### ISSUE TITLE
Erreur affichage état plugin

### ISSUE THREAD

**Issue by cedric-bollini** [domogik/domogik#103]
Plugin weather à l'état "stopped" sur la page qui liste tous les client/plugins et aussi sur la page du plugin alors que le plugin est bien démarré dans les logs.

manager.log : http://pastebin.com/GzmUjnNS
mq_forwarder.log : http://pastebin.com/4k6SBQNc
mq_broker.log : envoyer par mail à fritz_smh

**Comment by fritz-smh** [comment]
Avec tous les correctifs réalisés pour la 0.4.2, je pense qu'on a du résoudre un des soucis source de ce bug.
Pour le moment je le ferme, à vérifier après la sortie de la 0.4.2 si il est bien éliminé de ton côté!
