### ISSUE TITLE
install : better network interfaces handle

### ISSUE THREAD

**Issue by fritz-smh** [domogik/domogik#112]
during install : 
* find all existing interfaces

on admin/rest startup : 
* if the interface does not exists, trap the error
* or try to start on all interfaces with a * value in config ???

**Comment by Cereal2nd** [comment]
after some discussion we agreed we would handle this in the install script

we will select an interface in the install script and write this interface to the domogik.cfg
same will be done for the mq package

**Comment by Cereal2nd** [comment]
part one is committed in https://github.com/domogik/domogik/commit/4d17c37ff5c3f35fe5c27b6328e11a1758dfa1e3

**Comment by fritz-smh** [comment]
part two in 4d7a846

**Comment by fritz-smh** [comment]
part 3 in https://github.com/domogik/domogik-mq/commit/d2c34adc06a376e9a1c7e6c8c56774288e583fb1
(mq install : find automatically the ip adresse for config)

**Comment by fritz-smh** [comment]
part 4 (optionnal) : https://github.com/domogik/domogik-mq/commit/2c99baa4f474b2f4b572c355d8cad07145ef5f80
(mq config handle '*' : to be used with caution only for some demo purpose!)

**Comment by fritz-smh** [comment]
now waiting for a full test on a fresh rpi raspbian to validate all the process

**Comment by ferllings** [comment]
This generates an error for me:

$ sudo domogik/domogik-mq.repository.git/install.py
Traceback (most recent call last):
  File "domogik/domogik-mq.repository.git/install.py", line 18, in <module>
    from netifaces import interfaces, ifaddresses, AF_INET, AF_INET6
ImportError: No module named 'netifaces'

**Comment by fritz-smh** [comment]
Succesfully tested on a rpi b+ with raspbian jessie

But the rpi b+ is really too slow for the current release of domogik...
