### ISSUE TITLE
Handle a callback MQ message when device was created or change.

### ISSUE THREAD

**Issue by Nico0084** [domogik/domogik#120]
MQ send a message to plugin on new create device or changed parameters.
Don't knows if it's must be a message for all plugins or only plugin who handle device ?

**Comment by fritz-smh** [comment]
This would be a pub msg for all : 
- plugins
- domoweb
- etc

**Comment by Cereal2nd** [comment]
do we want this for just device updates or also for sensor/command updates

**Comment by Cereal2nd** [comment]
i moved all the device edit functions into the dbmgr
this way we can just add the edit pub message where we want

**Comment by Nico0084** [comment]
Indeed pub msg for sensors and command parameters could be good.
A pub msg for device client parent (plugin owner), domoweb and rest ,..... is the good way
event affected : 
- new device (or it's allready handle by device new fonction ?)
- removed device
- updated device
- updated sensor/command (but it probably the same as updated device)

**Comment by Cereal2nd** [comment]
Ok, with all the commits from today uit should be possible. to handle these
for events generated via the admin interface

Via the rest interface i have a bit more work before that one will work

**Comment by Cereal2nd** [comment]
all solved, so closing
