### ISSUE TITLE
scenario url start with "

### ISSUE THREAD

**Issue by tikismoke** [domogik/domogik#125]
If i create a scenario with the http command like this:
"http://somip/blablablabl"
the json in the db contains error and the scenario could no more be edit.
I have to remove the \" in the scenario json db to make it editable.

**Comment by fritz-smh** [comment]
Can you show us the json with the issue ?

**Comment by Cereal2nd** [comment]
tested with

{"type":"dom_condition","id":"1","IF":{"type":"cron.CronTest","id":"2","cron.cron":"* * * * *"},"DO":{"type":"call_url.CallUrlAction","id":"3","url":"http://gioogle.com"},"deletable":false}

and this works

**Comment by tikismoke** [comment]
Will post my exemple later...

Le 12 octobre 2015 09:08:19 GMT+02:00, Maikel Punie <notifications@github.com> a écrit :
>tested with
>
>{"type":"dom_condition","id":"1","IF":{"type":"cron.CronTest","id":"2","cron.cron":"*
>* * *
>*"},"DO":{"type":"call_url.CallUrlAction","id":"3","url":"http://gioogle.com"},"deletable":false}
>
>and this works
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/domogik/domogik/issues/125#issuecomment-147306226

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by tikismoke** [comment]
First working:
http://snag.gy/CkJ4q.jpg
adding "" and saving
http://snag.gy/4yHcG.jpg
Re-editing it (empty even moving cursors):
http://snag.gy/yo75b.jpg

**Comment by fritz-smh** [comment]
Sorry, but I really don't understand why you are adding some ""...

**Comment by tikismoke** [comment]
It as a try to make http request working.
Now i know it's not neccessary but when i try i found this bug.
If someone else make the same mistake, he will need to edit the Db or delete is scenario.

**Comment by fritz-smh** [comment]
ok, but does the url call work without "" now for you ?

I keep the ticket open : we will add \ before " in case of such errors ;)

**Comment by tikismoke** [comment]
Yes and no but need more test and will be another ticket if not.
Without " I receive SMS correctly.
