### ISSUE TITLE
Domogik installé, mais problème au lancement /.python-eggs

### ISSUE THREAD

**Issue by ifma** [domogik/domogik#127]
Au lancement de domogik => sudo /etc/init.d/domogik start
 * Starting xPL (python version)...Pas de r?pertoire, connexion avec HOME=/
 Done.
 * Starting Manager (with -d -r -x -s)...Pas de r?pertoire, connexion avec HOME=/
Traceback (most recent call last):
  File "/usr/local/bin/dmg_manager", line 9, in <module>
    load_entry_point('Domogik==0.4.0', 'console_scripts', 'dmg_manager')()
  File "build/bdist.linux-armv7l/egg/pkg_resources/__init__.py", line 558, in load_entry_point
  File "build/bdist.linux-armv7l/egg/pkg_resources/__init__.py", line 2682, in load_entry_point
  File "build/bdist.linux-armv7l/egg/pkg_resources/__init__.py", line 2355, in load
  File "build/bdist.linux-armv7l/egg/pkg_resources/__init__.py", line 2361, in resolve
  File "/opt/dmg/domogik-0.4.0b1/src/domogik/bin/manager.py", line 74, in <module>
    from domogik.common.utils import is_already_launched, STARTED_BY_MANAGER
  File "/opt/dmg/domogik-0.4.0b1/src/domogik/common/utils.py", line 42, in <module>
    from netifaces import interfaces, ifaddresses, AF_INET, AF_INET6
  File "build/bdist.linux-armv7l/egg/netifaces.py", line 7, in <module>
  File "build/bdist.linux-armv7l/egg/netifaces.py", line 4, in __bootstrap__
  File "build/bdist.linux-armv7l/egg/pkg_resources/__init__.py", line 1161, in resource_filename
  File "build/bdist.linux-armv7l/egg/pkg_resources/__init__.py", line 1861, in get_resource_filename
  File "build/bdist.linux-armv7l/egg/pkg_resources/__init__.py", line 1891, in _extract_resource
  File "build/bdist.linux-armv7l/egg/pkg_resources/__init__.py", line 1227, in get_cache_path
  File "build/bdist.linux-armv7l/egg/pkg_resources/__init__.py", line 1207, in extraction_error
pkg_resources.ExtractionError: Can't extract file(s) to egg cache

The following error occurred while trying to extract file(s) to the Python egg
cache:

  [Errno 13] Permission denied: '/.python-eggs'

The Python egg cache directory is currently set to:

  /.python-eggs

Perhaps your account does not have write access to this directory?  You can
change the cache directory by setting the PYTHON_EGG_CACHE environment
variable to point to an accessible directory.

 
 An error occured during manager startup.

Une idée ?

**Comment by fritz-smh** [comment]
Ca sent un souci de droits...
Va dans ton dossier domogik et fait : 
$ ls -ld .
$ ls -l .python-eggs
$ ls -l /.python-eggs
Et montre voir ton fichier /etc/default/domogik

**Comment by ifma** [comment]
Je t'ai pas dit, mais j'ai fait l'install sur un Pi2 / jeezy

pi@raspberrypi /opt/dmg $ cd /opt/dmg/domogik
pi@raspberrypi /opt/dmg/domogik $ ls -ld
drwxrwxr-x 7 root root 4096 oct.  10 19:10 .
pi@raspberrypi /opt/dmg/domogik $ ls -l .python-eggs
ls: impossible d'acc?der ? .python-eggs: Aucun fichier ou dossier de ce type
pi@raspberrypi /opt/dmg/domogik $ ls -l /.python-eggs
ls: impossible d'acc?der ? /.python-eggs: Aucun fichier ou dossier de ce type
pi@raspberrypi /opt/dmg/domogik $ cd /etc/default/domogik
-bash: cd: /etc/default/domogik: N'est pas un dossier
pi@raspberrypi /opt/dmg/domogik $ cd /etc/default        
pi@raspberrypi /etc/default $ dir
apache2        dbus	   fake-hwclock  kdm.d	     nss      ssh
avahi-daemon   devpts	   halt		 keyboard    ntp      timidity
bsdmainutils   domogik	   hdparm	 locale      rcS      tmpfs
console-setup  domogik-mq  hwclock	 networking  rsync    triggerhappy
cron	       domoweb	   ifplugd	 nfs-common  rsyslog  useradd
pi@raspberrypi /etc/default $ ls
apache2        dbus        fake-hwclock  kdm.d       nss      ssh
avahi-daemon   devpts      halt          keyboard    ntp      timidity
bsdmainutils   domogik     hdparm        locale      rcS      tmpfs
console-setup  domogik-mq  hwclock       networking  rsync    triggerhappy
cron           domoweb     ifplugd       nfs-common  rsyslog  useradd

J'ai dû oublié qqchose ou installé python de la mauvaise manière

**Comment by fritz-smh** [comment]
/etc/default/domogik c'est un fichier :)
Fait : cat /etc/default/domogik pour afficher son contenu

Sinon il semble que tu ais installé un 0.4.0b1... tu t'es basé sur quelle doc d'install ? Et surtout tu l'as trouvée comment ? (ça date un peu!)

**Comment by ifma** [comment]
J'ai suivi ce tuto à la lettre !
http://docs.domogik.org/domogik/dev/en/enduser/installation/index.html

pi@raspberrypi /etc/default $ cat /etc/default/domogik
# This file defines config parameters for domogik

#Start domogik daemon under this user
DOMOGIK_USER=domogik

# This variable can take 6 parameters :
# -d to start the database manager (launch only on master host)
# -r to start the rest component (launch only on master host)
# -x to start the xpl gw component (launch only on master host)
# -s to start the start scenario manager component (launch only on master host)

# TODO : OBSOLETE -E to manage external members (launch only on master host)
# TODO : OBSOLETE -p to regulary ping plugins 
# TODO : OBSOLETE -t <ping duration> to customize ping duration. Default : 20
# TODO : OBSOLETE -w <wait time between 2 ping> to customize ping delay. Default : 60

# Remember : Your domogik installation must have *one* and *only one*
# instance of each manager running.
# Your domogik installation won't start on this computer if :
#  - The database manager is not already running elsewhere on the network
#  - You do not pass -d parameter to the manager
MANAGER_PARAMS="-d -r -x -s"

# You may want to use a xPL hub which is not the one given with Domogik
# If so, set this option to 'false'
LAUNCH_DOMOGIK_XPL_HUB=true

# Two hubs are available in Domogik
# - the C hub 
# - the Domogik python hub
# By default, the Domogik python hub is used. On very slow computers, you may 
# want to use the C hub instead.
# Possible values are: c, python
DOMOGIK_XPL_HUB=python






###############################################################################
#               Time configuration for server starting/stopping               #
###############################################################################

# Time to wait for the server to die, in seconds
# If this value is set too low you might not
# let some servers to die gracefully and
# 'restart' will not work
DIETIME=2

# Time to wait for the server to start, in seconds
# If this value is set each time the server is
# started (on start or restart) the script will
# stall to try to determine if it is running
# If it is not set and the server takes time
# to setup a pid file the log message might
# be a false positive (says it did not start
# when it actually did)
STARTTIME=6








###############################################################################
#                   Obsolete C xPL hub configuration                          #
###############################################################################

# You can define one or many extra path(s) for Domogik startup scripts.
# This should only be useful if you use Domogik in developement mode (with 
# setup.py develop) or if you have a custom path install.
# PATH is needed to locate 1 application :
#  - xPL_Hub : the xPL hub, *not* installed by setup.py develop
CUSTOM_PATH=

# Interface where the xpl hub is supposed to listen for
HUB_IFACE="lo"

Il y a un autre tuto, une autre release que la 0.4.0b1 ?

**Comment by fritz-smh** [comment]
Oui, il suffit d'aller sur www.domogik.org => Télécharger et tu as les liens ;)
Ou sinon depuis http://docs.domogik.org/

Sinon je te conseille d'attendre la 0.4.2 qu'on devrait sortir cette semaine si tout va bien.

**Comment by fritz-smh** [comment]
Du coup, comme le bug est hors-sujet, je le clos.
Si tu as un autre souci avec l'install de la 0.4.1 ou 0.4.2 n'hésite pas à recréer un autre bug!

Et penses bien à tout nettoyer avant de refaire une tentative d'install : 
cd src/domogik/install
./uninstall.sh

**Comment by ifma** [comment]
Bonsoir,

La v 0.4.2. Est-elle sortie ?
Cdlt.
F.


De :  Fritz SMH <notifications@github.com>
Répondre à :  domogik/domogik <reply@reply.github.com>
Date :  lundi 12 octobre 2015 17:23
À :  domogik/domogik <domogik@noreply.github.com>
Cc :  Fabrice MARTIN <iphonefmartin@gmail.com>
Objet :  Re: [domogik] Domogik installé, mais problème au lancement /.python-eggs (#127)


Du coup, comme le bug est hors-sujet, je le clos.
Si tu as un autre souci avec l'install de la 0.4.1 ou 0.4.2 n'hésite pas à recréer un autre bug!

Et penses bien à tout nettoyer avant de refaire une tentative d'install : 
cd src/domogik/install
./uninstall.sh

**Comment by fritz-smh** [comment]
Pas encore :). D'ici quelques jours.
