### ISSUE TITLE
Clients are dead on raspberry pi B 512Mb

### ISSUE THREAD

**Issue by TheGrumpy** [domogik/domogik#131]
![capture](https://cloud.githubusercontent.com/assets/7392269/10466327/1767480a-71f4-11e5-88fd-d5dc89c06a64.PNG)

All is on the Screen !

**Comment by fritz-smh** [comment]
We think this issue should be corrected in 0.4.2 with all improvments we did.
I keep the ticket open until I checked on a rpi

**Comment by fritz-smh** [comment]
I checked with the fixes, it will be ok in 0.4.2 on a fresh rpi install using network interface eth0
