### ISSUE TITLE
Hooray, no orphans found on Rasp Pi B 512Mb

### ISSUE THREAD

**Issue by TheGrumpy** [domogik/domogik#132]
![orphan_device_empty](https://cloud.githubusercontent.com/assets/7392269/10466404/74ee005e-71f4-11e5-86dd-a71eaacd2520.PNG)

All is on the screen !

**Comment by fritz-smh** [comment]
Where you able to create some Domogik devices before going in this screen ?

**Comment by TheGrumpy** [comment]
Ooooopss !! You can close this ticket !! My only device is xPLduino and It's better if i read the manual ;-) !! Sorry !!

**Comment by fritz-smh** [comment]
ok, closing
