### ISSUE TITLE
merge rest and admin

### ISSUE THREAD

**Issue by Cereal2nd** [domogik/domogik#133]
merge rest and admin so they listen on the same port

/rest/<current rest urls> will be used

**Comment by fritz-smh** [comment]
Don't forget to update /etc/default/domogik manager's options

And also in manager, remove the related code. (I can do if you want)

**Comment by Cereal2nd** [comment]
merge is done in develop branch

**Comment by tikismoke** [comment]
How could we find a way to highlight user that he has to add /rest and change port for user interface like Domodroid?

A big advertising in doc?
I can add lot of test when sync is done...
But I'm not sure it's the right thinks to do.

**Comment by fritz-smh** [comment]
It is already in install doc and the release note ;)
