### ISSUE TITLE
Scenario add more error handling

### ISSUE THREAD

**Issue by tikismoke** [domogik/domogik#139]
Try to make a scenario using cron expression like:
 0 25 15 ? * MON,TUE,WED,THU,FRI * 
And get error in log and scenario not appear (exept in the DB).
https://gist.github.com/tikismoke/ee1f11b6fca451baf3ee
https://gist.github.com/tikismoke/288abed19af351d8b4fc

**Comment by fritz-smh** [comment]
Can you test with numbers insead of MON,TUE,.... ?

**Comment by tikismoke** [comment]
Using  this website works for me
http://crontab-generator.org/

**Comment by Cereal2nd** [comment]
i'm gonna reopen, as we should not crash on this, will need to add a new try/catch
