### ISSUE TITLE
scenario : add variables

### ISSUE THREAD

**Issue by fritz-smh** [domogik/domogik#142]
In scenario we will need variables to allow some actions. Here is my proposal :  

- variables can be of various type : bool, number, string
- variables will be stored in a dedicated table : variable, type, value

Blockly : 
- a block to set a variable (2 inputs : variable name, sensor or free field)
- a block to read a variable (for comparison, ...)
- in all input fields for actions, we should handle some tag to replace the tag by the variable value. Example of tag : {{variable_name}}. The replacement could be done only when the scenario is evaluated to True

**Comment by tikismoke** [comment]
We will also need a block to change a sensor value or send a command to a device.
If..... All Light off
If mirror read nanoztag(red) set Tobias present.

**Comment by fritz-smh** [comment]
This sort of feature is, in my opinion linked to some virtual devices.

Both virtual devices and variables are needed, but they have different goals.

Virtual devices = simulate a device and so you can for example change its status from a scenario, or when you put it on, it will launch a scenario.

Variables = a way to store informations (for heating management or anything else) and also store a sensor value in a variable and use it in a command thanks to the tag

**Comment by Cereal2nd** [comment]
the virtual devices is ok, althought they will require a virtual plugin ....

the variables, one question are they persistent? so do we keep track of
them in the db?

**Comment by fritz-smh** [comment]
As said in the ticket ;) .... persistent in a table

For virtual yes we need a plugin

**Comment by fritz-smh** [comment]
Closing the ticket : local variables have already been added. And virtual devices (domos's plugin) will be used for gloval variables
