### ISSUE TITLE
Scénario no repeat

### ISSUE THREAD

**Issue by tikismoke** [domogik/domogik#147]
I need a way to only run scenario once time and not repeatedly. Example SMS only once when disk >90%. Not 600 SMS in one day :(

**Comment by fritz-smh** [comment]
Basically we need sort of a flag in the scenario table to say the scenario was already true

When scenario is evaluated to True, and flag is False, set this flag to True and do the actions
When scenario is evaluated to True and flag is True, don't do the actions
When scenario is False, reset Flag to False

**Comment by tikismoke** [comment]
This mean it can simply be done with variable from your previous ticket.

**Comment by fritz-smh** [comment]
no, no... it would be a lot simplier for the user to not use variables for this :)

**Comment by Cereal2nd** [comment]
so some sort of hysteresis, if on no actions, if off trigger actions
this is pretty simple, only question do we want to track the state of the scenarios in the db then?
so at startup we have the previous state before shutdown?

**Comment by fritz-smh** [comment]
Yes we should store in case the user make the system rebbot each 24h for example. It will avoid getting some useless notifications for example

**Comment by tikismoke** [comment]
For boolean type it works (that's a good start things)
As value changed only from 1 to 0 or 0 to 1.
It is always a "front nontant ou descedant"

**Comment by Cereal2nd** [comment]
Do we need this configurable or will this apply to all scenarios
i think this should just apply to all scenarios

**Comment by tikismoke** [comment]
For now i'll try using virtual device in at least one scenario (just thinking about it 10min ago).

Don't know other point of view but for me in all scenario seems fine to.

**Comment by Cereal2nd** [comment]
its almost implemented , it will be finished tomorow

**Comment by tikismoke** [comment]
Just maybe a use case it will need configurable.
Consumption>5kW =>notify
10minutes later and still>5kW=>re-notify

**Comment by vdomos** [comment]
I test the last update of scenario.
if the scenario condition is True and as the test condition does not change, the scenario will not execute more ?
if we want an execution of the scenario each time it is true that no longer works, it's must return to false before. 
It's could be a problem for some case, no ?

**Comment by tikismoke** [comment]
Indeed it was the goal for number>

Maybe we have to find a way to set it to true after a certain time
