### ISSUE TITLE
Rouding of a sensor value in Admin interface

### ISSUE THREAD

**Issue by vdomos** [domogik/domogik#151]
With th Domoweb ticket "No rounding value in sensor widgets": https://github.com/domogik/domoweb/issues/52

I don't understand the difference/link  beetween  "Round value" in the Admin interface "Sensor properties" and Rounding value in Domoweb Widget.
Same use ?

![domogik_sensor_properties](https://cloud.githubusercontent.com/assets/1257481/10651698/6a550134-7851-11e5-93cc-b31886716e0d.png)

For the 2 sensors below in Domoweb snapshot, the "Round value" in the Admin="0.00"

![domoweb_widget_temp_2](https://cloud.githubusercontent.com/assets/1257481/10652057/a3e59290-7853-11e5-9e45-1d2206e7fc9e.png)

**Comment by Cereal2nd** [comment]
The admin interface i just for reducing the stats storage, in the docu its
perfectly explained how it works.
This will just result in less stats in your db.

for example if your sensor sends every second its value, and we would store
all values, this results in 3600 records per hour, with the stats reduce
only values that diferent at least the amount og the setting will be kept,
this usually results in about 75% storage reducing.

**Comment by vdomos** [comment]
ok,
thanks for this precision

**Comment by Cereal2nd** [comment]
here is the info about round value

http://docs.domogik.org/domogik/stable/en/package_development/plugins/json/sensors.html#round-value-explanation
