### ISSUE TITLE
Boolean type: command value type depending of sender

### ISSUE THREAD

**Issue by Nico0084** [domogik/domogik#154]
For a DT_type boolean command
The type of command value depending of where command come from. 
MQ receive a int type from domoweb
MQ receive a str type from domogik admin test button
In seems difference is in REST or websocket sender

**Comment by fritz-smh** [comment]
Nico, could you give more informations about the context ? Where are you using the result of the MQ command ?

**Comment by Nico0084** [comment]
If I remember ;)
Just an ascertainment that  in case of boolean command transmit by Domoweb, MQ receive an int ( 0/1) So conversion function must handle int type to y/n for db.
In case of REST boolean command data is an str ("0"/"1") , conversion must do handle str type to y/n for db.

**Comment by Cereal2nd** [comment]
No plan to fix, as websocket can not transfere the variable types

**Comment by Nico0084** [comment]
OK,  
But it's really a bad situation. 
The problem is also for number type.

A hilight information in conversion file section developper documentation should warn.

Because  all number type are impacted . All DT _type who use number and are a command must have conversion file who handle number type and string type.
I presume that same thing for DT_type list with index has number.
This is imposed  putting information  in other good place documentation as a warning.

**Comment by Cereal2nd** [comment]
yeah but i have no solution for it .....
i agree its not good

**Comment by Nico0084** [comment]
It's impossible to handle it in domogik-mq ?

**Comment by Cereal2nd** [comment]
no,

as the mq has no clue of the content of the message, it just forwards

**Comment by Nico0084** [comment]
Sorry  it's in REST to handle . Because it's REST who give str type ! not websocket by domoweb ;)

So If it's impossible, I think it' important to write this in developper doc.

**Comment by Cereal2nd** [comment]
ok i'll have another look
