### ISSUE TITLE
Idea: Enable choosing of the datatype in the admin GUI

### ISSUE THREAD

**Issue by vdomos** [domogik/domogik#159]
As we discussed in IRC  on  02/112015 12:57,
Possibility in futur release to add the choice of the datatype for a device in admin interface.

### Usage:
* For some chip like onewire DS2438 or DS2450 (digital to analog converter), the plugin should not freeze a value type, as it can be used to read a temperature, luminosity or gas.
* For DIY sensor, for example with Arduino emulator Oregon's sensor. The data is seen as a temperature by the receiver but can be any other.
* The use of  fixed "datatype" in  plugin's configuration  prevents any use of DIY sensor

### The idea

It' to create a specific data-type like **DT_Choice** to say in admin interface the possiblity to choose the real data-type in a list.

Exemple of **sensor** in info.json file:

    "sensors": {
	"Can0": {
		"name": "Can0",
                "data_type": "DT_Choice",
                "conversion": "",
                "incremental": false,
                "timeout": 0,
                "history": {
                    "store": true,
                    "duplicate": false,
                    "max": 0,
                    "expire": 0,
                    "round_value": 0
                }
	  },

**Comment by Cereal2nd** [comment]
Instead of dt-choice we will just introduce a special value to support this.

When this option is active we will not support conversions.

**Comment by vdomos** [comment]
Are there any conversions for the numeric type ?
I have only seen that for the binary type.

Will be still possible to apply a formula ?

**Comment by Cereal2nd** [comment]
formula would be possible

conversions are defined in the plugin, so we have no way to control the
conversions

**Comment by fritz-smh** [comment]
Cereal,
Do you plan to do it in 0.4.3 ?

**Comment by fritz-smh** [comment]
I think it will only be done in 0.5 now.
Moving to 0.5

**Comment by vdomos** [comment]
About this question (for my plugin script for example: datatype is only DT_Number for sensor_script  now)
Other possible idea to "force" a choice in admin GUI:

If the datatype is DT_Number in the info.json,  we can choose one of its child like "DT_Temp", "DT_Humidity" ... in the admin GUI

Idem for DT_Bool, for choosing  "DT_Switch", "DT_Enable"  "DT_Binary" ...

**Comment by Cereal2nd** [comment]
I was planning on allowing to select any child_data_type

for example if DT_Number is set in the plugin, allow all childs of DT_Number to be selected in the admin

**Comment by fritz-smh** [comment]
Seems fine

**Comment by vdomos** [comment]
Good

Will it be still possible to leave the type DT_Number if no child were found for a particular case ?
The same for DT_BOOL ?

**Comment by Cereal2nd** [comment]
yeah you can leave it to the parent, or you can select the child
