### ISSUE TITLE
Scenario cron (Enchancement)

### ISSUE THREAD

**Issue by tikismoke** [domogik/domogik#160]
Really need a system that's allow to select a date friendly.

Just test the Jeedom scenario and to select a date or time it's really pleasant.

**Comment by fritz-smh** [comment]
By date you mean each day/each week/zach monday/.... ?

**Comment by tikismoke** [comment]
Meaning an easy access to a sort of datepicker.

Something like this for exemple;
http://domotique34.com/wp-content/uploads/2013/04/horaire.png
Maybe a lib already do that convert to cron

The opposite of this:
http://cronexpressiondescriptor.azurewebsites.net/

**Comment by Cereal2nd** [comment]
i think we can do this with a custom block that results in a cronexpression
This way we can have one time mangement trigger and not multiple.

currently cron supports:
- real cron * * * * *
- @yearly
- @anually
- @monthly
- @weekly
- @daily
- @midnight
- @hourly
- @fullmoon
- @newmoon
- @firstquarter
- @lastquarter
- @equinox
- @solstice
- @dusk
- @dawn

**Comment by tikismoke** [comment]
Not sure about how it is easy of course ;)

Think it would make user experience more friendly.

**Comment by fritz-smh** [comment]
For 0.5, a time block have been added and also a 'current time' block.
This allows already main usages...

I keep the ticket opened but move it now a later release ;)

**Comment by Nico0084** [comment]
I'm working on it  :) .....

**Comment by tikismoke** [comment]
Done by nico #384 
Just a little problem with translation in text:

https://snag.gy/ZRuvWl.jpg

**Comment by Nico0084** [comment]
Yes I know that point. it's an cronstrue lib "issue" who handle seconds
field in some case, years presence is detected only with 4 digit at end.

So if you set year at all '*" (in this case you could set nothing. Year
field is optional, and human expression is good) with "*" cronstrue make
confusion with minutes.

If you set "2016/3", construe don't detect year field (not 4 end digit)
also.

This is construe lib who must be fixed to correctly handle year..


2016-12-05 19:18 GMT+01:00 tikismoke <notifications@github.com>:

**Comment by Nico0084** [comment]
Find a way to fix human readable :) PR #387

**Comment by tikismoke** [comment]
For me this one could be closed.
