### ISSUE TITLE
Log Rotate lock clients and MQ, this could induce inappropriate behavior

### ISSUE THREAD

**Issue by Nico0084** [domogik/domogik#161]
When log rotate it seems impossible to write in log, some stroke timeout appear
In fact more there's much log solicitation, the more problems can happen.
So more plugins, more potentially problem.
eg: 
* On init plugin a get-device could be lock and induce a non response of MQ (timeout).
* An admin request could fail in same situation

**Comment by Cereal2nd** [comment]
to solve this we will need to disable logrotate for the mq-logs

and then use a RotatingFileHandler in the domogik logger, as this will handle the logrotate for us

**Comment by fritz-smh** [comment]
It seems fine for me
