### ISSUE TITLE
Update font awesome lib to last rev.

### ISSUE THREAD

**Issue by Nico0084** [domogik/domogik#162]
Lib have new nice icones  :)

**Comment by Cereal2nd** [comment]
where are they used?

**Comment by fritz-smh** [comment]
Surely in ozwave admin pages

**Comment by Nico0084** [comment]
In base.html here :
https://github.com/domogik/domogik/blob/0192e5d59b9319c11f5fca2d8e9cd8c094d1bb0c/src/domogik/admin/themes/default/templates/base/base.html#L23

nav.html : https://github.com/domogik/domogik/blob/0192e5d59b9319c11f5fca2d8e9cd8c094d1bb0c/src/domogik/admin/themes/default/templates/base/nav.html#L17

and others places... qurely in ozwave admin

**Comment by Cereal2nd** [comment]
merged, into develop
