### ISSUE TITLE
Check js lib to merge with advanced administration ozwave plugin

### ISSUE THREAD

**Issue by Nico0084** [domogik/domogik#163]
used by oz wave :
* bootbox
* bootstrap-switch
* bootstrap-sidebar 
* jquery.data tables
* jquery.data tables-themeroller
* jstree
* kinetic-v5.1.0

**Comment by Cereal2nd** [comment]
Don't think this is usefull, as we don't need these plugins in the base, so why would we include them?

**Comment by Nico0084** [comment]
It's a fritz request to look if including some ozwave js lib could interesting for domogik admin or other dmg client. ??

**Comment by Cereal2nd** [comment]
Then i rather create a special plugin that only has these js files included.

You can then add a dependency so that this special plugin needs to be
installed before ozwave or the other plugins that need them can be
installed/started.

I want to keep the admin as clean as possible
