### ISSUE TITLE
scenario : add IF stattement

### ISSUE THREAD

**Issue by fritz-smh** [domogik/domogik#164]
To allow : 
WHEN [.....]
IF [...] THEN
    ...
ELSE 
    ....
FI

Usefull when we have one trigger and several actions possible for a trigger (depending on the time for example)

**Comment by fritz-smh** [comment]
As discussed a while ago with cereal this would be not easy to implement and maybe not fine with system resources usage...

As for now we can create several scenarios, this is not a blocking point.

Moving to 0.6

**Comment by Cereal2nd** [comment]
this is implemented in the newScenario branch
