### ISSUE TITLE
Plugin: new plugin "Script"

### ISSUE THREAD

**Issue by vdomos** [domogik/domogik#166]
Hi, 
Here is a new simple plugin that allows to launch scripts (shell, python ...) in Domogik.

There is two types of script for now:
* Action Script: 
Execute the script and returns a status of execution
* Script Sensor: 
Execute the script that returns a given sensor (DT_Number datatype only for now)

Plugin available here https://github.com/vdomos/domogik-plugin-script with a link to the doc in the README file

Any resemblance with another plugin Script Home Automation software is purely the result of chance;-)

**Comment by tikismoke** [comment]
Whouaou this one is very interesting. We can use it to get value and send command to the 0.3 where plugin still not exists.
Lots of other usage in mind.

**Comment by fritz-smh** [comment]
Hi,

I had a look on it. 
This is an interesting plugin indeed.

About the "TODO" in the doc, I think you should not include http (and xml/json path extractions) in this plugin.
The more a plugin is simple, the more it will be easy to maintain and the less work on it you will have (on tests especially).
You should do a new domogik-plugin-http plugin instead ;)

**Comment by fritz-smh** [comment]
I read this in the doc : 
```
        exec.basic                                                                                                      
        {                                                                                                               
                arg='canape on'                                                                                         
                pid='cmd_action'                                                                                        
                program='/home/dan/bin/setLum.sh'                                                                       
                status='start'                                                                                          
        }                   
```

pid as type... isn't it strange ?

**Comment by fritz-smh** [comment]
In the doc there are a lot of raw:html part... this is quite strange

About pictures, don't set sizes on them, it could break layout in the admin on a smartphone. No option is better ;)

**Comment by vdomos** [comment]
Hi,

pid as type... isn't it strange ? => In the xPL doc, the 'pid' parameter of exec.basic schema is describe as this:

    pid=[anything you like - this is just sent back unchanged in the status messages]

I use it to make the difference between action / info commands.

yes, This is not clean to use **raw:html** but I have not found how to force line break to make the document more readable.
ok, for the picture's size size, I will correct.

Good idea also to do only simple plugins.

**Comment by fritz-smh** [comment]
Hi,

Definitly, don't use raw:html ;). Let's speak over irc of the real need about line break. 

I wanted to test the plugin, but even reading the doc, i am quite lost about the 2 kind of scripts. Maybe the doc should give 2 short example scripts with stdout example and return code also

Fritz

**Comment by vdomos** [comment]
And if I add this in the documentation?

**Action script**, only th return code is test to verify that execution of script is ok. It's use only to execute any executable file to do a action. The return to the device is boolean. I choose DT_Trigger. 

**Info script**, return code is test and a value is return for a sensor device. It's use to retrieve a value from any executable file. The return to the device is a number (DT_Number)

Examples:

    # Action script:
    $ ~/bin/setLum.sh salon off ; echo $?
    0
    
    # Info script:
    $ ~/bin/getElec.sh -jour
    0.270

**Comment by fritz-smh** [comment]
It is indeed clearer.

**Comment by fritz-smh** [comment]
Closing as the plugin exists
