### ISSUE TITLE
scenario : add a new block : on value change

### ISSUE THREAD

**Issue by fritz-smh** [domogik/domogik#171]
Example with the plugin callerid.
When an inbound call happens, a new value is inserted in database, so the value changes.

To be able to do some action on inbound call, a new block is needed : 

WHEN [ sensor values changes (id) ]
DO ....

Fritz

**Comment by tikismoke** [comment]
Good idea for notification.

**Comment by Cereal2nd** [comment]
actually the sensorTest case thats currently in there will only trigger when the value changed

**Comment by fritz-smh** [comment]
But we have no way to check a DT_String sensor.
We can do comparisons, boolean tests but on DT_String if I don't want to compare, I can do nothing :)

Example : I want to create a scenario that do something each time the sensor value (a phone number) changes.

**Comment by fritz-smh** [comment]
To be more precise : 

We should have a way to detect if a new value has been inserted in database for the sensor, even if the previous one is the same than the new one.
It would be usefull for example to notify about inbound phone calls (if the same people call you the morning and the evening for example but nobody calls between)

To keep in 0.5 ? Or move in 0.6 ?

**Comment by Cereal2nd** [comment]
closeing this as 225 also fixes this
