### ISSUE TITLE
butler : still not ok with utf8 inputs

### ISSUE THREAD

**Issue by fritz-smh** [domogik/domogik#172]
Example with : "свет"
Butler responds : ERR: No Reply Matched

**Comment by axboct** [comment]
https://github.com/aichaos/rivescript-python/issues/10

**Comment by fritz-smh** [comment]
Interesting. I will include the newly rivescript release in Domogik 0.5.

**Comment by fritz-smh** [comment]
Should be ok now: 
https://github.com/domogik/domogik/commit/cf76939874d9817b72d251471a50439fe47a6e52
https://github.com/domogik/domogik/commit/a8bf40de47c6d4248673e6fb06cbf64e5175867a

But I have still to do some improvments on latin charset

@axboct tell me if the fix is ok on your side (and make sure to also use utf8 russian responses from the butler)

**Comment by fritz-smh** [comment]
Notice : rivescript 1.8.0 introduces a new way to handle [...] blocks... some triggers (a lot sadly) are not ok anymore...

More informations here : https://github.com/aichaos/rivescript-js/issues/48
(with a comment from me to describe the issue)

**Comment by kirsle** [comment]
RiveScript v1.8.1 fixes the issue described in https://github.com/aichaos/rivescript-js/issues/48

**Comment by axboct** [comment]
without changes :(
The example uses a request temperature device named "дом" 
```
2015-11-20 21:25:13,968 domogik-butler INFO Received message : {u'text': u'\u0442\u0435\u043c\u043f\u0435\u0440\u0430\u0442\u0443\u0440\u0430 \u0434\u043e\u043c', u'media': u'chat', u'identity': u'admin', u'source': u'core-butler.skyworker'}
2015-11-20 21:25:13,969 domogik-butler DEBUG Before transforming query : температура дом
2015-11-20 21:25:13,969 domogik-butler DEBUG After transforming query : температура дом
2015-11-20 21:25:13,969 domogik-butler DEBUG Before calling Rivescript brain for processing : температура дом (type=<type 'unicode'>)
2015-11-20 21:25:13,977 domogik-butler DEBUG Processing finished. The reply is : температура дом  [ERR: Error when executing Python object]
2015-11-20 21:25:13,978 domogik-butler INFO Send response over MQ : {'mood': None, 'media': u'chat', 'sex': 'female', 'location': None, 'text': u'\u0442\u0435\u043c\u043f\u0435\u0440\u0430\u0442\u0443\u0440\u0430 \u0434\u043e\u043c  [ERR: Error when executing Python object]', 'reply_to': u'core-butler.skyworker', 'identity': 'Aria'}
```
fore test I use simple script  (from python_get_sensor_value.rive)
```python
# -*- coding: utf-8 -*-
from domogik.butler.brain import get_sensor_value
dt_type = 'DT_Temp'
unit = 'degres'
args=raw_input('key_input: ')
device_name = args
value = get_sensor_value(dt_type, device_name)
#    if value == None:
 #       print (u"неизвестнo")
print (u"{0} {1}".format(value, unit))
```
response is OK
```
key_input: дом
Device name = дом
Preferences found for datatype 'DT_Temp' : sensor 'current_temperature'
Candidates for the appropriate datatype : [{'sensor_name': u'Temperature', 'device_name': u'\u0434\u043e\u043c', 'sensor_id': 13, 'sensor_reference': u'current_temperature', 'last_value': u'7', 'device_id': 2}, {'sensor_name': u'Temperature', 'device_name': u'disk', 'sensor_id': 69, 'sensor_reference': u'temperature', 'last_value': u'40', 'device_id': 14}]
The sensor is : {'sensor_name': u'Temperature', 'device_name': u'\u0434\u043e\u043c', 'sensor_id': 13, 'sensor_reference': u'current_temperature', 'last_value': u'7', 'device_id': 2}
7 degres
```

**Comment by kirsle** [comment]
@fritz-smh in the default Python RiveScript module when an object raises an exception at run-time, the exception message is printed to standard error. I'm not sure what your app does with this but it may be something to look into making more visible to the user.

For example

```
> object test python
	return 5/0
< object

+ test
- <call>test</call>
```

```
You> test
[RS] Error executing Python object: division by zero
Bot> [ERR: Error when executing Python object]
```

**Comment by fritz-smh** [comment]
@kirsle indeed, I have in my todo to find a way to properly log rivescript side issues in our application logs (and the application runs in background). I use a lot of python functions for advanced usages and it may happen that for some reasons it crashes and sadly we have to restart the component in a terminal to check what is not going fine.

If you have any idea I would be glad to ear them :)

The only option I have in mind for now is to tweak rivescript.py file to use my application logger when an error occurs (as we can add some item to rivescript object easily I can easily add my logger in it.

By the way, another question : is there a roadmap about the next rivescript releases ?

**Comment by fritz-smh** [comment]
@axboct it should be ok now. Please check.

**Comment by axboct** [comment]
missed unicode
```
diff --git a/src/domogik/butler/brain.py b/src/domogik/butler/brain.py
index 6a016f4..e8ade4f 100644
--- a/src/domogik/butler/brain.py
+++ b/src/domogik/butler/brain.py
@@ -283,13 +283,13 @@ def filter_sensors_by_reference_and_device_name(candidates, reference, device_na
 def filter_sensors_by_device_name(candidates, device_name, log):
     """ for each given sensor, check the most appropriate choice depending on device_name
     """
-    log.info("Filter sensors by device name ({0})...".format(device_name))
+    log.info(u"Filter sensors by device name ({0})...".format(device_name))
     device_name = clean_input(device_name)
 
     # first, check if we got an exact match !
     for a_sensor in candidates:
         try:
-            if clean_input(a_sensor["device_name"]) == device_name:
+            if clean_input(a_sensor[u"device_name"]) == device_name:
                 return a_sensor
         except:
             log.error(u"ERROR : {0}".format(traceback.format_exc()))
```

**Comment by axboct** [comment]
can be closed. everything is working

**Comment by fritz-smh** [comment]
Great :)
