### ISSUE TITLE
Scenario: Add the possiblity to use sensor value in action

### ISSUE THREAD

**Issue by vdomos** [domogik/domogik#174]
Hello,

With the futur new block : **on value change**

For example, 
* Update a "ThingSpeak" Channel:

WHEN [ **{sensor values id}** changes]
   DO <Call a URL>
       url="https://api.thingspeak.com/update?key=apikey&field1= **{sensor values id}**"

* With the CID plugin,  mail the inbound call number (not yet possible ?)

**Comment by fritz-smh** [comment]
Hi,
This is in my todo ;)
Its is indeed not yet possible

**Comment by Cereal2nd** [comment]
its implemented in the newScenario branch
