### ISSUE TITLE
install : xPL_Hub can't be found

### ISSUE THREAD

**Issue by overload08** [domogik/domogik#176]
Version : 0.4.2
Plateforme : Raspberry Pi 2

On Domogik 0.4.2 install :

root@pi:/opt/dmg/domogik# ./test_config.py

 [ Start to test configuration ]
 [ Check this script is started as root ]
 ==> Correctly started with root privileges.
 [ Test imports ]
 ==> Imports are good
 [ Check hostname ]
 ==> Hostname characters are OK
 [ Test global config file ]
 ==> Global config file exists and contains right stuff
 [ Check manager params ]
 ==> Manager params seem good
 [ Check xPL_Hub is in path ]
 ==> xPL_Hub can't be found, please double check CUSTOM_PATH is correctly defined if you are in development mode. In install mode, check your architecture is supported or check src/domogik/xpl/tools/COMPILE.txt, then restart test_config.py

**Comment by overload08** [comment]
root@pi:/opt/dmg/domogik# ./install.py --dist-packages
 [ Check this script is started as root ]
 ==> Correctly started with root privileges.
Namespace(admin_interfaces=None, admin_port=None, admin_ssl_certificate=None, admin_ssl_key=None, admin_use_ssl=None, backup_folder=None, butler_lang=None, butler_name=None, butler_sex=None, command_line=False, config=False, database_host=None, database_name=None, database_password=None, database_port=None, database_prefix=None, database_type=None, database_user=None, db=False, dist_packages=True, domogik_bind_interface=None, domogik_broadcast=None, domogik_libraries_path=None, domogik_log_dir_path=None, domogik_log_level=None, domogik_pid_dir_path=None, hub_interfaces=None, hub_log_bandwidth=None, hub_log_dir_path=None, hub_log_invalid_data=None, hub_log_level=None, mq=False, no_create_database=False, rest_clean_json=None, rest_interfaces=None, rest_port=None, rest_ssl_certificate=None, rest_ssl_key=None, rest_use_ssl=None, setup=False, skip_database_backup=False, test=False, user=None, user_creation=True, user_shell=None)
 [ Check the sources location (not in /root/ or / ]
/opt/dmg/domogik-0.4.2
 [ Check that domogik-mq is installed ]
 [ Process some database upgrade issues with previous releases ]
Domogik configuration file found. reading configuration...

Checking if some tables need to be converted to InnoDB...

- server : 127.0.0.1:3306

- database : domogik

- credentials : domogik/****

All your tables are InnoDB. There is nothing to do

Hit http://mirrordirector.raspbian.org wheezy Release.gpg
Hit http://archive.raspberrypi.org wheezy Release.gpg
Hit http://archive.raspberrypi.org wheezy Release
Hit http://mirrordirector.raspbian.org wheezy Release
Hit http://archive.raspberrypi.org wheezy/main armhf Packages
Hit http://mirrordirector.raspbian.org wheezy/main armhf Packages
Hit http://mirrordirector.raspbian.org wheezy/firmware armhf Packages
Ign http://archive.raspberrypi.org wheezy/main Translation-en
Ign http://mirrordirector.raspbian.org wheezy/firmware Translation-en
Ign http://mirrordirector.raspbian.org wheezy/main Translation-en
Reading package lists... Done
Argparse module for python is already installed
Obtaining flask-themes2 from git+git://github.com/sysr-q/flask-themes2.git#egg=flask_themes2-dev
  Updating ./src/flask-themes2 clone
  Running setup.py egg_info for package flask-themes2

Requirement already satisfied (use --upgrade to upgrade): Flask>=0.6 in /usr/local/lib/python2.7/dist-packages (from flask-themes2)
Requirement already satisfied (use --upgrade to upgrade): simplejson in /usr/local/lib/python2.7/dist-packages/simplejson-3.8.1-py2.7-linux-armv7l.egg (from flask-themes2)
Requirement already satisfied (use --upgrade to upgrade): Werkzeug>=0.7 in /usr/local/lib/python2.7/dist-packages (from Flask>=0.6->flask-themes2)
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.4 in /usr/lib/python2.7/dist-packages (from Flask>=0.6->flask-themes2)
Requirement already satisfied (use --upgrade to upgrade): itsdangerous>=0.21 in /usr/local/lib/python2.7/dist-packages (from Flask>=0.6->flask-themes2)
Installing collected packages: flask-themes2
  Running setup.py develop for flask-themes2
    Checking .pth file support in /usr/local/lib/python2.7/dist-packages/
    /usr/bin/python -E -c pass
    TEST PASSED: /usr/local/lib/python2.7/dist-packages/ appears to support .pth files

    Creating /usr/local/lib/python2.7/dist-packages/Flask-Themes2.egg-link (link to .)
    Flask-Themes2 0.1.4 is already the active version in easy-install.pth

    Installed /opt/dmg/domogik-0.4.2/src/flask-themes2
Successfully installed flask-themes2
Cleaning up...
Reading package lists... Done
Building dependency tree
Reading state information... Done
alembic is already the newest version.
gcc is already the newest version.
gettext is already the newest version.
git is already the newest version.
libffi-dev is already the newest version.
libpq-dev is already the newest version.
libssl-dev is already the newest version.
libusb-1.0-0-dev is already the newest version.
libzmq-dev is already the newest version.
python is already the newest version.
python-babel is already the newest version.
python-daemon is already the newest version.
python-dev is already the newest version.
python-flask is already the newest version.
python-flaskext.wtf is already the newest version.
python-gluon is already the newest version.
python-magic is already the newest version.
python-mysqldb is already the newest version.
python-netifaces is already the newest version.
python-openssl is already the newest version.
python-pip is already the newest version.
python-pkg-resources is already the newest version.
python-psutil is already the newest version.
python-psycopg2 is already the newest version.
python-requests is already the newest version.
python-serial is already the newest version.
python-setuptools is already the newest version.
python-simplejson is already the newest version.
python-sphinx is already the newest version.
python-sqlalchemy is already the newest version.
python-tornado is already the newest version.
python-twisted is already the newest version.
python-zmq is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
Requirement already satisfied (use --upgrade to upgrade): Flask-Login in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): Flask in /usr/local/lib/python2.7/dist-packages (from Flask-Login)
Requirement already satisfied (use --upgrade to upgrade): Werkzeug>=0.7 in /usr/local/lib/python2.7/dist-packages (from Flask->Flask-Login)
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.4 in /usr/lib/python2.7/dist-packages (from Flask->Flask-Login)
Requirement already satisfied (use --upgrade to upgrade): itsdangerous>=0.21 in /usr/local/lib/python2.7/dist-packages (from Flask->Flask-Login)
Cleaning up...
Requirement already satisfied (use --upgrade to upgrade): Flask-Babel in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): Flask in /usr/local/lib/python2.7/dist-packages (from Flask-Babel)
Requirement already satisfied (use --upgrade to upgrade): Babel>=1.0 in /usr/local/lib/python2.7/dist-packages (from Flask-Babel)
Requirement already satisfied (use --upgrade to upgrade): speaklater>=1.2 in /usr/local/lib/python2.7/dist-packages (from Flask-Babel)
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.5 in /usr/lib/python2.7/dist-packages (from Flask-Babel)
Requirement already satisfied (use --upgrade to upgrade): Werkzeug>=0.7 in /usr/local/lib/python2.7/dist-packages (from Flask->Flask-Babel)
Requirement already satisfied (use --upgrade to upgrade): itsdangerous>=0.21 in /usr/local/lib/python2.7/dist-packages (from Flask->Flask-Babel)
Requirement already satisfied (use --upgrade to upgrade): pytz>=0a in /usr/local/lib/python2.7/dist-packages (from Babel>=1.0->Flask-Babel)
Cleaning up...
Requirement already satisfied (use --upgrade to upgrade): Flask-Bootstrap in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): Flask>=0.8 in /usr/local/lib/python2.7/dist-packages (from Flask-Bootstrap)
Requirement already satisfied (use --upgrade to upgrade): dominate in /usr/local/lib/python2.7/dist-packages (from Flask-Bootstrap)
Requirement already satisfied (use --upgrade to upgrade): visitor in /usr/local/lib/python2.7/dist-packages (from Flask-Bootstrap)
Requirement already satisfied (use --upgrade to upgrade): Werkzeug>=0.7 in /usr/local/lib/python2.7/dist-packages (from Flask>=0.8->Flask-Bootstrap)
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.4 in /usr/lib/python2.7/dist-packages (from Flask>=0.8->Flask-Bootstrap)
Requirement already satisfied (use --upgrade to upgrade): itsdangerous>=0.21 in /usr/local/lib/python2.7/dist-packages (from Flask>=0.8->Flask-Bootstrap)
Cleaning up...
Requirement already satisfied (use --upgrade to upgrade): sphinx-better-theme in /usr/local/lib/python2.7/dist-packages
Cleaning up...
Requirement already satisfied (use --upgrade to upgrade): sqlalchemy-utils in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/dist-packages (from sqlalchemy-utils)
Requirement already satisfied (use --upgrade to upgrade): SQLAlchemy>=1.0 in /usr/local/lib/python2.7/dist-packages (from sqlalchemy-utils)
Cleaning up...
 [ Run setup.py ]
******************************************
use: mysql-python
use: magic-file-extensions
******************************************
running develop
Checking .pth file support in /usr/local/lib/python2.7/dist-packages/
/usr/bin/python -E -c pass
TEST PASSED: /usr/local/lib/python2.7/dist-packages/ appears to support .pth files
running egg_info
writing requirements to src/Domogik.egg-info/requires.txt
writing src/Domogik.egg-info/PKG-INFO
writing top-level names to src/Domogik.egg-info/top_level.txt
writing dependency_links to src/Domogik.egg-info/dependency_links.txt
writing entry points to src/Domogik.egg-info/entry_points.txt
reading manifest file 'src/Domogik.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'README.txt'
writing manifest file 'src/Domogik.egg-info/SOURCES.txt'
running build_ext
Creating /usr/local/lib/python2.7/dist-packages/Domogik.egg-link (link to src)
Domogik 0.4.2 is already the active version in easy-install.pth
Installing dmg_testrunner script to /usr/local/bin
Installing dmg_version script to /usr/local/bin
Installing dmg_send script to /usr/local/bin
Installing dmg_manager script to /usr/local/bin
Installing dmg_package script to /usr/local/bin
Installing dmg_hub script to /usr/local/bin
Installing dmg_dump script to /usr/local/bin

Installed /opt/dmg/domogik-0.4.2/src
Processing dependencies for Domogik==0.4.2
Searching for ephem==3.7.6.0
Best match: ephem 3.7.6.0
Processing ephem-3.7.6.0-py2.7-linux-armv7l.egg
ephem 3.7.6.0 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/ephem-3.7.6.0-py2.7-linux-armv7l.egg
Searching for pyzmq==15.0.0
Best match: pyzmq 15.0.0
Processing pyzmq-15.0.0-py2.7-linux-armv7l.egg
pyzmq 15.0.0 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/pyzmq-15.0.0-py2.7-linux-armv7l.egg
Searching for Magic-file-extensions==0.2
Best match: Magic-file-extensions 0.2
Adding Magic-file-extensions 0.2 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Searching for requests==0.12.1
Best match: requests 0.12.1
Adding requests 0.12.1 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Searching for tornado==4.3
Best match: tornado 4.3
Processing tornado-4.3-py2.7-linux-armv7l.egg
tornado 4.3 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/tornado-4.3-py2.7-linux-armv7l.egg
Searching for Flask-Themes2==0.1.4
Best match: Flask-Themes2 0.1.4
Flask-Themes2 0.1.4 is already the active version in easy-install.pth

Using /opt/dmg/domogik-0.4.2/src/flask-themes2
Searching for Flask-Babel==0.9
Best match: Flask-Babel 0.9
Flask-Babel 0.9 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages
Searching for Flask-Login==0.3.2
Best match: Flask-Login 0.3.2
Flask-Login 0.3.2 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages
Searching for Flask-WTF==0.6
Best match: Flask-WTF 0.6
Adding Flask-WTF 0.6 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Searching for Flask==0.10.1
Best match: Flask 0.10.1
Flask 0.10.1 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages
Searching for Twisted==12.0.0
Best match: Twisted 12.0.0
Adding Twisted 12.0.0 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Searching for netifaces==0.8
Best match: netifaces 0.8
Adding netifaces 0.8 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Searching for pyserial==2.5
Best match: pyserial 2.5
Adding pyserial 2.5 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Searching for pip==1.1
Best match: pip 1.1
Adding pip 1.1 to easy-install.pth file
Installing pip-2.7 script to /usr/local/bin

Using /usr/lib/python2.7/dist-packages
Searching for psycopg2==2.4.5
Best match: psycopg2 2.4.5
Adding psycopg2 2.4.5 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Searching for MySQL-python==1.2.3
Best match: MySQL-python 1.2.3
Adding MySQL-python 1.2.3 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Searching for psutil==0.5.1
Best match: psutil 0.5.1
psutil 0.5.1 is already the active version in easy-install.pth

Using /usr/lib/pymodules/python2.7
Searching for pyOpenSSL==0.13
Best match: pyOpenSSL 0.13
pyOpenSSL 0.13 is already the active version in easy-install.pth

Using /usr/lib/pymodules/python2.7
Searching for simplejson==3.8.1
Best match: simplejson 3.8.1
Processing simplejson-3.8.1-py2.7-linux-armv7l.egg
simplejson 3.8.1 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/simplejson-3.8.1-py2.7-linux-armv7l.egg
Searching for alembic==0.3.4
Best match: alembic 0.3.4
Adding alembic 0.3.4 to easy-install.pth file
Installing alembic script to /usr/local/bin

Using /usr/lib/python2.7/dist-packages
Searching for SQLAlchemy==1.0.9
Best match: SQLAlchemy 1.0.9
SQLAlchemy 1.0.9 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages
Searching for distribute==0.6.24dev-r0
Best match: distribute 0.6.24dev-r0
Adding distribute 0.6.24dev-r0 to easy-install.pth file
Installing easy_install script to /usr/local/bin
Installing easy_install-2.7 script to /usr/local/bin
Installing easy_install-2.6 script to /usr/local/bin

Using /usr/lib/python2.7/dist-packages
Searching for backports-abc==0.4
Best match: backports-abc 0.4
Processing backports_abc-0.4-py2.7.egg
backports-abc 0.4 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/backports_abc-0.4-py2.7.egg
Searching for certifi==2015.11.20
Best match: certifi 2015.11.20
Processing certifi-2015.11.20-py2.7.egg
certifi 2015.11.20 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/certifi-2015.11.20-py2.7.egg
Searching for singledispatch==3.4.0.3
Best match: singledispatch 3.4.0.3
Processing singledispatch-3.4.0.3-py2.7.egg
singledispatch 3.4.0.3 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/singledispatch-3.4.0.3-py2.7.egg
Searching for backports.ssl-match-hostname==3.4.0.2
Best match: backports.ssl-match-hostname 3.4.0.2
Processing backports.ssl_match_hostname-3.4.0.2-py2.7.egg
backports.ssl-match-hostname 3.4.0.2 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/backports.ssl_match_hostname-3.4.0.2-py2.7.egg
Searching for Jinja2==2.6
Best match: Jinja2 2.6
Adding Jinja2 2.6 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Searching for speaklater==1.3
Best match: speaklater 1.3
speaklater 1.3 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages
Searching for Babel==2.1.1
Best match: Babel 2.1.1
Babel 2.1.1 is already the active version in easy-install.pth
Installing pybabel script to /usr/local/bin

Using /usr/local/lib/python2.7/dist-packages
Searching for WTForms==1.0.1
Best match: WTForms 1.0.1
Adding WTForms 1.0.1 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Searching for itsdangerous==0.24
Best match: itsdangerous 0.24
itsdangerous 0.24 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages
Searching for Werkzeug==0.11.2
Best match: Werkzeug 0.11.2
Werkzeug 0.11.2 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages
Searching for Mako==0.7.0
Best match: Mako 0.7.0
Adding Mako 0.7.0 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Searching for six==1.1.0
Best match: six 1.1.0
Adding six 1.1.0 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Searching for pytz==2015.7
Best match: pytz 2015.7
pytz 2015.7 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages
Searching for MarkupSafe==0.15
Best match: MarkupSafe 0.15
Adding MarkupSafe 0.15 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Finished processing dependencies for Domogik==0.4.2
 [ Create domogik user ]
As what user should domogik run? [domogik]:
  [ Create domogik user ]
 ==> Correctly created domogik user
 [ Copy files ]
 ==> Directory /etc/domogik already exists
 ==> Copyed file src/domogik/examples/config/domogik.cfg.sample
 ==> Copyed file src/domogik/xpl/hub/examples/config/xplhub.cfg.sample
 ==> Directory /var/cache/domogik already exists
 ==> Directory /var/cache/domogik/pkg-cache already exists
 ==> Directory /var/cache/domogik/cache already exists
 ==> Directory /var/lib/domogik already exists
 ==> Directory /var/lib/domogik/domogik_packages already exists
 ==> Copyed file src/domogik/common/__init__.py
 ==> Directory /var/lib/domogik/resources already exists
 ==> Directory /var/lib/domogik/resources/butler already exists
 ==> Directory /var/lib/domogik/resources already exists
 ==> Copyed file src/domogik/common/datatypes.json
 ==> Directory /var/lib/domogik/resources/sphinx already exists
 ==> Copyed file docs/Makefile
 ==> Copyed file docs/conf-packages.py
 ==> Directory /var/lock/domogik already exists
 ==> Directory /var/log/domogik already exists
 ==> Directory /var/log/xplhub already exists
 ==> Directory /etc/default/ already exists
 ==> Copyed file src/domogik/examples/default/domogik
 ==> Directory /etc/logrotate.d already exists
 ==> Copyed file src/domogik/examples/logrotate/domogik
 ==> Copyed file src/domogik/xpl/hub/examples/logrotate/xplhub
 ==> Directory /etc/init.d/ already exists
 ==> Copyed file src/domogik/examples/init/domogik
 [ Update /etc/default/domogik ]
 [ Configuration files ]
Please notice that Domogik 0.3.x configuration files are no more compliant with Domogik 0.4 :
- backup your Domogik 0.3 configuration files
- say 'n' to the question to recreate them from scratch
Do you want to keep your current config files ? [Y/n]:
y
SYS.PATH=['/opt/dmg/domogik-0.4.2', '/opt/dmg/domogik-mq-1.2/src', '/usr/local/lib/python2.7/dist-packages/pyzmq-15.0.0-py2.7-linux-armv7l.egg', '/usr/local/lib/python2.7/dist-packages/python_daemon-2.0.6-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/simplejson-3.8.1-py2.7-linux-armv7l.egg', '/usr/local/lib/python2.7/dist-packages/lockfile-0.11.0-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/pbr-0.11.0-py2.7.egg', '/usr/lib/pymodules/python2.7', '/opt/dmg/domogik-0.4.2/src/flask-themes2', '/opt/dmg/domogik-0.4.2/src', '/usr/local/lib/python2.7/dist-packages/ephem-3.7.6.0-py2.7-linux-armv7l.egg', '/usr/local/lib/python2.7/dist-packages/tornado-4.3-py2.7-linux-armv7l.egg', '/usr/local/lib/python2.7/dist-packages/backports_abc-0.4-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/certifi-2015.11.20-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/singledispatch-3.4.0.3-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/backports.ssl_match_hostname-3.4.0.2-py2.7.egg', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-linux2', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PIL']
USER=root
 [ Checking the db existance ]
 ==> Checking if the mysql db exists
 [ Database already exists ]
 [ The database already exists, we won't create it ]
 [ Installing or upgrading the db ]
 ==> Creating backup
Do you want to backup your database? [Y/n] n
 ==> Upgrading
INFO  [alembic.migration] Context impl MySQLImpl.
INFO  [alembic.migration] Will assume non-transactional DDL.



 [ Start to test configuration ]
 [ Check this script is started as root ]
 ==> Correctly started with root privileges.
 [ Test imports ]
 ==> Imports are good
 [ Check hostname ]
 ==> Hostname characters are OK
 [ Test global config file ]
 ==> Global config file exists and contains right stuff
 [ Check manager params ]
 ==> Manager params seem good
 [ Check xPL_Hub is in path ]
 ==> xPL_Hub can't be found, please double check CUSTOM_PATH is correctly defined if you are in development mode. In install mode, check your architecture is supported or check src/domogik/xpl/tools/COMPILE.txt, then restart test_config.py

**Comment by overload08** [comment]
root@pi:/etc/domogik# cat domogik-mq.cfg
[mq]
is_master = True
log_dir_path = /var/log/domogik/
pid_dir_path = /var/run/domogik/
log_level = debug
ip = 172.20.0.10
req_rep_port = 40410
pub_port = 40411
sub_port = 40412


root@pi:/etc/domogik# cat domogik-mq.cfg
[mq]
is_master = True
log_dir_path = /var/log/domogik/
pid_dir_path = /var/run/domogik/
log_level = debug
ip = 172.20.0.10
req_rep_port = 40410
pub_port = 40411
sub_port = 40412

root@pi:/etc/domogik# cat domogik.cfg
[domogik]
libraries_path = /var/lib/domogik/
log_dir_path = /var/log/domogik/
pid_dir_path = /var/run/domogik/
log_level = debug
bind_interface = eth0
broadcast = 255.255.255.255

[database]
type = mysql
user = domogik
password = domopass
port = 3306
name = domogik
host = 127.0.0.1
prefix = core

[rest]
interfaces = eth0
port = 40405
use_ssl = False
ssl_certificate =
ssl_key =
clean_json = False

[admin]
interfaces = eth0
port = 40406
use_ssl = False
ssl_certificate =
ssl_key =

[butler]
name = Aria
lang = fr_FR
sex = female

[backup]
folder = /var/lib/domogik/backup/


root@pi:/etc/domogik# cat xplhub.cfg
[hub]
interfaces = eth0
log_dir_path = /var/log/xplhub/
log_level = error
log_bandwidth = False
log_invalid_data = True

**Comment by fritz-smh** [comment]
Which OS/kind of cpu are you using ?
```
uname -a 
```

**Comment by overload08** [comment]
root@pi:/etc/domogik# uname -a
Linux pi 3.18.0-trunk-rpi2 #1 SMP PREEMPT Debian 3.18.5-1~exp1+rpi19 (2015-08-08) armv7l GNU/Linux

**Comment by fritz-smh** [comment]
By the way, was the python hub working after install ?

**Comment by overload08** [comment]
That's ok for me, I've some logs in /var/log/domogik/xplgw.log

**Comment by fritz-smh** [comment]
I keep the ticket open, I will fix the test_config tool to no more test the old c hub

**Comment by fritz-smh** [comment]
Fixed in develop branch for 0.5

**Comment by fritz-smh** [comment]
Fixed in develop, so closing
