### ISSUE TITLE
Scenario : limit a scenario to a period

### ISSUE THREAD

**Issue by fritz-smh** [domogik/domogik#181]
Add an.option to allow restriction of a scenario execution to a period (from 8:00 to 15:00 for example).

**Comment by tikismoke** [comment]
May I suggest something:
A variable current time.
And use cron block

If current time>blockcron AND current time< blockcron
Do....

Could be used also to decline work week or weekend.



Le 24 novembre 2015 17:37:09 GMT+01:00, Fritz SMH <notifications@github.com> a écrit :
>Add an.option to allow restriction of a scenario execution to a period
>(from 8:00 to 15:00 for example).
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/domogik/domogik/issues/181

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by fritz-smh** [comment]
A block cron can't be used for this.
But we could create a block to check if the hour is in an interval

**Comment by fritz-smh** [comment]
Not sure we should keep this one in 0.5... Maybe 0.6 ?

**Comment by fritz-smh** [comment]
Such blocks are now available.
Closing the ticket
