### ISSUE TITLE
Virtual device/sensor suggestion

### ISSUE THREAD

**Issue by vdomos** [domogik/domogik#184]
Concerning the virtual device discussed in this issue:  https://github.com/domogik/domogik/issues/142

And as in other home automation software like Domoticz or jeedom, 
adding the possibility to update the virtual sensors with REST query such as this:

      http://IP:40405/sensor/id/217/value/10.5

No need a xpl layer for external hosts or box, just a simple http request.

This will allow an easier transition from home automation box to Domogik

**Comment by fritz-smh** [comment]
To be sure to understand. The url would help to set a device sensor value just by calling the url ?
And it could be used by any external thing ?

**Comment by vdomos** [comment]
Yes, the url call set the value of the "virtual" sensor in Domogik.

For example, 
-  if a plugin in Domoticz that don't exist in Domogik, Domoticz can set the sensors of this plugin in Domogik  (no need to use the Domoticz GUI)
- A small device like wifi ESP8266 sensor can call a Domogik URL to update the "virtual" sensor.

This can be a temporary or not solution to integrate sensors in Domogik without plugin.

**Comment by fritz-smh** [comment]
it is a good idea, now we need to find the best way to do this

**Comment by tikismoke** [comment]
Not sure but this already possible:
http://apidoc.domogik.org/rest/#api-Sensor-putSensor

That's what i'm using (with 0.3) to interact with dostant mirror and Pir on a dedicated pi.

**Comment by Cereal2nd** [comment]
I have been looking at it, and I think we can do this pretty simple.

Will put it on my to-do list for 0.5

**Comment by vdomos** [comment]
Thanks, cereal2nd

tikismoke, I thought the same thing, but the Post parameters are only for sensor configuration, I think.

**Comment by Cereal2nd** [comment]
yes indeed

i'll add something like that once i finish the mq only plugins

**Comment by vdomos** [comment]
About this idea of virtual device, 
I found a little solution with a small plugin called vdevice.

It provided 3 device type as the script plugin:
* vdevice.info_binary
* vdevice.info_number
* vdevice.info_string

Each device provided a command and a sensor. 
The command called will update the sensor, allowing the sensor to be update from a REST URL.

Like this in shell:
For update the sensor:

    $ curl -s 'http://hermes:40406/rest/cmd/id/36?value=260'

The read of the sensor return the same value:

    $ curl -s 'http://hermes:40406/rest/sensorhistory/id/217/last/1'; echo
    [{"timestamp": 1452101182.0, "value_str": "260", "value_num": 260.0}]


Early documentation can be read here: http://domogik-plugin-vdevice.readthedocs.org/en/latest/vdevice.html

**Comment by fritz-smh** [comment]
Topic in progress on @vdomos side.
I close the ticket as there is no more relationship with domogik 0.5 core
