### ISSUE TITLE
Select List size in device configuration

### ISSUE THREAD

**Issue by vdomos** [domogik/domogik#189]
Hello,

A little thing:

Possible to reduce the size of the selection lists ("choices" in device type configuration)., really very, very large.
Same large size in Iceweasel / Chromium / Android Tablet

it is also visible in notify plugin.

thanks,

![domogik_device_selectlist](https://cloud.githubusercontent.com/assets/1257481/11610778/d8b90aa2-9bac-11e5-894b-fb24f48147af.png)

**Comment by fritz-smh** [comment]
Already fixed in develop branch (0.5)

Closing.
