### ISSUE TITLE
Add the posibility to upgrade devices if the plugin json changes

### ISSUE THREAD

**Issue by Cereal2nd** [domogik/domogik#190]
steps to follow
1- packagevalidator to give a list of bad things per plugin/device
2- disable all devices
3- admin page to upgrade (similar to device creation process)
4- after 3 re-enable the device

when a device is disabled no stats will be stored or anything

**Comment by fleroypro** [comment]
How does this work ?

**Comment by fritz-smh** [comment]
With the good account...

Hos does this work ?

**Comment by Cereal2nd** [comment]
it was a duplicate of https://github.com/domogik/domogik/issues/72

thats why i closed it
