### ISSUE TITLE
Select List display is not correct with global parameter

### ISSUE THREAD

**Issue by vdomos** [domogik/domogik#197]
A last little bug for the road :)

With domogik develop version, the display in admin interface of a choice Select List is not correct for Global parameter.
The name of choice is display in the list instead of the text of the choice.

With an example it will be easier:

Configuration exemple parameters **choice** type with **xpl=false** for the first and **xpl=true** for the second:

            "parameters": [
               {
                  "key": "name",
                  "xpl": false,
                  "description": "Sensor Attribute",
                  "type": "choice",
                  "choices" : {
                     "choix1" : "le choix 1",
                     "choix2" : "le choix 2",
                     "choix3" : "le choix 3"
                        }
               },
               {
                  "key": "name2",
                  "xpl": true,
                  "description": "Sensor Attribute2",
                  "type": "choice",
                  "choices" : {
                     "choix4" : "le choix 4",
                     "choix5" : "le choix 5",
                     "choix6" : "le choix 6"
                        }
               },

And the result:
With **xpl=true** mode display is correct.

![domogik_choice_parameter_1](https://cloud.githubusercontent.com/assets/1257481/11993563/b3135516-aa32-11e5-80d8-d91a458f4124.png)

![domogik_choice_parameter_2](https://cloud.githubusercontent.com/assets/1257481/11993565/b897abc2-aa32-11e5-9e5d-6efcd9b9385b.png)

Thanks and Merry Christmas

**Comment by fritz-smh** [comment]
To allow a quick fix of this, can you list me a plugin (or more) with this use case ?

**Comment by vdomos** [comment]
you can test with the onewired plugin
https://github.com/vdomos/domogik-plugin-onewired
 with a "onewire.pio_input" device type:

"choices" : {
							"sensed" : "Input (DS2405 sensed)",
							"sensed.A" : "Input A (DS2406/7)",
							"sensed.B" : "Input B (DS2406/7)",
							"sensed.0" : "Input 0 (DS2408)",
							"sensed.1" : "Input 1 (DS2408)",
							"sensed.2" : "Input 2 (DS2408)",
							"sensed.3" : "Input 3 (DS2408)",
							"sensed.4" : "Input 4 (DS2408)",
							"sensed.5" : "Input 5 (DS2408)",
							"sensed.6" : "Input 6 (DS2408)",
							"sensed.7" : "Input 7 (DS2408)"
                         }

**Comment by fritz-smh** [comment]
Thanks, I will check this week end
