### ISSUE TITLE
scenario call url issue

### ISSUE THREAD

**Issue by tikismoke** [domogik/domogik#198]
Got this error in log:

>2015-12-28 10:00:28,171 domogik-scenario WARNING Trigger <bound method ScenarioInstance.generic_trigger of <domogik.scenario.scenario.ScenarioInstance instance at 0x7f43681a0f80>> called by parameter <domogik.scenario.parameters.cron.CronParameter instance at 0x7f435c0278c0>
>2015-12-28 10:00:28,172 domogik-scenario DEBUG Evaluate <domogik.scenario.parameters.cron.CronParameter instance at 0x7f435c0278c0> : True
>2015-12-28 10:00:28,172 domogik-scenario DEBUG Evaluate <domogik.scenario.parameters.cron.CronParameter instance at 0x7f435c0278c0> : True
>2015-12-28 10:00:28,172 domogik-scenario DEBUG _parsed condition is : self._mapping['test' ['685addef-ffec-41a1-be08-957c0d37363e'].evaluate(), eval is True
>2015-12-28 10:00:28,172 domogik-scenario INFO Condition horloge karotz evaluated to True
> 2015-12-28 10:00:28,172 domogik-scenario INFO Calling url : http://karotz/cgi-bin/apps/clock
>2015-12-28 10:00:28,172 domogik-scenario WARNING Error when calling url from action.CallUrlAction : Traceback (most recent call last):
>  File "/home/domogik/src/domogik/scenario/actions/call_url.py", line 62, in do_action  key, value = arg.split("=")
>ValueError: need more than 1 value to unpack

This is a simple scenario like this:
http://pasteboard.co/mNY1MSy.png

In a console:
>root@domogik0:~# sudo -u domogik curl http://karotz/cgi-bin/apps/clock
>sudo: unable to resolve host domogik0
>2015 Dec 28 10:38:38 domogik0     root : unable to resolve host domogik0
>{"return":"0","hour":"10"}

**Comment by tikismoke** [comment]
>2015-12-28 12:00:12,734 domogik-scenario INFO Condition horloge karotz evaluated to True
>2015-12-28 12:00:12,734 domogik-scenario INFO Calling url : http://192.168.0.62/cgi-bin/apps/clock/
>2015-12-28 12:00:12,734 domogik-scenario DEBUG Calling url (transformed) : http://192.168.0.62/cgi-bin/apps/clock/?
>2015-12-28 12:00:18,200 domogik-scenario INFO Call url OK

Not sure it is 100% ok as it transfrom the url adding a "?"

**Comment by Cereal2nd** [comment]
its ok, but it would be nicer if its removed (so only added if args)

**Comment by tikismoke** [comment]
An android i did this:
>//remove last &
>if (Url2send.endsWith("&")) {
>Url2send = Url2send.substring(0, Url2send.length() - 1);
>}
