### ISSUE TITLE
Timestamp of sensor history advance one hour

### ISSUE THREAD

**Issue by vdomos** [domogik/domogik#200]
Hello,

As we have found with the callerid plugin, call time problem ahead of one hour is not related to the plugin but seems more generic problem with REST:

The timestamp of the history value have all one hour ahead.
Here a example to show:

    $ date
    vendredi 25 décembre 2015, 20:59:09 (UTC+0100)
    
    $ curl -s  http://hermes:40406/rest/sensorhistory/id/195/last/1 | python -m json.tool
    [
        {
            "timestamp": 1451077119.0,                    	***
            "value_num": 9579570.0,
            "value_str": "9579570"
        }
    ]
    
    $ date -d @1451077119.0 '+%Y-%m-%d %H:%M:%S'     		***
    2015-12-25 21:58:39										# one hour ahead for value timestamp

But in database, i's ok:

    id      sensor_id  date                    value_num  value_str  original_value_num
    129888  195        2015-12-25 20:58:39     9579570    9579570    9579570

**Comment by Cereal2nd** [comment]
is your timezone setup correctly?

**Comment by vdomos** [comment]
Yes I think, see the  above command "date".

**Comment by vdomos** [comment]
Some additional findings:

Difference beetween "sensor" REST request:

the "last_received" is at the good timestamp.

    $ curl -s "http://hermes:40406/rest/sensor/132"| python -m json.tool
    {
        "conversion": "",
        "data_type": "DT_Temp",
        "device_id": 51,
        "formula": null,
        "history_duplicate": false,
        "history_expire": 0,
        "history_max": 0,
        "history_round": 0.0,
        "history_store": true,
        "id": 132,
        "incremental": false,
        "last_received": 1451508470,			***
        "last_value": "23",
        "name": "Temperature",
        "reference": "sensor_temperature",
        "timeout": 600,
        "value_max": 26.5,
        "value_min": null
    }


And at the same time the "sensorhistory" REST request: 

The timestamp have 3600s more => 1451508470 + 3600 = 1451512070

    $ curl -s "http://hermes:40406/rest/sensorhistory/id/132/last/1"| python -m json.tool
    [
        {
            "timestamp": 1451512070.0,			***
            "value_num": 23.0,
            "value_str": "23"
        }
    ]

**Comment by tikismoke** [comment]
The problem is also available in domodroid and domoweb. As it make rest request.

Maybe a problem with winter/summer time ?

**Comment by tikismoke** [comment]
Problems comes from database.py line 975 & line 993.
` "timestamp" : (a_value.date - datetime.datetime(1970, 1, 1)).total_seconds()})`

**Comment by Cereal2nd** [comment]
hmm, looking at the code
this should just be a_value.date and nothing else

can you try if that solves it?

**Comment by tikismoke** [comment]
No in this case it returns not a timestamp but the complete date

Le 3 février 2016 08:36:09 GMT+01:00, Maikel Punie <notifications@github.com> a écrit :
>hmm, looking at the code
>this should just be a_value.date and nothing else
>
>can you try if that solves it?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/domogik/domogik/issues/200#issuecomment-179067383

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by tikismoke** [comment]
Perhaps we should re-add a new value 'date' in the json returned as it was in 0.3? It will need to modify client (web/droid).

**Comment by fritz-smh** [comment]
no

timestamp is THE way to store a datetime

the issue is related to timezone I think

**Comment by tikismoke** [comment]
Solution should be:
 "timestamp" : (a_value.date - datetime.datetime(1970, 1, 1)).total_seconds() - time_zone_utc_difference_in_seconds})

but didn't find hos to get this information :(

**Comment by Cereal2nd** [comment]
ok,

i'll look into it

**Comment by vdomos** [comment]
The issue is back:
I have again one hour between **rest/sensor** and **rest/sensorhistory**


    $ date
    mardi 29 mars 2016, 16:22:59 (UTC+0200)
    
    $ wget -qO- "http://vesta:40406/rest/sensor/141" | python -m json.tool | grep last_received
        "last_received": 1459261387,
     
    $ date -d @1459261387
    mardi 29 mars 2016, 16:23:07 (UTC+0200)
    
    
    $ wget -qO- "http://vesta:40406/rest/sensorhistory/id/111/last/1" ; echo
    [{"timestamp": 1459264995, "value_str": "20.7", "value_num": 20.7}]
     
    $ date -d @1459264995
    mardi 29 mars 2016, 17:23:15 (UTC+0200)

Problem with summer time change ?

**Comment by tikismoke** [comment]
Same here, in callerdid time, current call in list is in one hour ;)

**Comment by Cereal2nd** [comment]
I don't see this at all, so I'm 99% sure this is a config mistake ....

**Comment by tikismoke** [comment]
What config to look at? It comes back last week whith time change for summer.

**Comment by vdomos** [comment]
And why **rest/sensor** is ok  while **rest/sensorhistory** advanced one hour ?
