### ISSUE TITLE
Overflow text

### ISSUE THREAD

**Issue by ghost** [domogik/domogik#203]
Menu Scenario, button Help : 

Here : 

![overflow-text](https://cloud.githubusercontent.com/assets/13867163/12050561/6a25079a-aef7-11e5-8d4d-5cc608984d2d.png)

and here : 

![overflow-text-2](https://cloud.githubusercontent.com/assets/13867163/12050586/aaa3c504-aef7-11e5-91ba-4625588ad037.png)

and here (little) for string "is ok" : 

![overflow-text-3](https://cloud.githubusercontent.com/assets/13867163/12050608/f382d9fe-aef7-11e5-87e6-49a7ae0eb226.png)

**Comment by fritz-smh** [comment]
I close the ticket as the help box will be  redone from scratch in 0.5

Can you just give your browser name and version ?
