### ISSUE TITLE
Widget does not display the formula or incremental value

### ISSUE THREAD

**Issue by vdomos** [domogik/domogik#207]
I transfer this issue https://github.com/domogik/domoweb/issues/53 on Domogik because the problem is the same on Domoweb and Domodroid.

The MQ send only the **original_value_num** not the **value_num**  with a formula or a incrmental sensor (see last messages of the ticket)

**Comment by fritz-smh** [comment]
I also noticed it. We should send the complete data over mq (timestamp, value num, value str, ....) instead of only the value. But we will need to do it synced with domoweb (all widgets upgrade) and domodroid

**Comment by tikismoke** [comment]
For dmd, as it is sync with lot of different version I can make a simple test on mq receive and display the calculate one if exist or the string one else. Also I can set an option to force string one if user do not want the str value. 
it is need in rest too.

Le 4 janvier 2016 13:03:09 GMT+01:00, Fritz SMH <notifications@github.com> a écrit :
>I also noticed it. We should send the complete data over mq (timestamp,
>value num, value str, ....) instead of only the value. But we will need
>to do it synced with domoweb (all widgets upgrade) and domodroid
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/domogik/domogik/issues/207#issuecomment-168659400

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by tikismoke** [comment]
Don't remember exactly the exact page of rest is used at startup and when mq timeout? Answer later this evening.

**Comment by Cereal2nd** [comment]
i think i can easily solve this by just sending the value that's really stored in the db, so after rounding, formula, conversion and everything. the exact same value as the one stored.
