### ISSUE TITLE
test post install : add a check on hostname - manager failed without message because of hostname.

### ISSUE THREAD

**Issue by tikismoke** [domogik/domogik#212]
Launch with the init.d no error message but manager doesn't start.

launch manager in a cli and:
>sudo -u domogik python /home/domogik/src/domogik/bin/manager.py -f
>is manager
>2016-01-10 11:25:15,736 domogik-manager INFO Looking for launched instances of 'manager'
>2016-01-10 11:25:15,747 domogik-manager INFO No existing process.
>2016-01-10 11:25:15,750 domogik-manager DEBUG watcher fork
>2016-01-10 11:25:15,750 domogik-manager INFO ----------------------------------
>2016-01-10 11:25:15,752 domogik-manager INFO Starting client 'manager' (new manager instance)
>2016-01-10 11:25:15,752 domogik-manager INFO Python version is sys.version_info(major=2, minor=7, micro=3, releaselevel='final', serial=0)
>2016-01-10 11:25:15,759 domogik-manager DEBUG Send client status : starting
>2016-01-10 11:25:15,760 domogik-manager DEBUG Send client status : starting
>2016-01-10 11:25:15,762 domogik-manager DEBUG Write pid file for pid '3905' in file '/var/run/domogik/manager.pid'
>2016-01-10 11:25:15,763 domogik-manager INFO End init of the global client part
>2016-01-10 11:25:15,763 domogik-manager INFO Start of the xPL init
>2016-01-10 11:25:15,763 domogik-manager INFO Configured interface(s) : ['eth0']
>2016-01-10 11:25:15,764 domogik-manager INFO The xpl connection may be done on the below addresses (only one will be used):
>2016-01-10 11:25:15,764 domogik-manager INFO  - 192.168.0.63:0
>2016-01-10 11:25:15,764 domogik-manager INFO Binding to ('192.168.0.63', 0) [BIND]...
>2016-01-10 11:25:15,765 domogik-manager DEBUG xPL plugin manager socket bound to 192.168.0.63, port 40956
>2016-01-10 11:25:15,765 domogik-manager INFO Plugin configure to have the xPL hub as optionnal! The hub won't be searched but a hbeat message will be sent each 5 minutes
>2016-01-10 11:25:15,765 domogik-manager DEBUG send hbeat
>Traceback (most recent call last):
>  File "/home/domogik/src/domogik/bin/manager.py", line 1717, in <module>
>    main()
>  File "/home/domogik/src/domogik/bin/manager.py", line 1714, in main
>    Manager()
>  File "/home/domogik/src/domogik/bin/manager.py", line 143, in __init__
>    XplPlugin.__init__(self, name = 'manager', parser=parser, log_prefix = "", nohub=True)
>  File "/home/domogik/src/domogik/xpl/common/plugin.py", line 78, in __init__
>    self.myxpl = Manager(self.config['bind_interface'], broadcast = broadcast, plugin = self, nohub = >nohub, source = source)
>  File "/home/domogik/src/domogik/xpl/common/xplconnector.py", line 206, in __init__
>    self._SendHeartbeat()
>  File "/home/domogik/src/domogik/xpl/common/xplconnector.py", line 339, in _SendHeartbeat
>    mesg.set_source( self._source )
>  File "/home/domogik/src/domogik/xpl/common/xplmessage.py", line 290, in set_source
>    raise XplMessageError("Invalid source (%s)" % source)
>domogik.common.dmg_exceptions.XplMessageError: Invalid source (domogik-manager.domogik_dev)

The problem is in the hostname **domogik_dev** renaming it to domogikdev solve my problem.

But no log or error message or avertissement when launching th init.d

**Comment by fritz-smh** [comment]
In testconfig for domogik (or domogik-mq ?), add a test to check if hostname does not contains some characters like '_'
