### ISSUE TITLE
scenario handle multiparameters

### ISSUE THREAD

**Issue by tikismoke** [domogik/domogik#214]
#202 Rest handle such multiparameters but the command in scenario only fill the url path of newtifry device.
So the action is not done as plugin wait for all params.

**Comment by Cereal2nd** [comment]
can you get me the screenshot of the blockly for that command?

**Comment by tikismoke** [comment]
Ok in the evening I'll show you.

**Comment by tikismoke** [comment]
![URL only](http://snag.gy/jg2SJ.jpg)

The newtifry need: url, body, image, priority & title to correctly do is request to newitfy system.
In domodroid i create this widget (missing url on image):
[(https://twitter.com/newdomodroid/status/682637461181325312)]
