### ISSUE TITLE
Admin, Display sensors/commands on create device page

### ISSUE THREAD

**Issue by Nico0084** [domogik/domogik#218]
In create device administration page.
To give more user helper display sensor and commands list of the device_type create .
Details of feature components (Dt_type, min, max,....)
Should be interesting.

**Comment by fritz-smh** [comment]
Hi Nico,

You mean in the creation page where the device parameters are requested ?

Fritz

**Comment by Nico0084** [comment]
Yes that page :)

**Comment by fritz-smh** [comment]
ok, but after 0.5 ;)
there is too much to do already in 0.5.
