### ISSUE TITLE
Naming of no xpl plugin log

### ISSUE THREAD

**Issue by vdomos** [domogik/domogik#219]
hello,

Possible to name the log file of the no xpl plugin to remain consistent with the other like that:

    xPL plugin: xplplugin_script.log
    MQ plugin: plugin_script.log  (now is script.log) for it.

thanks,

**Comment by tikismoke** [comment]
As already  discuss with domos it is indeed a nice feature to find plugin log easily.

Le 22 janvier 2016 16:37:33 GMT+01:00, vdomos <notifications@github.com> a écrit :
>hello,
>
>Possible to name the log file of the no xpl plugin to remain consistent
>with the other like that:
>
>    xPL plugin: xplplugin_scriptlog
>    MQ plugin: plugin_scriptlog  (now is scriptlog) for it
>
>thanks,
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/domogik/domogik/issues/219

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by tikismoke** [comment]
Could be solved by editing __init__ of Plugin Class in domogik.common.plugin
Like in xplplugin class they're is a log_prefix variable but it's also used by:
-admin
-butler
-dbmgr
-scenario

**Comment by tikismoke** [comment]
![/var/log/domogik](http://snag.gy/pgYGU.jpg)

**Comment by fritz-smh** [comment]
just missing xplgw nox (this is a core component) ;)

**Comment by tikismoke** [comment]
Yes but it does not implement plugin lib

**Comment by tikismoke** [comment]
Oups it does.....
