### ISSUE TITLE
﻿Scenario: examples for the 0.5 website

### ISSUE THREAD

**Issue by vdomos** [domogik/domogik#228]
Hello,

Here is an example scenario launched with a widget by using a vdevice StartStop "device type" (recently added in the plugin dev release)
- Create a vdevice StartStop         (DT_Start datatype)
- Create a widget command bool on Domoweb ...
- Create a Scenario like this:

![domogik_scenario_widget_3](https://cloud.githubusercontent.com/assets/1257481/12658011/af8ea5ae-c606-11e5-9e38-f8200c12f8f5.jpg)

A clic on the right widget start the scenario:
![domogik_scenario_widget_2](https://cloud.githubusercontent.com/assets/1257481/12658045/e469b3b8-c606-11e5-9ff0-1172bc1a6f53.jpg)

And the widget returns to the "stop" state at the end of the scenario:
![domogik_scenario_widget_1](https://cloud.githubusercontent.com/assets/1257481/12658055/f66bec7a-c606-11e5-8b8b-bfb0d17759a7.jpg)

Example of use: turn off all the lights with a single button.

Useful, no ?

**Comment by fritz-smh** [comment]
Hi,

This is a very good idea.
To be clear, you can do exactly the same thing with a DT_Switch vdevice, but it will be a lot clearer to understand for the end used with a DT_Start vdevice!

Now, I am not sure about the goal of this ticket...
Is there something to do on Domogik side ?

Good job!
++
Fritz

**Comment by vdomos** [comment]
Yes, a DT_Start vdevice is better to the requested use

Nothing to do, 
Just to give an example of use.
It's more easier to explain here  than on IRC

**Comment by fritz-smh** [comment]
ok, let's keep the ticket for doc purpose. I aimed to add some tutorial pages to the website for 0.5 with some scenario examples.

I will rename this ticket for this purpose ;)

**Comment by vdomos** [comment]
Surely for later, but a wiki for users to give their own examples of scenarios, scripts or other would be a interesting idea ?

**Comment by fritz-smh** [comment]
This is one idea I also had in the past. I was more thinking on a dedicated website like the packages repo.
In domogik admin, on a scenario page, we would have a "publish a scenario example" button or something like that. It would post a screenshot of the scenario + the name + the description + some tags.
Then the website would (after a validation) show all the users scenario.

Or a wiki, but a wiki imply administrative work (accounts issue, ...)

But later ;)
