### ISSUE TITLE
sensors : values storage with duplicate = false

### ISSUE THREAD

**Issue by fritz-smh** [domogik/domogik#231]
Currently, when duplicate option is set to false for a sensor, the value is not inserted if the previous one has the same value.
But we also don't update the last value date !

So we can have for some sensors (batteries for example) a last value of several monthes (especially for plugins like rfxcom where battery level can be only 10% or 100%...)

We should improve the way to handle the last value date in case of duplicates

**Comment by Cereal2nd** [comment]
i suggests we implement the todo that in the database.py code (line 934)

when we implement it like that this ticket will be solved.
ok?

**Comment by fritz-smh** [comment]
Are you sure of the line number ?

Could you maybe give the direct link to the github file line (I have a
github access only on my smartphone today, so not easy to look...)

**Comment by Cereal2nd** [comment]
idd bad line number

https://github.com/domogik/domogik/blob/develop/src/domogik/common/database.py#L878

**Comment by fritz-smh** [comment]
this is ok for me

**Comment by fritz-smh** [comment]
I reopen the issue. See my last comment in #237
