### ISSUE TITLE
Integer global parameter does not accept the value zero

### ISSUE THREAD

**Issue by vdomos** [domogik/domogik#232]
Hello,

I can't validate this device creation, nothing is happening when "Create the device" with the value of 'qos' parameter equal to 0.

![domogik_parameter_2](https://cloud.githubusercontent.com/assets/1257481/12966263/e85628b6-d05c-11e5-8825-9b8ed2098acb.jpg)

Same problem when I want to change the parameter configuration:

![domogik_parameter_1](https://cloud.githubusercontent.com/assets/1257481/12966271/fb6112a4-d05c-11e5-837c-b17da9a9ecef.jpg)

Same problem in Script Plugin with interval time value.
I use '-1' to disable script.

**Comment by fritz-smh** [comment]
This is indeed a bug....
