### ISSUE TITLE
On New admin develop, MQ Subscriber crash after lot of publish.

### ISSUE THREAD

**Issue by Nico0084** [domogik/domogik#234]
Perhaps this a domogik-mq issue ?

admin.py - f

> ......  Lot of publish ......

Pushing` MQ message to 1 WS subscribers...
Pushing MQ message to 1 WS subscribers...
ERROR:tornado.general:Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyzmq-14.7.0-py2.7-linux-x86_64.egg/zmq/eventloop/zmqstream.py", line 407, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.3-py2.7-linux-x86_64.egg/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/admdomo/domogik-mq/src/domogikmq/pubsub/subscriber.py", line 125, in _on_message
    jsons = json.loads(msg[1])
IndexError: list index out of range
ERROR:tornado.general:Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyzmq-14.7.0-py2.7-linux-x86_64.egg/zmq/eventloop/zmqstream.py", line 433, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python2.7/dist-packages/pyzmq-14.7.0-py2.7-linux-x86_64.egg/zmq/eventloop/zmqstream.py", line 465, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python2.7/dist-packages/pyzmq-14.7.0-py2.7-linux-x86_64.egg/zmq/eventloop/zmqstream.py", line 407, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.3-py2.7-linux-x86_64.egg/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/admdomo/domogik-mq/src/domogikmq/pubsub/subscriber.py", line 125, in _on_message
    jsons = json.loads(msg[1])
IndexError: list index out of range
ERROR:tornado.application:Exception in callback None
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.3-py2.7-linux-x86_64.egg/tornado/ioloop.py", line 883, in start
    handler_func(fd_obj, events)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.3-py2.7-linux-x86_64.egg/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyzmq-14.7.0-py2.7-linux-x86_64.egg/zmq/eventloop/zmqstream.py", line 433, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python2.7/dist-packages/pyzmq-14.7.0-py2.7-linux-x86_64.egg/zmq/eventloop/zmqstream.py", line 465, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python2.7/dist-packages/pyzmq-14.7.0-py2.7-linux-x86_64.egg/zmq/eventloop/zmqstream.py", line 407, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.3-py2.7-linux-x86_64.egg/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/admdomo/domogik-mq/src/domogikmq/pubsub/subscriber.py", line 125, in _on_message
    jsons = json.loads(msg[1])
IndexError: list index out of range
2016-02-18 10:05:16,204 domogik-admin DEBUG Send client status : alive
2016-02-18 10:05:31,210 domogik-admin DEBUG Send client status : alive

**Comment by Cereal2nd** [comment]
this is an invallid mq message thats received

**Comment by Cereal2nd** [comment]
can you try this again while sub_all running? and see what message caused it?

**Comment by Nico0084** [comment]
Sorry , I don't understand what you mean by "while sub_all running"  !

2016-02-18 10:25 GMT+01:00 Maikel Punie <notifications@github.com>:

**Comment by Cereal2nd** [comment]
run this mq-example
~/domogik/src/domogik$ python examples/mq-python/sub_all.py

then you will see all mq sub messages

**Comment by Nico0084** [comment]
> From ./sub_all.py 


New pub message ozwave.ctrl.command
{u'NetworkID': u'Maison', u'nodeId': 0, u'state': u'Starting', u'command': u'Internal', u'error': u'', u'usermsg': u'The command is starting.'}
New pub message ozwave.ctrl.report
{u'NetworkID': u'Maison', u'Node count': 16, u'Node sleeping': 6, u'type': u'node-state-changed', u'NodeID': 4, u'Node fail': 0, u'usermsg': u'Domogik device linked.', u'data': {u'state': u'DmgDevices', u'NewDeviceTypes': {u'ozwave.battery-level_level__decrease_increase': {u'commands': [u'decrease', u'increase'], u'description': u'Zwave device information, Must be edited', u'parameters': [{u'type': u'string', u'description': u'Zwave network name if refered in controller node or Openzwave Home ID', u'key': u'networkid', u'xpl': False}, {u'description': u'Zwave node id', u'xpl': False, u'max_value': 255, u'min_value': 1, u'key': u'node', u'type': u'integer'}, {u'description': u'Zwave node instance id', u'xpl': False, u'max_value': 255, u'min_value': 1, u'key': u'instance', u'type': u'integer'}, {u'type': u'boolean', u'description': u'Check battery level at zwave device wakeup.', u'key': u'batterycheck', u'xpl': False}], u'sensors': [u'battery-level', u'level'], u'id': u'ozwave.battery-level_level__decrease_increase', u'name': u'Device type name, Must be edited'}}, u'KnownDeviceTypes': {}}}
New pub message ozwave.ctrl.command
{u'NetworkID': u'Maison', u'nodeId': 0, u'state': u'InProgress', u'command': u'Internal', u'error': u'', u'usermsg': u'The controller is communicating with the other device to carry out the command.'}
New pub message ozwave.ctrl.command
{u'NetworkID': u'Maison', u'nodeId': 0, u'state': u'Completed', u'command': u'Internal', u'error': u'', u'usermsg': u'The command has completed successfully.'}
New pub message ozwave.ctrl.report
{u'NetworkID': u'Maison', u'Node count': 16, u'Node sleeping': 6, u'type': u'node-state-changed', u'NodeID': 7, u'Node fail': 0, u'usermsg': u'Domogik device linked.', u'data': {u'state': u'DmgDevices', u'NewDeviceTypes': {u'ozwave.battery-level_energy-k_energy-previous-reading-k_power_power': {u'commands': [], u'description': u'Zwave device information, Must be edited', u'parameters': [{u'type': u'string', u'description': u'Zwave network name if refered in controller node or Openzwave Home ID', u'key': u'networkid', u'xpl': False}, {u'description': u'Zwave node id', u'xpl': False, u'max_value': 255, u'min_value': 1, u'key': u'node', u'type': u'integer'}, {u'description': u'Zwave node instance id', u'xpl': False, u'max_value': 255, u'min_value': 1, u'key': u'instance', u'type': u'integer'}, {u'type': u'boolean', u'description': u'Check battery level at zwave device wakeup.', u'key': u'batterycheck', u'xpl': False}], u'sensors': [u'battery-level', u'energy-k', u'energy-previous-reading-k', u'power', u'power'], u'id': u'ozwave.battery-level_energy-k_energy-previous-reading-k_power_power', u'name': u'Device type name, Must be edited'}, u'ozwave.energy-previous-reading': {u'commands': [], u'description': u'Zwave device information, Must be edited', u'parameters': [{u'type': u'string', u'description': u'Zwave network name if refered in controller node or Openzwave Home ID', u'key': u'networkid', u'xpl': False}, {u'description': u'Zwave node id', u'xpl': False, u'max_value': 255, u'min_value': 1, u'key': u'node', u'type': u'integer'}, {u'description': u'Zwave node instance id', u'xpl': False, u'max_value': 255, u'min_value': 1, u'key': u'instance', u'type': u'integer'}], u'sensors': [u'energy-previous-reading'], u'id': u'ozwave.energy-previous-reading', u'name': u'Device type name, Must be edited'}, u'ozwave.battery-level_energy-k_energy-previous-reading_power_power': {u'commands': [], u'description': u'Zwave device information, Must be edited', u'parameters': [{u'type': u'string', u'description': u'Zwave network name if refered in controller node or Openzwave Home ID', u'key': u'networkid', u'xpl': False}, {u'description': u'Zwave node id', u'xpl': False, u'max_value': 255, u'min_value': 1, u'key': u'node', u'type': u'integer'}, {u'description': u'Zwave node instance id', u'xpl': False, u'max_value': 255, u'min_value': 1, u'key': u'instance', u'type': u'integer'}, {u'type': u'boolean', u'description': u'Check battery level at zwave device wakeup.', u'key': u'batterycheck', u'xpl': False}], u'sensors': [u'battery-level', u'energy-k', u'energy-previous-reading', u'power', u'power'], u'id': u'ozwave.battery-level_energy-k_energy-previous-reading_power_power', u'name': u'Device type name, Must be edited'}, u'ozwave.energy-previous-reading-m': {u'commands': [], u'description': u'Zwave device information, Must be edited', u'parameters': [{u'type': u'string', u'description': u'Zwave network name if refered in controller node or Openzwave Home ID', u'key': u'networkid', u'xpl': False}, {u'description': u'Zwave node id', u'xpl': False, u'max_value': 255, u'min_value': 1, u'key': u'node', u'type': u'integer'}, {u'description': u'Zwave node instance id', u'xpl': False, u'max_value': 255, u'min_value': 1, u'key': u'instance', u'type': u'integer'}], u'sensors': [u'energy-previous-reading-m'], u'id': u'ozwave.energy-previous-reading-m', u'name': u'Device type name, Must be edited'}, u'ozwave.energy-previous-reading-k': {u'commands': [], u'description': u'Zwave device information, Must be edited', u'parameters': [{u'type': u'string', u'description': u'Zwave network name if refered in controller node or Openzwave Home ID', u'key': u'networkid', u'xpl': False}, {u'description': u'Zwave node id', u'xpl': False, u'max_value': 255, u'min_value': 1, u'key': u'node', u'type': u'integer'}, {u'description': u'Zwave node instance id', u'xpl': False, u'max_value': 255, u'min_value': 1, u'key': u'instance', u'type': u'integer'}], u'sensors': [u'energy-previous-reading-k'], u'id': u'ozwave.energy-previous-reading-k', u'name': u'Device type name, Must be edited'}, u'ozwave.battery-level_energy-k_energy-previous-reading-m_power_power': {u'commands': [], u'description': u'Zwave device information, Must be edited', u'parameters': [{u'type': u'string', u'description': u'Zwave network name if refered in controller node or Openzwave Home ID', u'key': u'networkid', u'xpl': False}, {u'description': u'Zwave node id', u'xpl': False, u'max_value': 255, u'min_value': 1, u'key': u'node', u'type': u'integer'}, {u'description': u'Zwave node instance id', u'xpl': False, u'max_value': 255, u'min_value': 1, u'key': u'instance', u'type': u'integer'}, {u'type': u'boolean', u'description': u'Check battery level at zwave device wakeup.', u'key': u'batterycheck', u'xpl': False}], u'sensors': [u'battery-level', u'energy-k', u'energy-previous-reading-m', u'power', u'power'], u'id': u'ozwave.battery-level_energy-k_energy-previous-reading-m_power_power', u'name': u'Device type name, Must be edited'}}, u'KnownDeviceTypes': {}}}
New pub message ozwave.ctrl.command
{u'NetworkID': u'Maison', u'nodeId': 0, u'state': u'Starting', u'command': u'Internal', u'error': u'', u'usermsg': u'The command is starting.'}
New pub message ozwave.ctrl.report
{u'NetworkID': u'Maison', u'Node count': 16, u'Node sleeping': 6, u'type': u'node-state-changed', u'NodeID': 7, u'Node fail': 0, u'usermsg': u'Domogik device linked.', u'data': {u'state': u'DmgDevices', u'DmgDevices': [{u'xpl_stats': {}, u'commands': {}, u'description': u'', u'reference': u'HEM', u'xpl_commands': {}, u'client_version': u'0.5.0', u'client_id': u'plugin-ozwave.vmdomogik0', u'device_type_id': u'ozwave.energy_energy-k_power', u'sensors': {u'energy-k': {u'conversion': u'', u'value_min': None, u'data_type': u'DT_kActiveEnergy', u'reference': u'energy-k', u'incremental': True, u'id': 52, u'last_received': 1455786370, u'timeout': 0, u'formula': None, u'last_value': u'-0.0499999999993', u'value_max': 0.0, u'name': u'Energy'}, u'energy': {u'conversion': u'', u'value_min': None, u'data_type': u'DT_ActiveEnergy', u'reference': u'energy', u'incremental': True, u'id': 51, u'last_received': None, u'timeout': 0, u'formula': None, u'last_value': None, u'value_max': None, u'name': u'Energy'}, u'power': {u'conversion': u'', u'value_min': None, u'data_type': u'DT_Power', u'reference': u'power', u'incremental': False, u'id': 50, u'last_received': 1455786539, u'timeout': 0, u'formula': None, u'last_value': u'5283.33', u'value_max': 5283.33, u'name': u'Power'}}, u'parameters': {u'networkid': {u'value': u'Maison', u'type': u'string', u'id': 51, u'key': u'networkid'}, u'node': {u'value': u'7', u'type': u'integer', u'id': 52, u'key': u'node'}, u'instance': {u'value': u'1', u'type': u'integer', u'id': 53, u'key': u'instance'}}, u'id': 15, u'name': u'TEST HEM'}]}}
New pub message ozwave.ctrl.report
{u'NetworkID': u'Maison', u'Node count': 16, u'Node sleeping': 6, u'type': u'node-state-changed', u'NodeID': 1, u'Node fail': 0, u'usermsg': u'Domogik device linked.', u'data': {u'state': u'DmgDevices', u'NewDeviceTypes': {}, u'KnownDeviceTypes': {}}}
New pub message ozwave.ctrl.report
{u'NetworkID': u'Maison', u'Node count': 16, u'Node sleeping': 6, u'type': u'node-state-changed', u'NodeID': 1, u'Node fail': 0, u'usermsg': u'Domogik device linked.', u'data': {u'state': u'DmgDevices', u'DmgDevices': [{u'xpl_stats': {}, u'commands': {}, u'description': u'Controleur zwave', u'reference': u'Z-Stick 2', u'xpl_commands': {}, u'client_version': u'0.5.0', u'client_id': u'plugin-ozwave.vmdomogik0', u'device_type_id': u'ozwave.primary_controller', u'sensors': {u'ctrl-status': {u'conversion': u'', u'value_min': None, u'data_type': u'DT_String', u'reference': u'ctrl-status', u'incremental': False, u'id': 56, u'last_received': None, u'timeout': 0, u'formula': None, u'last_value': None, u'value_max': None, u'name': u'Controler status'}}, u'parameters': {u'networkid': {u'value': u'Maison', u'type': u'string', u'id': 64, u'key': u'networkid'}, u'driver': {u'value': u'/tmp/ttyS0', u'type': u'string', u'id': 63, u'key': u'driver'}}, u'id': 19, u'name': u'Controleur'}]}}
New pub message ozwave.ctrl.command
{u'NetworkID': u'Maison', u'nodeId': 0, u'state': u'InProgress', u'command': u'Internal', u'error': u'', u'usermsg': u'The controller is communicating with the other device to carry out the command.'}
New pub message ozwave.ctrl.command
{u'NetworkID': u'Maison', u'nodeId': 0, u'state': u'Completed', u'command': u'Internal', u'error': u'', u'usermsg': u'The command has completed successfully.'}
New pub message device.new
{u'device': {u'data': {u'xpl_stats': {}, u'reference': u'', u'xpl': [], u'xpl_commands': {}, u'global': [{u'key': u'networkid', u'value': u'Maison'}, {u'key': u'node', u'value': u'10'}, {u'key': u'instance', u'value': u'3'}], u'device_type': u'ozwave.switch__switch'}, u'id': u'device_typeozwave.switch__switchglobalkeynetworkidvalueMaisonkeynodevalue10keyinstancevalue3referencexplxpl_commandsxpl_stats'}, u'host': u'vmdomogik0', u'type': u'plugin', u'name': u'ozwave', u'client_id': u'plugin-ozwave.vmdomogik0'}
New pub message ozwave.ctrl.command
{u'NetworkID': u'Maison', u'nodeId': 0, u'state': u'Starting', u'command': u'Internal', u'error': u'', u'usermsg': u'The command is starting.'}
New pub message device.new
{u'device': {u'data': {u'xpl_stats': {}, u'reference': u'', u'xpl': [], u'xpl_commands': {}, u'global': [{u'key': u'networkid', u'value': u'Maison'}, {u'key': u'node', u'value': u'10'}, {u'key': u'instance', u'value': u'2'}], u'device_type': u'ozwave.switch__switch'}, u'id': u'device_typeozwave.switch__switchglobalkeynetworkidvalueMaisonkeynodevalue10keyinstancevalue2referencexplxpl_commandsxpl_stats'}, u'host': u'vmdomogik0', u'type': u'plugin', u'name': u'ozwave', u'client_id': u'plugin-ozwave.vmdomogik0'}
New pub message device.new
{u'device': {u'data': {u'xpl_stats': {}, u'reference': u'', u'xpl': [], u'xpl_commands': {}, u'global': [{u'key': u'networkid', u'value': u'Maison'}, {u'key': u'node', u'value': u'10'}, {u'key': u'instance', u'value': u'1'}], u'device_type': u'ozwave.switch__switch'}, u'id': u'device_typeozwave.switch__switchglobalkeynetworkidvalueMaisonkeynodevalue10keyinstancevalue1referencexplxpl_commandsxpl_stats'}, u'host': u'vmdomogik0', u'type': u'plugin', u'name': u'ozwave', u'client_id': u'plugin-ozwave.vmdomogik0'}
New pub message ozwave.ctrl.report
{u'NetworkID': u'Maison', u'Node count': 16, u'Node sleeping': 6, u'type': u'node-state-changed', u'NodeID': 10, u'Node fail': 0, u'usermsg': u'Domogik device linked.', u'data': {u'state': u'DmgDevices', u'NewDeviceTypes': {}, u'KnownDeviceTypes': {u'Maison.10.3': [u'ozwave.switch__switch'], u'Maison.10.2': [u'ozwave.switch__switch'], u'Maison.10.1': [u'ozwave.switch__switch']}}}
New pub message ozwave.ctrl.report
{u'NetworkID': u'Maison', u'Node count': 16, u'Node sleeping': 6, u'type': u'node-state-changed', u'NodeID': 10, u'Node fail': 0, u'usermsg': u'Domogik device linked.', u'data': {u'state': u'DmgDevices', u'DmgDevices': [{u'xpl_stats': {}, u'commands': {u'switch': {u'return_confirmation': True, u'id': 23, u'parameters': [{u'conversion': u'', u'data_type': u'DT_Switch', u'key': u'switch'}], u'name': u'Switch On-Off'}}, u'description': u'FGS211', u'reference': u'', u'xpl_commands': {}, u'client_version': u'0.5.0', u'client_id': u'plugin-ozwave.vmdomogik0', u'device_type_id': u'ozwave.switch__switch', u'sensors': {u'switch': {u'conversion': u'from_switch_to_DT_Switch', u'value_min': None, u'data_type': u'DT_Switch', u'reference': u'switch', u'incremental': False, u'id': 53, u'last_received': 1455786411, u'timeout': 0, u'formula': None, u'last_value': u'0', u'value_max': 1.0, u'name': u'Switch'}}, u'parameters': {u'networkid': {u'value': u'Maison', u'type': u'string', u'id': 54, u'key': u'networkid'}, u'node': {u'value': u'10', u'type': u'integer', u'id': 55, u'key': u'node'}, u'instance': {u'value': u'1', u'type': u'integer', u'id': 56, u'key': u'instance'}}, u'id': 16, u'name': u'Test simple switch'}]}}
New pub message ozwave.ctrl.command
{u'NetworkID': u'Maison', u'nodeId': 0, u'state': u'InProgress', u'command': u'Internal', u'error': u'', u'usermsg': u'The controller is communicating with the other device to carry out the command.'}
New pub message device.new
{u'device': {u'data': {u'xpl_stats': {}, u'reference': u'', u'xpl': [], u'xpl_commands': {}, u'global': [{u'key': u'networkid', u'value': u'Maison'}, {u'key': u'node', u'value': u'13'}, {u'key': u'instance', u'value': u'1'}], u'device_type': u'ozwave.switch__switch'}, u'id': u'device_typeozwave.switch__switchglobalkeynetworkidvalueMaisonkeynodevalue13keyinstancevalue1referencexplxpl_commandsxpl_stats'}, u'host': u'vmdomogik0', u'type': u'plugin', u'name': u'ozwave', u'client_id': u'plugin-ozwave.vmdomogik0'}
New pub message ozwave.ctrl.report
{u'NetworkID': u'Maison', u'Node count': 16, u'Node sleeping': 6, u'type': u'node-state-changed', u'NodeID': 13, u'Node fail': 0, u'usermsg': u'Domogik device linked.', u'data': {u'state': u'DmgDevices', u'NewDeviceTypes': {}, u'KnownDeviceTypes': {u'Maison.13.1': [u'ozwave.switch__switch']}}}
New pub message ozwave.ctrl.command
{u'NetworkID': u'Maison', u'nodeId': 0, u'state': u'Completed', u'command': u'Internal', u'error': u'', u'usermsg': u'The command has completed successfully.'}
New pub message ozwave.ctrl.command
{u'NetworkID': u'Maison', u'nodeId': 0, u'state': u'Starting', u'command': u'Internal', u'error': u'', u'usermsg': u'The command is starting.'}
New pub message ozwave.ctrl.command
{u'NetworkID': u'Maison', u'nodeId': 0, u'state': u'InProgress', u'command': u'Internal', u'error': u'', u'usermsg': u'The controller is communicating with the other device to carry out the command.'}
New pub message ozwave.ctrl.command
{u'NetworkID': u'Maison', u'nodeId': 0, u'state': u'Completed', u'command': u'Internal', u'error': u'', u'usermsg': u'The command has completed successfully.'}
ERROR:tornado.general:Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyzmq-14.7.0-py2.7-linux-x86_64.egg/zmq/eventloop/zmqstream.py", line 407, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.3-py2.7-linux-x86_64.egg/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/admdomo/domogik-mq/src/domogikmq/pubsub/subscriber.py", line 125, in _on_message
    jsons = json.loads(msg[1])
IndexError: list index out of range
ERROR:tornado.general:Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyzmq-14.7.0-py2.7-linux-x86_64.egg/zmq/eventloop/zmqstream.py", line 433, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python2.7/dist-packages/pyzmq-14.7.0-py2.7-linux-x86_64.egg/zmq/eventloop/zmqstream.py", line 465, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python2.7/dist-packages/pyzmq-14.7.0-py2.7-linux-x86_64.egg/zmq/eventloop/zmqstream.py", line 407, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.3-py2.7-linux-x86_64.egg/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/admdomo/domogik-mq/src/domogikmq/pubsub/subscriber.py", line 125, in _on_message
    jsons = json.loads(msg[1])
IndexError: list index out of range
ERROR:tornado.application:Exception in callback None
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.3-py2.7-linux-x86_64.egg/tornado/ioloop.py", line 883, in start
    handler_func(fd_obj, events)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.3-py2.7-linux-x86_64.egg/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyzmq-14.7.0-py2.7-linux-x86_64.egg/zmq/eventloop/zmqstream.py", line 433, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python2.7/dist-packages/pyzmq-14.7.0-py2.7-linux-x86_64.egg/zmq/eventloop/zmqstream.py", line 465, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python2.7/dist-packages/pyzmq-14.7.0-py2.7-linux-x86_64.egg/zmq/eventloop/zmqstream.py", line 407, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.3-py2.7-linux-x86_64.egg/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/admdomo/domogik-mq/src/domogikmq/pubsub/subscriber.py", line 125, in _on_message
    jsons = json.loads(msg[1])
IndexError: list index out of range

**Comment by Cereal2nd** [comment]
can you reproduce this easely?

because this bug is in domogik-ma, has nothing todo with admin.
It can only occure when a bad message iss end over the mq
