### ISSUE TITLE
Scenario delete device no more available

### ISSUE THREAD

**Issue by tikismoke** [domogik/domogik#235]
Related to #158 solution,
I think they're is a problem beetween sensor id and command id.

I can't delete a device, domogik tells it is used in a scenario, but it is really not.
The command id (5) is in at least scenario, but this device (i want to delete) contains sensor id (5) but no command id (5).

**Comment by Cereal2nd** [comment]
looking at the code i can not understand where this would be coming from ...

`        llist = []
        for sen in self.get_sensor_by_device_id(d_id):
            llist.append(Scenario.json.like(u'%sensor.SensorTest.{0}%'.format(sen.id)))
        for cmd in self.get_command_by_device_id(d_id):
            llist.append(Scenario.json.like(u'%command.CommandAction.{0}%'.format(cmd.id)))
        scens = self.__session.query(Scenario).filter( or_(*llist) ).count()
        if scens > 0:
            self.__raise_dbhelper_exception("Can not delete device with id {0}, its sensors or commands are used in a scenario".format(d_id))
        del llist
        del scens`

**Comment by tikismoke** [comment]
Found:

Maybe because of like ;) not equal......
This device as a senserid 77

and i got a scenario with: "type":"sensor.SensorTest.177" So  i think it match

**Comment by tikismoke** [comment]
Ok it comes from comands no sensor.

Commands from this device have id:

```
	id 	device_id 	name 	reference 	return_confirmation
	5 	8 	Power On-Off 	set_power 	1
	6 	8 	Temperature setpoint 	set_setpoint 	1
	7 	8 	Select Mode 	set_mode 	1
	8 	8 	Vertical swing On-Off 	set_vertical_swing 	1
	9 	8 	Horizontal swing On-Off 	set_horizontal_swing 	1
	10 	8 	Select fan speed 	set_speedfan 	1
	11 	8 	Powerfull On-Off 	set_powerfull 	1
	12 	8 	Silent On-off 	set_silent 	1
	13 	8 	Home leave On-Off 	set_home_leave 	1
	14 	8 	Sensor On-Off 	set_sensor 	1
	15 	8 	Start time 	set_start_time 	1
	16 	8 	Stop time 	set_stop_time 	1
	134 	158 	Switch On or Off 	set_level_bin 	1
```

And i got lots of scenario with:
`"type":"command.CommandAction.73"`

It is the command for the nabaztag tts :)

**Comment by tikismoke** [comment]
Changing those 2 lines lines:
`        llist.append(Scenario.json.like(u'%sensor.SensorTest.{0}%'.format(sen.id)))`

&
`         llist.append(Scenario.json.like(u'%command.CommandAction.{0}%'.format(cmd.id)))`

Adding the " character to matches: command.CommandAction.73"

**Comment by Cereal2nd** [comment]
indeed, do you create a pull request? or shall i do this

**Comment by tikismoke** [comment]
You'll have to.... My attempt ti fix it didn't wirk at all :(
