### ISSUE TITLE
Scenario test

### ISSUE THREAD

**Issue by tikismoke** [domogik/domogik#236]
Add a way to test a scenario (by doing action immediatly) could be usefull to test and validate a big scenario.

(Can be done for now by removing sensor and do a true or current time test)

**Comment by Cereal2nd** [comment]
hmm, this can only be done once the scenario is saved.
so i could add a button on the scenario overview page to trigger the actions

**Comment by fritz-smh** [comment]
This is indeed a good idea :)

**Comment by Cereal2nd** [comment]
so we implement this after saving of the scenario? thats fine?

**Comment by fritz-smh** [comment]
I just did some user tests on my smartphone.

Here what we have now :
1. When we click on the 'save' button we come back to the scenarios list.
2. When we look to a scenario, we have no visual way to know if the
scenario have been changed or not in blockly.

What I think is that we could indeed add a "test actions" button on the
scenario edit page. But this one should be activated ONLY if nothing have
been changed in the json.

So basically :

* on page load : put the current json in a javascript variable or in a
dedicated div to keep the "original" json.
* keep the current json variable/div which is dynamically updated by
blockly engine (if I remember correctly, it is stored in a div.
* add a javascript trigger on the current json which is called each time
the current json is updated.
* in the trigger, if the current json is different of the original json,
deactivate the test button

Another question comes about the save button.
If the user 'saves' to be able to test the scenario, he will come back to
the scenarios list. Maybe we should have 2 buttons :
* save
* save and quit
?

**Comment by Cereal2nd** [comment]
i like the idea
i'll implement the save / save and quit first
then we will add the needed js

**Comment by Cereal2nd** [comment]
won't be as easy as this, if the json changes the id field (inserted by
blockly) also changes .... so we can not just compare the json

**Comment by fritz-smh** [comment]
When I say "compare the json", I mean compare the whole json string, not
all subparts of the json.
If anything change in the json even the WHEN clause, we deactivate the test
button.

(or I missed something in your question ?)
