### ISSUE TITLE
order scenario

### ISSUE THREAD

**Issue by tikismoke** [domogik/domogik#240]
Just a small request to order scenario in scenario page.

By ID or name or anything else.

For now it's always different every time I reload the page.

**Comment by fritz-smh** [comment]
As discussed, for me it was already done. I will check

**Comment by fritz-smh** [comment]
You said on irc :  
21:15 <tikismoke> Voilà l'ordre actuelle:
21:15 <tikismoke>  Appel entrant
21:15 <tikismoke> Retour internet
21:15 <tikismoke> Reveil lapins WE
21:15 <tikismoke> Reveil lapins semaine
21:15 <tikismoke> Sommeil lapins WE
21:15 <tikismoke> Sommeil lapins semaine
21:15 <tikismoke> Temperature froide noelyne
21:15 <tikismoke> arrive Tobias
21:15 <tikismoke> arrive nono
21:15 <tikismoke> depart nono
21:15 <tikismoke> depart tobias
21:15 <tikismoke> horloge karotz
21:15 <tikismoke> lumiere noelyne nuit
21:15 <tikismoke> plus arduino entree
21:15 <tikismoke> plus internet
21:16 <tikismoke> poubelle jeudi
21:16 <tikismoke> retour arduino entree 


This is ordered !
A...=>...Z,a...=>...z

**Comment by tikismoke** [comment]
Crap.... Could eit be order nob sensitive case
