### ISSUE TITLE
﻿Scenario: New state is not saved

### ISSUE THREAD

**Issue by axboct** [domogik/domogik#241]
between domogik/develop caf2efb and domogik/develop 0cda574 broken scenario editing.

**Comment by Cereal2nd** [comment]
can you get me a bit more info?
1- did you rerun the install script?
2- can you get me the logs?

**Comment by axboct** [comment]
Of course instal rerun.

log below contains:
create scenario->save->edit by add pause and new command->save 
https://gist.github.com/axboct/58ef4bcbdeca544fe394

**Comment by Cereal2nd** [comment]
so its the new json thats not updated?
