### ISSUE TITLE
scenario : add something on the scenarios list to show the deactivated scenarios

### ISSUE THREAD

**Issue by fritz-smh** [domogik/domogik#243]
It would be usefull to see which scenarios are disabled in the list.

**Comment by tikismoke** [comment]
If I may abuse....
A simple check box when on list.
And a sort of listener on checked to enable/disable it from list.

**Comment by Cereal2nd** [comment]
- [ ] There is a bug in enabling a disabled scenario, the json is wrongly stored somewhere
