### ISSUE TITLE
Database : sensor history : increase last_value length

### ISSUE THREAD

**Issue by fritz-smh** [domogik/domogik#257]
Currently, the last_value field is a unicode(32). It is quite shorten for some status usages.
I think we should increase it a "lot", the question is how long is a "lot" ?

I discovered this issue by using a personnal home script that sends me some long string data (length of 35).

It makes me think that for later use (cameras usages for example as I explained in one email) that would need longer data than 32.

Maybe 128 ?

**Comment by fritz-smh** [comment]
Why closing it ?

**Comment by Cereal2nd** [comment]
its done :)

look at the commit logs

**Comment by Cereal2nd** [comment]
https://github.com/domogik/domogik/commit/561feae49acf58ec0b95f010b003bc4be05e62a1

**Comment by fritz-smh** [comment]
Ah ok,sorry, I only see the emails in worktime ;)

Thanks
