### ISSUE TITLE
Scenario order the data_types by there parent

### ISSUE THREAD

**Issue by Cereal2nd** [domogik/domogik#259]
currently in the scenario edit window the dat_types are all in the same list

we should order them by there parent to make searching simpler

**Comment by fritz-smh** [comment]
Maybe grouping them also by parent ?
Numbers
- Temperature
- Humidity
- ...
Boolean
- Switch
- OpenClose
- ...
...

?

**Comment by Cereal2nd** [comment]
yeah thats what i mean :)
