### ISSUE TITLE
Device configuration : unable to set a boolean device parameter to False !

### ISSUE THREAD

**Issue by fritz-smh** [domogik/domogik#260]
The device can't be created until the checkbox is checked to True...

**Comment by fritz-smh** [comment]
and by the way, the value is 'y', don't remember it this is normal or not...

**Comment by vdomos** [comment]
I still have this problem with a update Develop Domogik.

info.json 
device parameters:

            "parameters": [
                {
                    "description": "Screen title", 
                    "key": "title", 
                    "xpl": false,
                    "default": "", 
                    "type": "string"
                },      
                {
                    "description": "Line1 format", 
                    "key": "line1", 
                    "xpl": false,
                    "default": "", 
                    "type": "string"
                },      
                {
                    "description": "Backlight", 
                    "key": "backlight", 
                    "xpl": false,
                    "default": true,
                    "type": "boolean"
                },      
                {
                    "description": "Priority", 
                    "key": "priority", 
                    "xpl": false,
                    "default": false,
                    "type": "boolean"
                },      
                {
                    "description": "Screen duration", 
                    "key": "duration", 
                    "xpl": false,
                    "default": "5",
                    "type": "integer"
                }    
            ]

Parameter "**priority**" must be check otherwise the creation of the device is not validate and stay on this page.


![domogik_plugin_lcdproc_parameters_1](https://cloud.githubusercontent.com/assets/1257481/14227782/81a59fda-f905-11e5-8ded-125c42cd0aa4.jpg)


In the "**Edit the device GLOBAL parameters**" page, it's possible to change value of Parameter "priority" and validate.

**Comment by fritz-smh** [comment]
the same on my side.

**Comment by fritz-smh** [comment]
More informations here : 
http://stackoverflow.com/questions/18161483/how-to-get-unchecked-checkbox-using-flask-or-something

**Comment by fritz-smh** [comment]
It should be fixed by using a radio button instead of a checkbox (see the link before for more informations)
Please check with the last push if this is ok on your side.

**Comment by fritz-smh** [comment]
Just fixed a type... Fase => False

**Comment by vdomos** [comment]
Just seen that there are "**Radio button**" when create device :

![domoweb_device_parameter_1](https://cloud.githubusercontent.com/assets/1257481/14863636/d0c47dc4-0cb6-11e6-87f9-7ab87cc2893a.jpg)

But still have a "**Check Box**" in the  Configure page:

![domoweb_device_parameter_2](https://cloud.githubusercontent.com/assets/1257481/14863662/eded1fb4-0cb6-11e6-8177-77055ede8dd6.jpg)
