### ISSUE TITLE
Notification for dead plugin

### ISSUE THREAD

**Issue by vdomos** [domogik/domogik#261]
This is just a idea and don't know if it's possible.

I think, it' important to report when a plugin is dead.
Maybe the scenarios would be a good choice to do that.
By adding a list of plugins in the left menu and testing in this manner if possible:

```
When plugin_name state = "dead"
do send_sms | pull_notification | send_mail 
```

And why not, if use exist:

```
When plugin_name state = "start|stop"
do action
```

Using the scenarios, we only choose the plugins we want supervise or not

**Comment by fritz-smh** [comment]
I think it would be better to create a new component named 'watchdog' which
has nothing to do with domogik itself (to avoid domogik related issues on
the watchdog).

This component may be able to do some checks/restarts depending on some
rules, for exemple :
* if a plugin is dead/stopped dans plugin config 'auto startup' == True,
then restart it and send a notification

**Comment by vdomos** [comment]
Even better if dedicated watchdog is expected :)
