### ISSUE TITLE
Scenario : if 2 devices has the same name in a plugin, only the commands/sensors of one is displayed

### ISSUE THREAD

**Issue by fritz-smh** [domogik/domogik#263]
Example for a plugin rfxcom : 
* a temperature sensor named 'foo'
* an open/close sensor named 'foo'

One of the sensor is not displayed in the blocky tree

We should add something after the name in case of duplicate : foo, foo (1), foo (2) for example

**Comment by Cereal2nd** [comment]
we should only allow a device one once per client
and not multiple times

**Comment by fritz-smh** [comment]
Locally fixed. Will be pushed soon
