### ISSUE TITLE
newScenario : when moving the if block, a javascript error occurs

### ISSUE THREAD

**Issue by fritz-smh** [domogik/domogik#267]
See http://snag.gy/kTvfz.jpg

To reproduce : put a EQUAL block in the blockly space and then try to move the IF block. It will freeze

**Comment by Cereal2nd** [comment]
these are errors inside blockly itself, i can not help here

**Comment by fritz-smh** [comment]
which release of blockly did you include ?

**Comment by Cereal2nd** [comment]
latest master

**Comment by fritz-smh** [comment]
Ok, maybe there is an opened issue on their tracker.
