### ISSUE TITLE
Display plugin timeline (enchancement)

### ISSUE THREAD

**Issue by tikismoke** [domogik/domogik#276]
Could it be add a plugin timeline button.

It should display only device from current plugin.
Available from timeline itself (like for a device when clicing is name) by adding a link on plugin name.
And also from plugin page itself (a button next to create or detected device).

As always not priority and do not nknow how diffivult it is ;)

**Comment by fritz-smh** [comment]
Good idea. I add it to 0.5 for now, will see if it will in 0.5 or 0.6 ;)
