### ISSUE TITLE
The message queue is not working for PUB/SUB messages

### ISSUE THREAD

**Issue by vdomos** [domogik/domogik#278]
Fritz,

Here the result you ask for this problem see in #275, it happened again today

![domogik_mq_error](https://cloud.githubusercontent.com/assets/1257481/13918921/996dce66-ef6a-11e5-8cc6-3bcf0783e94f.jpg)

For additional information, when I go on the Client page of the admin interface, all plugin and Core components appear dead and become alive after a few seconds.

* launch : python req_client_list.py and give the result 
$ python req_client_list.py => [req_client_list.txt](https://github.com/domogik/domogik/files/186035/req_client_list.txt)

* launch : python sub_plugin_status.py and see it you got a message for the status of all components each 15 seconds 
I well receive the status of all plugin:

   $ python sub_plugin_status.py 
    New pub message plugin.status
    {u'host': u'vesta', u'type': u'plugin', u'name': u'rfxbnz', u'event': u'alive'}
    New pub message plugin.status
    {u'host': u'vesta', u'type': u'plugin', u'name': u'weather', u'event': u'alive'}
    New pub message plugin.status
    {u'host': u'vesta', u'type': u'core', u'name': u'butler', u'event': u'alive'}
    New pub message plugin.status
    {u'host': u'vesta', u'type': u'core', u'name': u'scenario', u'event': u'alive'}
    New pub message plugin.status
    {u'host': u'vesta', u'type': u'plugin', u'name': u'diskfree', u'event': u'alive'}
    New pub message plugin.status
    {u'host': u'vesta', u'type': u'plugin', u'name': u'script', u'event': u'alive'}
    New pub message plugin.status
    {u'host': u'vesta', u'type': u'core', u'name': u'manager', u'event': u'alive'}
    New pub message plugin.status
    {u'host': u'vesta', u'type': u'plugin', u'name': u'mqtt', u'event': u'alive'}
    New pub message plugin.status
    {u'host': u'vesta', u'type': u'plugin', u'name': u'dbsensor', u'event': u'alive'}
    New pub message plugin.status
    {u'host': u'vesta', u'type': u'plugin', u'name': u'onewired', u'event': u'alive'}
    New pub message plugin.status
    {u'host': u'vesta', u'type': u'core', u'name': u'admin', u'event': u'alive'}
    New pub message plugin.status
    {u'host': u'vesta', u'type': u'core', u'name': u'dbmgr', u'event': u'alive'}
    New pub message plugin.status
    {u'host': u'vesta', u'type': u'plugin', u'name': u'vdevice', u'event': u'alive'}
    New pub message plugin.status
    {u'host': u'vesta', u'type': u'core', u'name': u'xplgw', u'event': u'alive'}
    New pub message plugin.status
    {u'host': u'vesta', u'type': u'plugin', u'name': u'rfxbnz', u'event': u'alive'}
    New pub message plugin.status
    {u'host': u'vesta', u'type': u'plugin', u'name': u'weather', u'event': u'alive'}
    New pub message plugin.status
    {u'host': u'vesta', u'type': u'core', u'name': u'butler', u'event': u'alive'}
    New pub message plugin.status
    {u'host': u'vesta', u'type': u'core', u'name': u'scenario', u'event': u'alive'}
    New pub message plugin.status
    {u'host': u'vesta', u'type': u'plugin', u'name': u'diskfree', u'event': u'alive'}
    New pub message plugin.status
    {u'host': u'vesta', u'type': u'plugin', u'name': u'script', u'event': u'alive'}
    New pub message plugin.status
    {u'host': u'vesta', u'type': u'core', u'name': u'manager', u'event': u'alive'}
    New pub message plugin.status
    {u'host': u'vesta', u'type': u'plugin', u'name': u'mqtt', u'event': u'alive'}
    New pub message plugin.status
    {u'host': u'vesta', u'type': u'plugin', u'name': u'dbsensor', u'event': u'alive'}
    New pub message plugin.status
    {u'host': u'vesta', u'type': u'plugin', u'name': u'onewired', u'event': u'alive'}
    New pub message plugin.status
    {u'host': u'vesta', u'type': u'core', u'name': u'admin', u'event': u'alive'}
    New pub message plugin.status
    {u'host': u'vesta', u'type': u'core', u'name': u'dbmgr', u'event': u'alive'}
    New pub message plugin.status
    {u'host': u'vesta', u'type': u'plugin', u'name': u'vdevice', u'event': u'alive'}
    New pub message plugin.status
    {u'host': u'vesta', u'type': u'core', u'name': u'xplgw', u'event': u'alive'}
    New pub message plugin.status
    {u'host': u'vesta', u'type': u'plugin', u'name': u'rfxbnz', u'event': u'alive'}
    New pub message plugin.status
    {u'host': u'vesta', u'type': u'plugin', u'name': u'weather', u'event': u'alive'}
    New pub message plugin.status
    {u'host': u'vesta', u'type': u'core', u'name': u'butler', u'event': u'alive'}
    New pub message plugin.status
    {u'host': u'vesta', u'type': u'core', u'name': u'scenario', u'event': u'alive'}
    New pub message plugin.status
    {u'host': u'vesta', u'type': u'plugin', u'name': u'diskfree', u'event': u'alive'}
    New pub message plugin.status
    {u'host': u'vesta', u'type': u'plugin', u'name': u'script', u'event': u'alive'}
    New pub message plugin.status
    {u'host': u'vesta', u'type': u'core', u'name': u'manager', u'event': u'alive'}
    New pub message plugin.status
    {u'host': u'vesta', u'type': u'plugin', u'name': u'mqtt', u'event': u'alive'}
    New pub message plugin.status
    {u'host': u'vesta', u'type': u'plugin', u'name': u'dbsensor', u'event': u'alive'}
    

* give the result of : ps -ef | grep dmg_ 
List of running dmg_* process:

    $ ps -ef | grep dmg_ 
    dan      16784     1  3 00:18 ?        00:29:20 /usr/bin/python /usr/local/bin/dmg_broker
    root     16785     1  0 00:18 pts/2    00:00:00 /bin/su - dan -c /usr/local/bin/dmg_forwarder >/dev/null 
    dan      16790 16785  0 00:18 ?        00:00:00 -su -c /usr/local/bin/dmg_forwarder >/dev/null 
    dan      16797 16790  0 00:18 ?        00:03:14 /usr/bin/python /usr/local/bin/dmg_forwarder
    dan      16801     1  0 00:19 ?        00:06:04 /usr/bin/python /usr/local/bin/dmg_hub
    dan      16826     1  0 00:19 ?        00:00:01 /usr/bin/python /usr/local/bin/dmg_manager -a -d -x -s -b
    dan      16830 16826  1 00:19 ?        00:13:14 /usr/bin/python /usr/local/bin/dmg_manager -a -d -x -s -b

**Comment by vdomos** [comment]
The problem is back after a few hours restarting Domogik.

I write some modification tout the **req_client_list.py** script to display only the  most important information:

    core-xplgw.vesta        dead    28/03/2016 13:12:39
    core-scenario.vesta     dead    28/03/2016 13:12:35
    plugin-vdevice.vesta    dead    28/03/2016 13:12:40
    plugin-mqtt.vesta       dead    28/03/2016 13:12:36
    core-dbmgr.vesta        dead    28/03/2016 13:12:40
    plugin-weather.vesta    dead    28/03/2016 13:12:27
    plugin-diskfree.vesta   dead    28/03/2016 13:12:35
    core-admin.vesta        dead    28/03/2016 13:12:31
    plugin-script.vesta     dead    28/03/2016 13:12:35
    plugin-rfxbnz.vesta     dead    28/03/2016 13:12:40
    plugin-onewired.vesta   dead    28/03/2016 13:12:26
    core-butler.vesta       dead    28/03/2016 13:12:32
    plugin-dbsensor.vesta   dead    28/03/2016 13:12:39

As we can see plugin and core component seems to be dead since yesterday but all plugin still working fine and the **sub_plugin_status.py** script receives the  plugin.status.

The only ERRORs found:

The dmg_forwarder is running manualy with '-f' parameter.

    mq_forwarder.log:2016-03-28 13:12:42,673 domogik-mq_forwarder ERROR BAD direction message: ['\x00plugin.configuration']
    mq_forwarder.log:2016-03-28 13:12:42,680 domogik-mq_forwarder ERROR BAD direction message: ['\x00plugin.status']
    mq_forwarder.log:2016-03-29 15:25:03,859 domogik-mq_forwarder ERROR BAD direction message: ['\x01plugin.status']
    mq_forwarder.log:2016-03-29 15:25:58,533 domogik-mq_forwarder ERROR BAD direction message: ['\x00plugin.status']
    mq_forwarder.log:2016-03-29 17:35:33,014 domogik-mq_forwarder ERROR BAD direction message: ['\x01plugin.status']
    mq_forwarder.log:2016-03-29 17:35:59,803 domogik-mq_forwarder ERROR BAD direction message: ['\x00plugin.status']
    mq_forwarder.log:2016-03-29 18:25:38,634 domogik-mq_forwarder ERROR BAD direction message: ['\x01plugin.status']
    mq_forwarder.log:2016-03-29 18:27:26,427 domogik-mq_forwarder ERROR BAD direction message: ['\x00plugin.status']

**Comment by fritz-smh** [comment]
The BAD direction messages happens also on a "good" installation.
for now I don't see what is the issue...

**Comment by vdomos** [comment]
it is not blocking, Domogik works.

The only symptoms in addition to the above message is that 
- the admin interface takes 3/4s to display the status "alive" of plugins and "core components"
- the admin can not correctly stop the plugin, the interface shows a "stopped" status but process are still there.I have to kill them.

**Comment by tikismoke** [comment]
vdomos, Nico0084 put me on a solution way :)
Try stopping onewired-plugin and tell us if you still have this bug?

**Comment by vdomos** [comment]
Arg, Domogik is now en vm and  I do not have this error, only on rpi or an old pc

**Comment by tikismoke** [comment]
Not a power problem i got 8 cpu.
@Nico0084 Point me to another source maybe, what is your current pyzmq version?

**Comment by tikismoke** [comment]
Ok finally not a pyzmq version problem.

If i stop onewired the problem goes away.
It appens only when this plugin is running. :(

**Comment by vdomos** [comment]
there was also the case where the plugin  onewired halt without explanation (issue #293).
I wonder if the problem is not related to too verbose log in this plugin.
I had reduced log messages for testing, it seems..

**Comment by tikismoke** [comment]
@Nico0084 Worked on a fix on my server the PR will point to a simple problemabout multi threads.
As i do the same in Xee and Nest maybe it multiplicate the problem.

**Comment by tikismoke** [comment]
Could be close. Thank's to Nico0084 patch
