### ISSUE TITLE
Dialogue admin and butler using unicode

### ISSUE THREAD

**Issue by axboct** [domogik/domogik#282]
screenshot of my attempt to debug the chat admin to Butler
![2016-03-27 14 45 29](https://cloud.githubusercontent.com/assets/11463718/14065313/8cdd7760-f42d-11e5-8fe1-4a3552d8e06d.jpg)

"Ça va?" also leads to the WS error

**Comment by fritz-smh** [comment]
This is fixed in the newScenario branch (or we don't speak of the same bug)

**Comment by axboct** [comment]
We were talking about this error in the IRC. Screenshot taken with newScenario. Dialogue domodroid <-> butler works well, the history displayed in the admin

**Comment by axboct** [comment]
Dialogue domoweb <-> butler works well, the history displayed in the admin after reload page. 
http://snag.gy/WJHjb.jpg

**Comment by fritz-smh** [comment]
I think it is ok now ?
Closing, if needed, reopen
