### ISSUE TITLE
Reduce the display of OpenRemote help

### ISSUE THREAD

**Issue by vdomos** [domogik/domogik#283]
I'm not a OpenRemote user and I find that the display of the help of OpenRemote overload the display in device information.

I made a little change in the file **client_devices.html** like that:

### Normal display after the modification
![domogik_admin_openremote_1](https://cloud.githubusercontent.com/assets/1257481/14066592/39cdd314-f44e-11e5-8358-f1c93b3cf6f6.jpg)

### Clicing "usage link" collapse the help:

![domogik_admin_openremote_2](https://cloud.githubusercontent.com/assets/1257481/14066595/55990da2-f44e-11e5-8a04-8d3270580a48.jpg)

Here are the little changes made in file: 
[client_devices.html.diff.txt](https://github.com/domogik/domogik/files/191009/client_devices.html.diff.txt)

Not sure it complies with your dev.
Your opinion ?

**Comment by tikismoke** [comment]
For me i found this nice (maybe because i don't use openremote at all).

**Comment by fritz-smh** [comment]
This was something I planned to do a day. Thanks to did it ;)

I will test tomorrow or a day later ;)

**Comment by Cereal2nd** [comment]
can you create a pull request for this?

**Comment by vdomos** [comment]
Done in pull request #284

**Comment by Cereal2nd** [comment]
merged
