### ISSUE TITLE
Timer for non xpl plugin

### ISSUE THREAD

**Issue by Nico0084** [domogik/domogik#286]
Hi
For 0.5
Actually there is a XplTimer class in xplconnector.py but for non xpl plugin it's not judicious to use this "specialized" timer.
In XplTimer class there is particular code used for xpl , Manager from xplconnector 
So perhaps write another class to make it general is a good way and it could be put in common/plugin.py.

**Comment by Cereal2nd** [comment]
i was actually planning to deprecate the xplTimer class

if you want to use something like the xplTimer you can use the standard threading.Timer() class

**Comment by Nico0084** [comment]
Why do you want to deprecate ? That mean in future there is no Timer ressource ?

It's an advantage to keep auto registration thread to stopping plugin, no ?
