### ISSUE TITLE
New scenario problem to edit.

### ISSUE THREAD

**Issue by tikismoke** [domogik/domogik#288]
http://snag.gy/Jp4NF.jpg
Was the new scenario created.

When i want to edit it now i got this:
http://snag.gy/KO1vf.jpg

I db i got this:
http://pastebin.com/CvZEibAt

**Comment by Cereal2nd** [comment]
are you sure the browser cache is completely cleared and everything is loaded from the new files?
As this looks like something todo with not all js files being up to date

**Comment by tikismoke** [comment]
Yes try with private And from another computer.

Le 1 avril 2016 07:48:33 GMT+02:00, Maikel Punie <notifications@github.com> a écrit :
>are you sure the browser cache is completely cleared and everything is
>loaded from the new files?
>As this looks like something todo with not all js files being up to
>date
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/domogik/domogik/issues/288#issuecomment-204256412

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by tikismoke** [comment]
I recreate it like this:
http://snag.gy/LAdYz.jpg

Need a week to see if it works.
