### ISSUE TITLE
Features of api REQ sensor_history.get

### ISSUE THREAD

**Issue by vdomos** [domogik/domogik#290]
Like in **req_sensor_history.py** example, it's possible in a plugin to get 
- the 'n' last values of a sensor,
- the values of a sensor in a period 

Possible to add in futur release some other features like:
- **min/max/avg**  for a period like in REST queries
- **sum** of the values in a period for differential counter (for example, water consumption, electricity, or rainfall for a day/month/year) (this selector doesn't exist in REST API too, can be useful to make consumption graphs )

The idea is to create plugin using data stored in Domogik

**Comment by Cereal2nd** [comment]
This should be handled in the plugin.py extension for it, closing the issue
