### ISSUE TITLE
scenario set value at 1st launch

### ISSUE THREAD

**Issue by tikismoke** [domogik/domogik#291]
When i restart domogik and until i edit the corresponding scenario, the set value took the previous sensor value not the current one.
For example:
-set a string notification to 1:

> Notify 1

-set a string notification to 2:

> Notify 2

-set a string notification to 3:

> Notify 3

-Restart domogik
-set a string notification to 1:

> Notify 3

-set a string notification to 2:

> Notify 1

-Edit and save the scenario:
-set a string notification to 3:

> Notify 3

**Comment by Cereal2nd** [comment]
Does this scenario has at least one test or at least one sensor test?

**Comment by tikismoke** [comment]
It is lunch with a if value change or last update

**Comment by Cereal2nd** [comment]
can you get a screenshot of the scenario so i can reproduce it?

**Comment by tikismoke** [comment]
http://snag.gy/dJaqj.jpg

**Comment by tikismoke** [comment]
For me this is fix with: https://github.com/domogik/domogik/commit/c4504e90454ed9d7c18a65b3be33c3c91258d888

**Comment by fritz-smh** [comment]
Closing
