### ISSUE TITLE
There is no "sensor.get" for MQ to retrieve the last value without history ?

### ISSUE THREAD

**Issue by vdomos** [domogik/domogik#295]
I did not find MQ function to get the latest value of a sensor if there is no history.
(Option: "store": false  for the sensor.)

**'sensor_history.get'** return "null" in this case., 
Yes, it's normal because there is no history.

But it could be useful to have access to the last/uniq value without having to store all values.

No ?

**Comment by Cereal2nd** [comment]
in the get device this is included

**Comment by vdomos** [comment]
Ok,
Thanks

**Comment by fritz-smh** [comment]
Closing
