### ISSUE TITLE
Mq or rest URL device update for 0.6

### ISSUE THREAD

**Issue by tikismoke** [domogik/domogik#296]
See that now domoweb do no more need to be restart as it always listen for the mq device.update message.

For other client like Domodroid is it possible to have something like a rest call or a mq needing req/rep to know if a device have changed (new/delete/update) since a certain date(timestamp).
Because when offline we could not received the message device.update.

Or should i implement another mechanism?
I'm open to idea ;)

**Comment by Nico0084** [comment]
Idea : 
We could use a state flag of device list who could be a number increment or a kind of device list checksum
This "number" will update at each device.update
A mq request to get this value could help to compare a local storage to this new value.
And client could request device list if necessary.

**Comment by fritz-smh** [comment]
A little more simple, but nearly the same as nico :)

We just need to store a timestamp of the last upgrade in db.
And add a rest/mq feature to read it. And why not in device.list maybe ?

Then, on the client, you just need to store the last timestamp seen on domogik side and compare at each startup :)

**Comment by tikismoke** [comment]
Seems fine for me.
Just needing to implement it at start then listen for device change.
Then advise user to sync not sure if forcing the sync is a right choice. For me it must stay a user choice. Just a pop-up to inform him/her. Then they decide the good time to do it.

**Comment by tikismoke** [comment]
Cereal so you think's it's something easy to add before 0.5 release?

**Comment by Cereal2nd** [comment]
I'll look at this next week, should be doable but it will br an mq request.

What do you wnat to get returned? All changed devices like in a device.get? Or just ghe ids?

**Comment by tikismoke** [comment]
No problem for mq request.

I'll just need a sort of timestamp flag then if not the same as the previous saved will call rest/devices or mq/device.get

**Comment by Cereal2nd** [comment]
What updates should be visible? I mean when should we update the timestamp?
What triggers should i implement?

**Comment by tikismoke** [comment]
In my mind it should be update every time domogik sends the device.update information.

If clients domoweb/domodroid is currently connected to mq, it already listen for change and ask user to resync (for domodroid) .
But when offline we can not catch this information and problems could appear. Like trying to send a command to no more existing device or reading sensors that dttype as changed etc.

So this timestamp should be update on any device (sensors/commands/global) change.

**Comment by Cereal2nd** [comment]
TODO

- [ ] update the field on sensor history store
- [ ] add an filter to the mq message

**Comment by Cereal2nd** [comment]
everything seems to be implemented

we may need to add some triggers on some places, but in the device.get mq, if you add a timestamp in that message you will get all changes since that timestamp
