### ISSUE TITLE
Hysteresis in scenario

### ISSUE THREAD

**Issue by tikismoke** [domogik/domogik#298]
Last problem for me about scenario.
When I use :
if A=1 OR B=0
Hysteresis
Do something.

I was thinking that if A or B value change the action will be done but no.
When using a and/or blockly in if and hysteresis ALL the sensor in the condition have to change.

It is maybe normal, i do not know but it explain some of my non working scenario.

**Comment by fritz-smh** [comment]
Try adding a else with just a hysteris and a log action. It will do the stuff. I rzally need to put an included doc in this page....

<div>-------- Message d'origine --------</div><div>De : tikismoke <notifications@github.com> </div><div>Date :2016/04/10  10:06  (GMT+01:00) </div><div>À : domogik/domogik <domogik@noreply.github.com> </div><div>Objet : [domogik/domogik] Hysteresis in scenario (#298) </div><div>
</div>Last problem for me about scenario.
When I use :
if A=1 OR B=0
Hysteresis
Do something.

I was thinking that if A or B value change the action will be done but no.
When using a and/or blockly in if and hysteresis ALL the sensor in the condition have to change.

It is maybe normal, i do not know but it explain some of my non working scenario.

**Comment by tikismoke** [comment]
Thinking about it. It certainly what make my alarm sending me so much message.
Will try before end of Holliday's to see if it make the trick.

**Comment by fritz-smh** [comment]
Any feedback ?

**Comment by tikismoke** [comment]
Not retry, it ,was différent from my alarm SMS problem.

Let you know asap.

**Comment by tikismoke** [comment]
A really fast test, with an else (also with hysteresis applyed) it works as you said.
