### ISSUE TITLE
BUG XPL loss message in xplgw

### ISSUE THREAD

**Issue by tikismoke** [domogik/domogik#304]
i roll back before https://github.com/domogik/domogik/commit/6c1336b9950e3b1d7e703947cfb3ec5f334d720e to confirm this.

With this push the xplgw do no more receive xplmessage after a short time on my machine.
xplmessage are present in dmg-dump.
The commands appears in the xplgw log but not in the plugin or in dmg-dump.

Confirm 2 times with going back after this push xpl do no more works.

**Comment by Cereal2nd** [comment]
1- shat is a short while? how long?
2- any errors in xplgw.log?

**Comment by Cereal2nd** [comment]
do you see something like

2016-04-24 21:25:14,809 domogik-xplgw DEBUG New message (from xPL) > storing in the sensor queue finished, current length = 1
2016-04-24 21:25:14,809 domogik-xplgw DEBUG Getting item from the sensor queue, current length = 0, item = '{'msg': <domogik.xpl.common.xplmessage.XplMessage object at 0x7fb0d41e7850>, 'received_datetime': 1461525914, 'clientId': u'plugin-bluez.igor'}'

in the logs?

**Comment by tikismoke** [comment]
It bugs after ~10min.

After the bug only new message from mq no more from xpl.

No other message in log or when I lunch xplgw by hand.

**Comment by Cereal2nd** [comment]
is it always 10 minuts?

**Comment by tikismoke** [comment]
Not sure it is always the same time.

You do not have this bug? Try with diskfree plugin for example.

Le 24 avril 2016 21:32:09 GMT+02:00, Maikel Punie <notifications@github.com> a écrit :
>is it always 10 minuts?
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/domogik/domogik/issues/304#issuecomment-214025890

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by Cereal2nd** [comment]
whit my rollback from a couple of days ago its solved
