### ISSUE TITLE
Mail plugin request

### ISSUE THREAD

**Issue by tikismoke** [domogik/domogik#312]
Hi all I'm going to need notification outside home (no karotz,nabaztag or even buttler). In a normal time they go to my phone by SMS but I will not have network (only wifi).

As I can still not use notifry as it need multiple parameter and is not possible for now in scenario.

I thought to send them by mail but do not now how to? Maybe a simple bash script for now but it will be useful for future to have something simpler.

**Comment by fritz-smh** [comment]
Quite simple to implement : http://blog.hotfirenet.com/envoyer-mail-depuis-le-raspberry-pi/

The plugin configuration could be used to generate the /etc/ssmtp/ssmtp.conf in another place and I am quite sure there is a way to use another file path from the command line.

I will pass my turn as I have for now too much to do :)

**Comment by tikismoke** [comment]
I asked too because it seems a bit too difficult for me ;)

**Comment by tikismoke** [comment]
I found a beautiful libs.

Someone could have a better look to create such a plug-in?

Not urgent.

https://github.com/caronc/apprise
