### ISSUE TITLE
Add a DT_Bool family type reverse option

### ISSUE THREAD

**Issue by Nico0084** [domogik/domogik#318]
An idea to simplify users (Developper and final) DT_Bool utilisation is adding a flag inversion option like a parameter for sensors and commands using DT_Bool family.

I think we can't presume  what the user, manufacturer, technology, external developper,... what meaning  given by  0/1.
Eg. it could be:
0 /1-> up/down or 0/1 -> down/up

I known there is converting functions to do this, but it's very restrictive and need creating all sensors/commands case in json plugin.
For zwave device there is no rules and specifications and we could have the both way !

Perhaps a solution by add a global params in DT type bool and all child's will let final user chose good way
For discution....
@+
Nico

**Comment by vdomos** [comment]
+1 for this idea to add a flag.

For now, i use a formula in device "Configure" to reverse value like this:

    1 if VALUE == 0 else 0

**Comment by fritz-smh** [comment]
We must analyse the global impact (on user interfaces, on butler).
No idea currently if this is a good idea or something that will be too much complex to handle.

**Comment by Cereal2nd** [comment]
i think it will be really complex.

grep on datatype on the domogik source, on every place we will need to make
an exception for the special case.
maybe its simpeler to duplicate then in the json and just prepend./append
Inv

Maikel

**Comment by Nico0084** [comment]
In reality it's conversion functionnality who allready exist.

So other way, If we add an enable/disable flag for using or not conversion definition it could do the same effect and for all DT_type no exception :)
