### ISSUE TITLE
Dt_dtype change

### ISSUE THREAD

**Issue by tikismoke** [domogik/domogik#321]
Not sure it comes from domogik or plugin.

In domogik generic plugin, i change a sensor from DT_Number to DT_brightness.
Then another to DT_Pressure by error.
This last one dt_type could no more be change. they're is no more list of dt_type to change it.

**Comment by fritz-smh** [comment]
Hi, 

This is the way it is implemented. Once you change a basci dt type (DT_Boolean, DT_Number, ...) you can't change it any more.
Maybe we should add a warning about this to avoid user being disturbed like you.

Fritz

**Comment by tikismoke** [comment]
For my point of view, we should allow user to change it again if he make a mistake like i do.

**Comment by fritz-smh** [comment]
Not sure.
Cereal implemented this, we should see with him why we should not change
the dt type after setting it (there was a reason, I don't remember which
one)

**Comment by Cereal2nd** [comment]
Changing it would be possible. THe only thing i'm thinking about is the conversion, i don't think we can update the whole db when we change the DT_Type. just changing it in the sensor without looking at the history would be possible
