### ISSUE TITLE
Device creation db, Data too long for column 'device_type_id'

### ISSUE THREAD

**Issue by Nico0084** [domogik/domogik#323]
Hi, 
In branch develop, there is some string long limitation for device_type_id.
If There is no against indication could you remove this limitation

For ozwave plugin and is many possible device_type, I have a rule to build auto name and id depending of sensors and commands. But result could make long id.

> 2016-07-23 19:55:26,791 domogik-dbmgr ERROR Error while processing request. Message is : MQMessage(action=device.create, data='{u'data': {u'xpl_stats': {}, u'name': u'Volet cuisine', u'reference': u'Qubino-ZMNHCDx', u'xpl': [], u'xpl_commands': {}, u'global': [{u'key': u'networkid', u'type': u'string', u'description': u'Zwave network name if refered in controller node or Openzwave Home ID', u'value': u'Maison'}, {u'description': u'Zwave node id', u'max_value': 255, u'min_value': 1, u'value': u'2', u'key': u'node', u'type': u'integer'}, {u'description': u'Zwave node instance id', u'max_value': 255, u'min_value': 1, u'value': u'1', u'key': u'instance', u'type': u'integer'}], u'device_type': u'ozwave.energy-k_energy-previous-reading-k_level_power_switch__down_level_up_switch', u'client_id': u'plugin-ozwave.vmdevubuntu16', u'description': u'Contr\xf4le du volet'}}') . Error is : Traceback (most recent call last):
>   File "/home/admdomo/domogik/src/domogik/bin/dbmgr.py", line 147, in on_mdp_request
>     self._mdp_reply_sensor_history(msg)
>   File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
>     self.gen.next()
>   File "/home/admdomo/domogik/src/domogik/common/database.py", line 178, in session_scope
>     self.__session.commit()
>   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 813, in commit
>     self.transaction.commit()
>   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 390, in commit
>     self._assert_active(prepared_ok=True)
>   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 214, in _assert_active
>     % self._rollback_exception
> InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (pymysql.err.DataError) (1406, u"Data too long for column 'device_type_id' at row 1") [SQL: u'INSERT INTO core_device (name, description, reference, device_type_id, client_id, client_version) VALUES (%(name)s, %(description)s, %(reference)s, %(device_type_id)s, %(client_id)s, %(client_version)s)'] [parameters: {'name': u'Volet cuisine', 'reference': u'Qubino-ZMNHCDx', 'client_id': u'plugin-ozwave.vmdevubuntu16', 'device_type_id': u'ozwave.energy-k_energy-previous-reading-k_level_power_switch__down_level_up_switch', 'client_version': u'0.5.1', 'description': 'Contr\xc3\xb4le du volet'}]
>

**Comment by Cereal2nd** [comment]
What length do you need at max?

**Comment by Nico0084** [comment]
I thing 128 could be enough, but 192 more safe :-)
