### ISSUE TITLE
Polymer ID

### ISSUE THREAD

**Issue by overload08** [domogik/domogik#325]
Bonjour.

Je souhaiterai récupérer l'id utilisé (instance-11 par ex) dans le Polymer du fichier domoweb/packs/widgets/basic/sensorChart.html.

Comment dois-je faire ?

Le but étant de rendre le graphique cliquable pour ensuite afficher le graphique en plus grand (Via pop-up jquery-ui)

**Comment by ferllings** [comment]
Salut,

C'est l'id du widget dans la bdd. Je ne sais pas vraiment comment tu pourrais le récupérer. si ton bouton est en dehors du widget lui même.

Si il est dedans, tu peux récupérer l'élément en utilisant parent(), ou autre

**Comment by overload08** [comment]
Au contraire, je veux faire un script JS "onclick" sur le graph, donc dans le widget!
Je vais essayer avec le parent()

**Comment by fritz-smh** [comment]
Tu peux regarder le widget camera/mjpeg pour un exemple d'affichage plein écran.
Par contre c'est pas au top, j'ai un souci de z-index si je mets 2 fois ce widget sur une même page.
Si tu trouves une méthode pour faire mieux, je suis preneur !!!!

**Comment by overload08** [comment]
J'ai vu que je pouvais utiliser "this.$.primary.device['id']", mais j'arrive pas a l'utiliser correctement...
Je suis en 0.4.2, j'ai pas le widget Camera ;) Mais j'ai regardé le code

**Comment by fritz-smh** [comment]
Tu feras gaffe, je crois (pas sûr) que j'ai fais des évolutions dans sensorchart en branche develop de domoweb.

**Comment by overload08** [comment]
Non rien... Mais d'autres choses intéressante !

**Comment by overload08** [comment]
Je suis passé en 0.5 et j'ai remarqué autre chose avec ton widget mjpeg.
Tu créer le widget, tu créer un autre widget (ex sensorNumber) et tu lances le full screen du jmpeg et tu as le dernier widget au dessus... J'ai tenté de le coup z-index: 9999 mais sans succès.
J'arrive pas a comprendre comment le dernier widget arrive a prendre le premier plan

**Comment by fritz-smh** [comment]
C'est exactement le problème que j'évoquais plus haut... si tu arrivais à le résoudre je serais débarassé d'un poid, tu n'imagines même pas!

A cause ce ce bug je n'ose pas faire d'autres widgets avec un mode plein écran :(

**Comment by overload08** [comment]
J'ai trouvé!
Mais c'es plus compliqué que ce que je pensais.

Dans domoweb/static/css/style.css, class .widget, il y a un z-index: 5
dans la fenêtre de développement de Chrome, si une fois la page chargée, on retirer ce z-index: 5, tout revient dans l'ordre. Petit hic, si on le retire directement dans le fichier, le widget n'est plus cliquable.

Si ca peut t'aider...

**Comment by overload08** [comment]
En fait, d'après ce que je comprends, les widgets ont le même z-index. Priorité donc au(x) dernier(s).
Etant donné que le full screen n'est ni plus ni moins qu'un "enfant" du widget, le z-index reste à 5, malgrès le forcing

**Comment by overload08** [comment]
Résolu !
2 fichiers à modifier

Dans le fichier domoweb/static/js/main.js
function insertWidgetInstance(id, widget) {
        var tag = 'dmw-' + widget.set_id + '-' + widget.set_ref;
        var instance = document.createElement(tag);
        instance.id = "instance-" + id
        instance.classList.add("widget", "loading", "widgetw" + widget.width, "widgeth" + widget.height);
        if (widget.default_style) { // If we load the default style
                instance.classList.add("style-general");
                **instance.setAttribute("style", "z-index:" + id);**
                instance.setAttribute('default_style', true);
        }
        instance.setAttribute('instanceid', id);
        instance.setAttribute('tabindex', 0);
        if (DMW.main.edit == true) {
                instance.setAttribute('edit', 'true');
        }
        DMW.main.layout.appendChild(instance);
        return instance;
}

Dans le fichier domoweb/packs/widgets/camera/mjpeg.html
        Polymer('dmw-camera-mjpeg', {
            ready: function() {
                this.mode = "normal";
                this.super();
                this.url = "/widget/camera/noname.png";
                this.urlRaw = this.url;

                // refresh the video stream each 1s to reload automatically if the stream was shut for a while
                self = this;
                setInterval(function(){
                    self.url = self.urlRaw + "?" + +new Date().getTime();
                },1000);
                **this.style.zIndex = 1000;**

            },

**Comment by fritz-smh** [comment]
Je n'arrive pas à résoudre de mon côté avec ça : 
```
diff --git a/packs/widgets/camera/mjpeg.html b/packs/widgets/camera/mjpeg.html
index 59fabca..f9622c9 100644
--- a/packs/widgets/camera/mjpeg.html
+++ b/packs/widgets/camera/mjpeg.html
@@ -72,11 +72,12 @@
                 this.url = "/widget/camera/noname.png";
                 this.urlRaw = this.url;
 
-                // refresh the video stream each 20s to reload automatically if the stream was shut for a while
+                // refresh the video stream each 60s to reload automatically if the stream was shut for a while
                 self = this;
                 setInterval(function(){
                     self.url = self.urlRaw + "?" + +new Date().getTime();
-                },20000);
+                },60000);
+                this.style.zIndex = 1000;
 
                 // but first, refresh the image 1s after the component is loaded to avoid a broken image in case of 401 error (see comment before the iframe for more informations
                 setTimeout(function(){
diff --git a/packs/widgets/communication/phoneCalls.html b/packs/widgets/communication/phoneCalls.html
index b79cfa6..159b902 100644
--- a/packs/widgets/communication/phoneCalls.html
+++ b/packs/widgets/communication/phoneCalls.html
@@ -158,6 +158,7 @@
                 this.calls = [];
                 this.last_call = null;
                 this.blacklistCommand = false;
+                this.style.zIndex = 1000;
             },
             sensorsUpdated: function() {
                 if (this.$.callerid.isSet) {
diff --git a/static/css/style.css b/static/css/style.css
index 87077dc..21bbde9 100644
--- a/static/css/style.css
+++ b/static/css/style.css
@@ -81,7 +81,9 @@ h3 {
        transform-style: preserve-3d;
        -moz-box-sizing: border-box;
     box-sizing: border-box;
+/*
     z-index: 5;
+*/
 }
 
 /* Form */
diff --git a/static/js/main.js b/static/js/main.js
index c76ad0f..0b20ad2 100755
--- a/static/js/main.js
+++ b/static/js/main.js
@@ -127,6 +127,7 @@ function insertWidgetInstance(id, widget) {
        instance.classList.add("widget", "loading", "widgetw" + widget.width, "widgeth" + widget.height);
        if (widget.default_style) { // If we load the default style
                instance.classList.add("style-general");
+               instance.setAttribute("style", "z-index:" + id);
                instance.setAttribute('default_style', true);
        }
        instance.setAttribute('instanceid', id);
```

J'ai loupé quoi ?

**Comment by overload08** [comment]
Hmmm...
Pas d'erreur dans la console de Chrome ? Tu as pensé a vider ton cache (au cas où) ?

**Comment by overload08** [comment]
Ah! Il faut laisser le z-index: 5; dans le style.css

**Comment by fritz-smh** [comment]
Même en le remettant ça ne passe pas... Pour tester je mets 2 widgets mjpeg sur la même page.

```
diff --git a/packs/widgets/camera/mjpeg.html b/packs/widgets/camera/mjpeg.html
index 59fabca..f9622c9 100644
--- a/packs/widgets/camera/mjpeg.html
+++ b/packs/widgets/camera/mjpeg.html
@@ -72,11 +72,12 @@
                 this.url = "/widget/camera/noname.png";
                 this.urlRaw = this.url;
 
-                // refresh the video stream each 20s to reload automatically if the stream was shut for a while
+                // refresh the video stream each 60s to reload automatically if the stream was shut for a while
                 self = this;
                 setInterval(function(){
                     self.url = self.urlRaw + "?" + +new Date().getTime();
-                },20000);
+                },60000);
+                this.style.zIndex = 1000;
 
                 // but first, refresh the image 1s after the component is loaded to avoid a broken image in case of 401 error (see comment before the iframe for more informations
                 setTimeout(function(){
diff --git a/packs/widgets/communication/phoneCalls.html b/packs/widgets/communication/phoneCalls.html
index b79cfa6..159b902 100644
--- a/packs/widgets/communication/phoneCalls.html
+++ b/packs/widgets/communication/phoneCalls.html
@@ -158,6 +158,7 @@
                 this.calls = [];
                 this.last_call = null;
                 this.blacklistCommand = false;
+                this.style.zIndex = 1000;
             },
             sensorsUpdated: function() {
                 if (this.$.callerid.isSet) {
diff --git a/static/js/main.js b/static/js/main.js
index c76ad0f..0b20ad2 100755
--- a/static/js/main.js
+++ b/static/js/main.js
@@ -127,6 +127,7 @@ function insertWidgetInstance(id, widget) {
        instance.classList.add("widget", "loading", "widgetw" + widget.width, "widgeth" + widget.height);
        if (widget.default_style) { // If we load the default style
                instance.classList.add("style-general");
+               instance.setAttribute("style", "z-index:" + id);
                instance.setAttribute('default_style', true);
        }
        instance.setAttribute('instanceid', id);
```

J'ai bien vidé mon cache (et en général je fais les tests en navigation privée pour éviter ce genre de désagréments justement)

https://snag.gy/FN1ZoP.jpg
https://snag.gy/c7efu9.jpg

**Comment by overload08** [comment]
Hmm, je vois. Ca a impliqué d'autres choses aussi.
Je regarde dés que je peux et te post un diff

**Comment by overload08** [comment]
```
--- /root/dev/domoweb/static/js/main.js 2016-08-31 08:28:14.540085816 +0200
+++ static/js/main.js   2016-08-30 23:06:53.285180797 +0200
@@ -127,6 +127,7 @@
        instance.classList.add("widget", "loading", "widgetw" + widget.width, "widgeth" + widget.height);
        if (widget.default_style) { // If we load the default style
                instance.classList.add("style-general");
+               instance.setAttribute("style", "z-index:" + id);
                instance.setAttribute('default_style', true);
        }
        instance.setAttribute('instanceid', id);
```
```
--- /root/dev/domoweb/static/css/style.css      2016-08-31 08:28:14.540085816 +0200
+++ static/css/style.css        2016-08-31 08:21:30.008098967 +0200
@@ -68,7 +68,7 @@
        -webkit-transition: all .3s ease;
        -moz-transition: all .3s ease;
        transition: all .3s ease;
-       z-index: 10;
+       z-index: 1000;
        overflow-y:auto;
 }
```
```
--- /root/dev/domoweb/packs/widgets/camera/mjpeg.html   2016-08-31 08:28:13.892085837 +0200
+++ packs/widgets/camera/mjpeg.html     2016-08-31 08:42:05.812058791 +0200
@@ -25,7 +25,7 @@
                 left: 0px;
                 width: 100vw;
                 height: 100vh;
-                background-color: black;
+                background-color: rgba(0, 0, 0, 0.7);
             }
             .camera-normal {
                 position: absolute;
@@ -76,7 +76,7 @@
                 setInterval(function(){
                     self.url = self.urlRaw + "?" + +new Date().getTime();
                 },20000);
-
+               initialZIndex = this.style.zIndex;

             },
             optionsUpdated: function() {
@@ -103,13 +103,15 @@
                 this.urlRaw = this.url;
             },
             zoom: function() {
-                if (this.mode == "normal") {
+                               if (this.mode == "normal") {
                     this.mode = "zoom";
                     this.$.camera.classList.add('camera-zoom');
                     this.$.camera.classList.remove('camera-normal');
                     this.$.motionjpeg.classList.add('mjpeg-zoom');
                     this.$.motionjpeg.classList.remove('mjpeg-normal');
                     this.$.cameralabel.style.visibility = "hidden";
+                   this.style.zIndex = 1000;
+
                 }
                 else {
                     this.mode = "normal";
@@ -118,6 +120,7 @@
                     this.$.motionjpeg.classList.add('mjpeg-normal');
                     this.$.motionjpeg.classList.remove('mjpeg-zoom');
                     this.$.cameralabel.style.visibility = "initial";
+                    this.style.zIndex = initialZIndex;
                 }
             }
         });

```
Par contre, si l'ID du widget dépasse 1000, on retrouvera le problème...

**Comment by fritz-smh** [comment]
Nickel !

Il faut juste pousser le zindex plus loin que 1000 à cause des boutons arrondis dans les coins de domoweb.
Je l'ai poussé à 5000 pour être sûr que ça soit bien "devant"

La transparence à 0.7, je trouve que ça fait bizarre j'ai poussé à 0.9

Merci beaucoup ! Je vais corriger le widget phoneCalls dans la foulée ;)

**Comment by fritz-smh** [comment]
Ca marche nickel aussi avec l'autre widget !
Encore merci, je n'avais pas réussi à le résoudre ce bug!

**Comment by overload08** [comment]
De rien !

**Comment by fritz-smh** [comment]
Solved.
