### ISSUE TITLE
[develop] Domogik doesn't listen on these port

### ISSUE THREAD

**Issue by overload08** [domogik/domogik#327]
After upgrade (0.4.2 to 0.5), Domogik doesn't listen to port 40405 and 40406.

tcp        0      0 10.0.101.25:40410       0.0.0.0:*               LISTEN      1001       373785      23345/python
tcp        0      0 10.0.101.25:40411       0.0.0.0:*               LISTEN      1001       373754      23352/python
tcp        0      0 10.0.101.25:40412       0.0.0.0:*               LISTEN      1001       373756      23352/python

No error in logs.

**Comment by fritz-smh** [comment]
There is only one port used in domogik 0.5 : rest is merged in admin on admin port and under /rest/

More informations in the doc : 
http://docs.domogik.org/domogik/develop/en/enduser/installation/index.html
http://docs.domogik.org/domogik/develop/en/releases/0.5.0.html#core-components-merge-of-rest-and-admin-components

(btw in the first link I see an error, I will fix it asap, online doc should be ok tomorrow)

**Comment by overload08** [comment]
Yeah, i have read that.
But same problem after fresh install...

root@gi-domogik:/opt/dmg/domogik-mq# netstat -taupen | grep LISTEN
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      0          12162       1064/exim4
tcp        0      0 10.0.101.25:40410       0.0.0.0:*               LISTEN      1001       40544       3790/python
tcp        0      0 10.0.101.25:40411       0.0.0.0:*               LISTEN      1001       40514       3798/python
tcp        0      0 10.0.101.25:40412       0.0.0.0:*               LISTEN      1001       40516       3798/python
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      108        11473       601/mysqld
tcp        0      0 0.0.0.0:50027           0.0.0.0:*               LISTEN      106        9942        372/rpc.statd
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      0          9793        335/rpcbind
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      0          11138       388/sshd
tcp6       0      0 ::1:25                  :::*                    LISTEN      0          12163       1064/exim4
tcp6       0      0 :::45733                :::*                    LISTEN      106        9948        372/rpc.statd
tcp6       0      0 :::111                  :::*                    LISTEN      0          9796        335/rpcbind
tcp6       0      0 :::22                   :::*                    LISTEN      0          11145       388/sshd

No errors in logs, no port 40406 binding...

**Comment by fritz-smh** [comment]
Can you put /var/log/domogik/core_admin.log logs ?

**Comment by overload08** [comment]
No file.

If that can help, when I lunch "python /opt/dmg/domogik/src/domogik/bin/admin.py" : 
Traceback (most recent call last):
  File "/opt/dmg/domogik/src/domogik/bin/admin.py", line 61, in <module>
    from tornado.queues import Queue
ImportError: No module named queues


root@gi-domogik:~# ps ax | grep python
 6493 ?        Sl     0:04 /usr/bin/python /usr/local/bin/dmg_broker
 6501 ?        Sl     0:00 /usr/bin/python /usr/local/bin/dmg_forwarder
 6510 ?        Sl     0:03 /usr/bin/python /usr/local/bin/dmg_hub
 6535 ?        S      0:00 /usr/bin/python /usr/local/bin/dmg_manager -a -d -x -s -b
 6536 ?        Sl     0:05 /usr/bin/python /usr/local/bin/dmg_manager -a -d -x -s -b
 6580 ?        S      0:00 /usr/bin/python /opt/dmg/domogik/src/domogik/bin/dbmgr.py
 6596 ?        Sl     0:01 /usr/bin/python /opt/dmg/domogik/src/domogik/bin/dbmgr.py
 6615 ?        S      0:00 /usr/bin/python /opt/dmg/domogik/src/domogik/bin/xplgw.py
 6627 ?        Sl     2:44 /usr/bin/python /opt/dmg/domogik/src/domogik/bin/xplgw.py
 6671 ?        S      0:00 /usr/bin/python /opt/dmg/domogik/src/domogik/bin/scenario.py
 6687 ?        Sl     0:01 /usr/bin/python /opt/dmg/domogik/src/domogik/bin/scenario.py
 6708 ?        S      0:00 /usr/bin/python /opt/dmg/domogik/src/domogik/bin/butler.py
 6709 ?        Sl     0:01 /usr/bin/python /opt/dmg/domogik/src/domogik/bin/butler.py
 8925 pts/2    S+     0:00 grep python

**Comment by overload08** [comment]
OS : Debian 8.2
Tornado 3.2.2

**Comment by overload08** [comment]
I have commnted this line in file domogik/src/domogik/bin/admin.py : 
from tornado.queues import Queue

The daemon is launched but no binding

**Comment by Cereal2nd** [comment]
what python version?

**Comment by overload08** [comment]
Python2.7

**Comment by overload08** [comment]
I have done a new VM with new fresh install. It work... I will try to find what happened

**Comment by overload08** [comment]
Found!
tornado installed version : 3.2.2, needed 4.4.1

**Comment by Cereal2nd** [comment]
hmm, according to setup.py

we require 'tornado >= 4.2',

So not sure why your setup did not fail

**Comment by overload08** [comment]
Good question...
I close this issue
