### ISSUE TITLE
MQ device.get request on "create new scenario" fail on load page.

### ISSUE THREAD

**Issue by Nico0084** [domogik/domogik#328]
When Call create new scenario from admin page is loaded but without devices list.
MQ request are handle but not device.get.
Some time request is handle but most of time fail.

> 2016-09-02 00:18:34,065 domogik-mq_broker DEBUG Client REQ received: to='scenario' data=['test.list', '{}']
> 2016-09-02 00:18:34,286 domogik-mq_broker DEBUG WORKER REP received: from='scenario' data=['test.list', '{"result": {"cron.CronTest": {"blockly": "", "description": "Trigger on a crontab rule", "parameters": [{"values": {}, "type": "string", "name": "cron.cron", "filters": {}, "description": "Cron expression"}]}, "textinpage.TextInPageTest": {"blockly": "", "description": "Check if a web page contains some text", "parameters": [{"values": {}, "type": "string", "name": "url.urlpath", "filters": {}, "description": "Url"}, {"values": {}, "type": "string", "name": "url.interval", "filters": {}, "description": "Number of seconds between 2 checks"}, {"values": {}, "type": "string", "name": "text.text", "filters": {}, "description": "Text"}]}, "time_hhmm.TimeHHMMTest": {"blockly": "", "description": "Time", "parameters": [{"values": {}, "type": "string", "name": "time.time", "filters": {}, "description": "Time (hh:mm)"}]}, "sensor.SensorTest": {"blockly": "", "description": "Check if value/date changes for a sensor with id None", "parameters": [{"values": [["value", "value"], ["trigger if the value change", "trigger_on_change"], ["trigger if the value change or last update time change", "trigger_on_all"]], "type": "list", "name": "usage.usage", "filters": {}, "description": "Sensor usage"}]}, "trigger.Hysteresis": {"blockly": "this.appendDummyInput()\\n                .appendField(\\"Trigger mode hysteresis\\");\\n                this.appendStatementInput(\\"Run\\").setCheck(null);\\n                this.setPreviousStatement(true);\\n                this.setNextStatement(true);", "description": "Trigger mode hysteresis", "parameters": [{"values": {}, "type": "int", "name": "id.id", "filters": {}, "description": "Block Id"}]}, "time_now.TimeNow": {"blockly": "", "description": "Current time (hh:mm)", "parameters": []}}}']
> 2016-09-02 00:18:34,307 domogik-mq_broker DEBUG Client REQ received: to='scenario' data=['action.list', '{}']
> 2016-09-02 00:18:34,443 domogik-mq_broker DEBUG WORKER REP received: from='scenario' data=['action.list', '{"result": {"butler.ButlerAction": {"description": "Make the butler say something.", "parameters": {"media": {"default": "*", "values": [["*", "*"], ["Audio", "audio"]], "type": "list", "description": "Media target"}, "location": {"default": "", "type": "string", "description": "Location"}, "text": {"default": "", "type": "string", "description": "Text"}}}, "call_url.CallUrlAction": {"description": "Call an url.", "parameters": {"url": {"default": "http://", "type": "string", "description": "Url"}}}, "command.CommandAction": {"description": "Start a certain command", "parameters": {"cmdparams": {"default": {}, "type": "dict", "description": "The parameters for this command"}}}, "log.LogAction": {"description": "Log a message in the scenario component logs.", "parameters": {"message": {"default": "", "type": "string", "description": "Message"}}}, "pass.PassAction": {"description": "Do nothing.", "parameters": {}}, "shell.ShellAction": {"description": "Execute a shell command.", "parameters": {"shell_command": {"default": "echo \\"Hello world\\"", "type": "string", "description": "Shell command"}}}}}']
> 2016-09-02 00:18:34,467 domogik-mq_broker DEBUG Client REQ received: to='manager' data=['datatype.get', '{}']
> 2016-09-02 00:18:34,504 domogik-mq_broker DEBUG WORKER REP received: from='manager' data=['datatype.result', '{"datatypes": {"DT_mbarPressure": {"max": null, "childs": [], "parent": "DT_Number", "unit": "mbar", "min": null}, "DT_HVACVent": {"childs": [], "values": {"1": "Heat", "0": "Auto", "3": "Fan only", "2": "Cool", "4": "Dry"}}, "DT_DateTime": {"childs": ["DT_Date", "DT_Time"], "format": "YYYY-MM-DDThh:mm:ss.s"}, "DT_String": {"childs": ["DT_Phone", "DT_Hexa", "DT_ColorRGBHexa", "DT_CoordD", "DT_CoordDM", "DT_CoordDMS"], "maxLengh": null, "format": null}, "DT_CoordDM": {"childs": [], "parent": "DT_String", "format": "(N|S) DD MM.mmm,(E|W) DD MM.mmm"}, "DT_ColorCII": {"childs": [], "values": {"B": "Blue", "Br": "Brown", "G": "Green", "O": "Orange", "Bk": "Black", "R": "Red", "W": "White", "Y": "Yellow"}}, "DT_Time": {"childs": [], "parent": "DT_DateTime", "format": "hh:mm:ss.s"}, "DT_Pressure": {"max": null, "childs": [], "parent": "DT_Number", "unit": "Pa", "min": null}, "DT_Char": {"childs": []}, "DT_VideoMjpeg": {"childs": [], "parent": "DT_Video", "format": ""}, "DT_CoordD": {"childs": [], "parent": "DT_String", "format": "DD.dddddd,DD.dddddd"}, "DT_Date": {"childs": [], "parent": "DT_DateTime", "format": "YYYY-MM-DD"}, "DT_mSecond": {"max": 999, "childs": [], "parent": "DT_Number", "unit": "ms", "min": 0}, "DT_ColorCMYK": {"childs": [], "parent": "DT_List", "format": "(C 0-100%),(M 0-100%),(Y 0-100%),(K 0-100%)"}, "DT_DayOfWeek": {"childs": [], "values": {"1": "Monday", "0": "no day", "3": "Wednesday", "2": "Tuesday", "5": "Friday", "4": "Thursday", "7": "Sunday", "6": "Saturday"}}, "DT_Tvoc": {"max": null, "childs": [], "parent": "DT_Number", "unit": "ppb", "min": 0}, "DT_State": {"childs": [], "labels": {"1": "Active", "0": "Inactive"}, "parent": "DT_Bool"}, "DT_Trigger": {"childs": [], "labels": {"1": "Triggered"}}, "DT_Battery": {"max": 100, "childs": [], "parent": "DT_Number", "unit": "%", "min": 0}, "DT_MByte": {"max": null, "childs": [], "parent": "DT_Number", "unit": "Mb", "min": null}, "DT_Month": {"max": 12, "childs": [], "parent": "DT_Number", "unit": "Month", "min": 1}, "DT_Angle": {"max": 360, "childs": [], "parent": "DT_Number", "unit": "\\u00b0", "min": 0}, "DT_Step": {"childs": [], "labels": {"1": "Increase", "0": "Decrease"}, "parent": "DT_Bool"}, "DT_Enable": {"childs": [], "labels": {"1": "Enable", "0": "Disable"}, "parent": "DT_Bool"}, "DT_Chlorine": {"max": null, "childs": [], "parent": "DT_Number", "unit": "mg/l", "min": null}, "DT_Bool": {"childs": ["DT_Switch", "DT_Enable", "DT_Binary", "DT_Step", "DT_UpDown", "DT_OpenClose", "DT_Start", "DT_State", "DT_Motion"], "labels": {"1": "True", "0": "False"}}, "DT_Hexa": {"childs": ["DT_ColorRGBHexa"], "parent": "DT_String", "maxLengh": null, "format": null}, "DT_kgWeight": {"max": null, "childs": [], "parent": "DT_Number", "unit": "kg", "min": 0}, "DT_Scaling": {"max": 100, "childs": [], "parent": "DT_Number", "unit": "%", "min": 0}, "DT_kmhSpeed": {"max": null, "childs": [], "parent": "DT_Number", "unit": "km/h", "min": null}, "DT_mActiveEnergy": {"max": null, "childs": [], "parent": "DT_Number", "unit": "mWh", "min": null}, "DT_Phone": {"childs": [], "parent": "DT_String", "maxLengh": null, "format": "+00000000000"}, "DT_kActiveEnergy": {"max": null, "childs": [], "parent": "DT_Number", "unit": "kWh", "min": null}, "DT_HVACMode": {"childs": [], "values": {"1": "Comfort", "0": "Auto", "3": "Economy", "2": "Standby", "4": "Building Protection"}}, "DT_kCurrent": {"max": null, "childs": [], "parent": "DT_Number", "unit": "kA", "min": null}, "DT_List": {"childs": ["DT_ColorRGB", "DT_ColorCMYK"], "format": null}, "DT_Number": {"max": null, "childs": ["DT_Scaling", "DT_Angle", "DT_Brightness", "DT_Temp", "DT_TempK", "DT_TempF", "DT_Pressure", "DT_mbarPressure", "DT_Humidity", "DT_AirQuality", "DT_Volt", "DT_mVolt", "DT_kVolt", "DT_Current", "DT_mCurrent", "DT_kCurrent", "DT_Power", "DT_mPower", "DT_kPower", "DT_ActiveEnergy", "DT_kActiveEnergy", "DT_ApparantEnergy", "DT_Speed", "DT_kmhSpeed", "DT_Year", "DT_Month", "DT_Day", "DT_Hour", "DT_Minute", "DT_Second", "DT_mSecond", "DT_Timestamp", "DT_mMeter", "DT_kMeter", "DT_mMeterHour", "DT_Byte", "DT_kByte", "DT_MByte", "DT_GByte", "DT_pH", "DT_Chlorine", "DT_Battery", "DT_Co2", "DT_Tvoc", "DT_Insolation", "DT_kgWeight"], "unit": null, "min": null}, "DT_Minute": {"max": 59, "childs": [], "parent": "DT_Number", "unit": "min", "min": 0}, "DT_Video": {"childs": ["DT_VideoMjpeg"]}, "DT_OpenClose": {"childs": [], "labels": {"1": "Close", "0": "Open"}, "parent": "DT_Bool"}, "DT_Switch": {"childs": [], "labels": {"1": "On", "0": "Off"}, "parent": "DT_Bool"}, "DT_Co2": {"max": null, "childs": [], "parent": "DT_Number", "unit": "ppm", "min": 0}, "DT_Motion": {"childs": [], "labels": {"1": "Motion", "0": "No motion"}, "parent": "DT_Bool"}, "DT_ColorRGB": {"childs": [], "parent": "DT_List", "format": "(R 0-255),(G 0-255),(B 0-255)"}, "DT_ActiveEnergy": {"max": null, "childs": [], "parent": "DT_Number", "unit": "Wh", "min": null}, "DT_AirQuality": {"max": null, "childs": [], "parent": "DT_Number", "unit": "ppm", "min": null}, "DT_UPSEvent": {"childs": [], "values": {"input_voltage_ok": "Input voltage returns ok", "temp_ok": "UPS temperature returns ok", "output_overload": "UPS output overload", "comms_ok": "UPS communication restored", "btp": "Battery test passed", "output_voltage_ok": "UPS Output voltage returns ok", "battlow": "Battery is low", "comms_lost": "Host lost UPS communication", "output_ok": "UPS output returns ok", "battfull": "Battery is fully charged", "output_voltage_high": "UPS Output voltage too high", "btf": "Battery test failed", "temp_high": "UPS temperature too high", "input_freq_error": "Input frequency out of range", "input_freq_ok": "Input frequency returns ok", "onmains": "Mains power", "input_voltage_low": "Input voltage too low", "output_voltage_low": "UPS Output voltage too low", "bti": "Battery test initiated", "input_voltage_high": "Input voltage too high", "onbattery": "Battery power"}}, "DT_Humidity": {"max": null, "childs": [], "parent": "DT_Number", "unit": "%", "min": null}, "DT_Timestamp": {"max": null, "childs": [], "parent": "DT_Number", "unit": null, "min": null}, "DT_Start": {"childs": [], "labels": {"1": "Start", "0": "Stop"}, "parent": "DT_Bool"}, "DT_mCurrent": {"max": null, "childs": [], "parent": "DT_Number", "unit": "mA", "min": null}, "DT_pH": {"max": null, "childs": [], "parent": "DT_Number", "unit": "pH", "min": null}, "DT_Year": {"max": null, "childs": [], "parent": "DT_Number", "unit": "Year", "min": null}, "DT_Hour": {"max": 23, "childs": [], "parent": "DT_Number", "unit": "h", "min": 0}, "DT_Second": {"max": 59, "childs": [], "parent": "DT_Number", "unit": "s", "min": 0}, "DT_Volt": {"max": null, "childs": [], "parent": "DT_Number", "unit": "V", "min": null}, "DT_Speed": {"max": null, "childs": [], "parent": "DT_Number", "unit": "m/s", "min": null}, "DT_Day": {"max": 31, "childs": [], "parent": "DT_Number", "unit": "Day", "min": 1}, "DT_HVACFan": {"childs": [], "values": {"1": "Auto", "0": "Unknown", "3": "Speed 1", "2": "Lower", "5": "Speed 3", "4": "Speed 2", "7": "Speed 5", "6": "Speed 4"}}, "DT_mMeterHour": {"max": null, "childs": [], "parent": "DT_Number", "unit": "mm/h", "min": null}, "DT_mMeter": {"max": null, "childs": [], "parent": "DT_Number", "unit": "mm", "min": null}, "DT_kMeter": {"max": null, "childs": [], "parent": "DT_Number", "unit": "km", "min": null}, "DT_mPower": {"max": null, "childs": [], "parent": "DT_Number", "unit": "mW", "min": null}, "DT_Current": {"max": null, "childs": [], "parent": "DT_Number", "unit": "A", "min": null}, "DT_ApparantEnergy": {"max": null, "childs": [], "parent": "DT_Number", "unit": "VAh", "min": null}, "DT_CoordDMS": {"childs": [], "parent": "DT_String", "format": "(N|S) DD MM SS.s,(E|W) DD MM SS.s"}, "DT_Binary": {"childs": [], "labels": {"1": "High", "0": "Low"}, "parent": "DT_Bool"}, "DT_Power": {"max": null, "childs": [], "parent": "DT_Number", "unit": "W", "min": null}, "DT_kVolt": {"max": null, "childs": [], "parent": "DT_Number", "unit": "kV", "min": null}, "DT_GByte": {"max": null, "childs": [], "parent": "DT_Number", "unit": "Gb", "min": null}, "DT_ColorRGBHexa": {"childs": [], "parent": "DT_Hexa", "maxLengh": 6, "format": "RRGGBB"}, "DT_Insolation": {"max": null, "childs": [], "parent": "DT_Number", "unit": "W/m\\u00b2", "min": 0}, "DT_kPower": {"max": null, "childs": [], "parent": "DT_Number", "unit": "kW", "min": null}, "DT_kByte": {"max": null, "childs": [], "parent": "DT_Number", "unit": "kb", "min": null}, "DT_Byte": {"max": null, "childs": [], "parent": "DT_Number", "unit": "b", "min": null}, "DT_Brightness": {"max": null, "childs": [], "parent": "DT_Number", "unit": "lux", "min": null}, "DT_TempK": {"max": null, "childs": [], "parent": "DT_Number", "unit": "K", "min": null}, "DT_mVolt": {"max": null, "childs": [], "parent": "DT_Number", "unit": "mV", "min": null}, "DT_TempF": {"max": null, "childs": [], "parent": "DT_Number", "unit": "\\u00b0F", "min": null}, "DT_Temp": {"max": null, "childs": [], "parent": "DT_Number", "unit": "\\u00b0C", "min": null}, "DT_HVACHeat": {"childs": [], "values": {"1": "Comfort", "0": "Auto", "3": "Economy", "2": "Standby", "4": "Building Protection"}}, "DT_UpDown": {"childs": [], "labels": {"1": "Down", "0": "Up"}, "parent": "DT_Bool"}, "DT_UPSState": {"childs": [], "values": {"OL": "mains", "LB": "unknown", "OB": "battery"}}}}']
> 2016-09-02 00:18:34,542 domogik-mq_broker DEBUG Client REQ received: to='dbmgr' data=['device.get', '{}']
> 2016-09-02 00:18:37,595 domogik-mq_broker INFO A worker seems to be dead : wid=k▒G▒ service=admin
> 2016-09-02 00:18:37,598 domogik-mq_broker DEBUG Try to unregister a worker : wid=k▒G▒
> 2016-09-02 00:18:37,599 domogik-mq_broker INFO Unregistered worker : wid=k▒G▒
> 2016-09-02 00:18:38,595 domogik-mq_broker INFO A worker seems to be dead : wid=k▒G▒ service=dbmgr
> 2016-09-02 00:18:38,601 domogik-mq_broker DEBUG Try to unregister a worker : wid=k▒G▒
> 2016-09-02 00:18:38,603 domogik-mq_broker INFO Unregistered worker : wid=k▒G▒
> 2016-09-02 00:18:39,877 domogik-mq_broker DEBUG Try to disconnect a worker : wid=k▒G▒
> 2016-09-02 00:18:39,882 domogik-mq_broker WARNING The worker wid=k▒G▒ is not registered, ignoring the disconnect request
> 2016-09-02 00:18:44,566 domogik-mq_broker DEBUG Try to register a worker : wid=k▒G▒, service=dbmgr
> 2016-09-02 00:18:44,570 domogik-mq_broker INFO Registered worker : wid=k▒G▒, service=dbmgr
> 2016-09-02 00:18:51,087 domogik-mq_broker DEBUG Try to register a worker : wid=k▒G▒, service=admin
> 2016-09-02 00:18:51,088 domogik-mq_broker INFO Registered worker : wid=k▒G▒, service=admin
>

**Comment by Nico0084** [comment]
After additional test  it seems that sql request who can block response. But I don't see high load charge on mysql during it !
I will add some debug in database.py to get best tracking......

**Comment by Nico0084** [comment]
I think I have find the reason : -)
Problem is due to the response time of db.
If this response time is more than MQ worker hbeat, Corresponding client worker is unregistered by MQ.
So db response can't be redirect to client.

TimeOut param of cli.request have no effect in this case because the worker is unregister before (5s) !

In domogik-mq/src/domogikmq/reqrep/broker.py process to hbeat worker is set by to params : 
```
HB_INTERVAL = 1000  #: in milliseconds
HB_LIVENESS = 5    #: HBs to miss before connection counts as dead
```

One solution could be increase HB_LIVENESS to 10 for example. Perhaps it's enough for most of configuration. But it's depend also of db size so with big db and lot of devices it'could be a problem ?

Other solution could be a system lock of this unregistered process during a MQ request. In this case we must get timeout param of source request to "lock" hbeat" only during the time required.
Implementation is more difficulte but safer process.

For discussion ;-)

**Comment by Cereal2nd** [comment]
yeah this is a known problem all around domogik

i'm working on a fix

**Comment by Nico0084** [comment]
Hi
Cereal, Have see my PR on domogik-mq ?
What do you think about this solving way ?

We can suggest to tikismoke this patch, he have an issue with the manager who lost regulary MQ req/rep connection. Probaly this is similar bug.

**Comment by Cereal2nd** [comment]
we need to test this one out before we can merge it

i'm hoping to test it tomorow or next week

**Comment by Nico0084** [comment]
Agree with you to test.
If you think it's could be a solution, tikismoke can use my git branch just
to test it. And having an other bench test.

2016-09-22 10:17 GMT+02:00 Maikel Punie <notifications@github.com>:

**Comment by tikismoke** [comment]
Test but not compliant at all...

See on irc the resume.
