### ISSUE TITLE
[develop] Variables in scenario

### ISSUE THREAD

**Issue by overload08** [domogik/domogik#329]
Variable doesn't work in scenario

```
ERROR Error while evaluating condition '<code object <module> at 0x7fe1c87f46b0, file "Scenario test", line 1>'. Error is : Traceback (most recent call last):
  File "/opt/dmg/domogik/src/domogik/scenario/scenario.py", line 404, in eval_condition
    exec(self._compiled_condition)
  File "Scenario test", line 2, in <module>
NameError: name 'var' is not defined
```

**Comment by tikismoke** [comment]
Could you post the whole scénario image?

Le 2 septembre 2016 23:07:42 GMT+02:00, overload08 <notifications@github.com> a écrit :
>Variable doesn't work in scenario
>
>ERROR Error while evaluating condition '<code object <module> at
>0x7fe1c87f46b0, file "Scenario test", line 1>'. Error is : Traceback
>(most recent call last):
>File "/opt/dmg/domogik/src/domogik/scenario/scenario.py", line 404, in
>eval_condition
>    exec(self._compiled_condition)
>  File "Scenario test", line 2, in <module>
>NameError: name 'var' is not defined
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/domogik/domogik/issues/329

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by overload08** [comment]
https://snag.gy/f1OtxD.jpg

**Comment by tikismoke** [comment]
Ok as i remember var are scenario dependent. So you try to read a it before it as been set the 1st time. In this case using a virtual device (plugin vdevice) will work at each time.

Le 2 septembre 2016 23:11:31 GMT+02:00, overload08 <notifications@github.com> a écrit :
>https://snag.gy/f1OtxD.jpg
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/domogik/domogik/issues/329#issuecomment-244488445

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by tikismoke** [comment]
This is a way to use variable

Le 2 septembre 2016 23:11:31 GMT+02:00, overload08 <notifications@github.com> a écrit :
>https://snag.gy/f1OtxD.jpg
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/domogik/domogik/issues/329#issuecomment-244488445

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by tikismoke** [comment]
https://snag.gy/oDWQAF.jpg
An example of variable used in a scenario.
1st set it to a value, then reuse it

**Comment by tikismoke** [comment]
Again another aproach with hysteresis:
https://snag.gy/yYVl78.jpg

In this case action will be done once only until it change value

**Comment by overload08** [comment]
Very simple with hysteresis ! Thank's !

**Comment by tikismoke** [comment]
You're welcome.

Think you can close the ticket and it will stay in memory for other to help them.

Don't worry I used to have the same question and problem, that's why I knew your problem and got solutions.

Le 3 septembre 2016 10:42:28 GMT+02:00, overload08 <notifications@github.com> a écrit :
>Very simple with hysteresis ! Thank's !
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/domogik/domogik/issues/329#issuecomment-244534934

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by fritz-smh** [comment]
Sorry, I am not sure to understand how you got the error.
Can you sum up ?

And keep the ticket open, even if this would be a bad use case we should trap the error !

Thanks

**Comment by tikismoke** [comment]
The var is read before sets.

Le 3 septembre 2016 11:49:40 GMT+02:00, Fritz SMH <notifications@github.com> a écrit :
>Sorry, I am not sure to understand how you got the error.
>Can you sum up ?
>
>And keep the ticket open, even if this would be a bad use case we
>should trap the error !
>
>Thanks
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/domogik/domogik/issues/329#issuecomment-244537541

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.
