### ISSUE TITLE
Db error switching from master installation to develop

### ISSUE THREAD

**Issue by tikismoke** [domogik/domogik#340]
`ERROR [root] (<class 'sqlalchemy.exc.InternalError'>, InternalError('(InternalError) (1054, u"Unknown column \'core_user_account.lock_edit\' in \'field list\'")',), <traceback object at 0x7514dd50>)  ==> (<class 'sqlalchemy.exc.InternalError'>, InternalError('(InternalError) (1054, u"Unknown column \'core_user_account.lock_edit\' in \'field list\'")',), <traceback object at 0x7514dd50>)`

Seen on irc here:
https://botbot.me/freenode/domogik/2016-09-23/?msg=73505626&page=1

**Comment by fritz-smh** [comment]
When you switch from a branch to another, you need to run python install.py


Maybe we could add some checks...

**Comment by Cereal2nd** [comment]
what check do you want to see added?

the only thing i can think of, is that we should add some sort of min db version in __init__.py of domogik
and during the startup of the db connection check with alembic if we have at least this version, if not exit and give an error message that they should upgrade.

But this works for upgrades, but not for downgrades

**Comment by fritz-smh** [comment]
Not sure it will be easy to maintain... I think we may often forget to update the __init__ file...

**Comment by Cereal2nd** [comment]
another option would be to add a check inside manager to see if we run the latest alembic version for that code base.

**Comment by Cereal2nd** [comment]
we should not do anything for this, normally people whould not switch, and people who switch need to run install.py
