### ISSUE TITLE
domogik version not check in plugin

### ISSUE THREAD

**Issue by tikismoke** [domogik/domogik#341]
From irc too,

seems nikko have install the yi plugin that require domogik 0.5.0 on a domogik master installation :(
https://botbot.me/freenode/domogik/2016-09-23/?msg=73502247&page=1

**Comment by Cereal2nd** [comment]
hmm, not sure how we can solve this in 0.5.0, i think this is a 0.4.0 bug ....

**Comment by fritz-smh** [comment]
we can check we do'nt have it anymore in 0.5 at least
