### ISSUE TITLE
db do not saved value if already exist

### ISSUE THREAD

**Issue by tikismoke** [domogik/domogik#348]
Was confusing with duplicate=false., but it has nothing to see with this.

Normally when publishing to mq via client.sensor..... the timestamp is never the same so no problems.

But when adding timestamp the value could be saved 'n' times in db meaning if i make 10 mass import, the value is stored ten times in db at the same timestamp.

**Comment by Cereal2nd** [comment]
indeed the duplicates are only checked on the last2 values

`                last2 = self.__session.query(SensorHistory) \
                    .filter(SensorHistory.sensor_id == sid) \
                    .order_by(SensorHistory.date.desc()) \
                    .limit(2).all()
`

**Comment by Cereal2nd** [comment]
so basically we need to take the timestamp into account now, and get the last2 values before the timestamp

**Comment by tikismoke** [comment]
As told with Fritz, it is really not a normal use case.

I discovered it making many mass import for same sensor. I also have to handle that in the plugin to avoid it.

In normal and everyday use it should never happens.


Le 5 octobre 2016 08:13:19 GMT+02:00, Maikel Punie <notifications@github.com> a écrit :
>so basically we need to take the timestamp into account now, and get
>the last2 values before the timestamp
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/domogik/domogik/issues/348#issuecomment-251590695

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.
