### ISSUE TITLE
send wrong target on xpl message

### ISSUE THREAD

**Issue by makwarlock** [domogik/domogik#349]
lors de passage d'un switch de on a off
le message xpl généré contient une target étonnante dans l’entête du message xpl.
au lieu d'avoir * ou le non d'un target existant j'obtient un target type : domogin-nonduplugin.hostaname ?

**Comment by fritz-smh** [comment]
Bonjour,

Pour moi il ne s'agit pas d'un bug, le device sur lequel on agit est lié à un plugin, du coup on utilise l'adresse du plugin comme target.

Est-ce que cela pose un souci dans ton usage ?

++
Fritz

**Comment by makwarlock** [comment]
le plugin que j'utilise me sert a communiquer avec raspberry distant sur celui-ci tourne xpl-hub
et un soft en c (librairie xpllib) sa source est marie-ptc.raspberryptc

lors du changement d'etat  depuis domogik j'obtient
domogik-ptc.raspberry

ptc corespond bien a mon plugin mais raspberry est l'host sur le quel tourne domogik (un pi3)
est domogik me semble coder "en dur"

du coup ma cible ne traite pas le message car il ne lui est pas destiné
effectivement le device est bien attaché a un plugin mais vu que le plugin est forcement installé sur la machine domogik le hostname est toujours celui la alors que la cible peut etre different non ?

dans l'idée de correction il faudrait ajouter un champs de configuration du plugin (ce qui me parait faisable depuis le json du plugin" dans celui-ci on stock la target...
puis lors lors de la gération du message si ce champ exite on l'utilise sinon on fait comme d'habitude

merci de ton aide....

**Comment by fritz-smh** [comment]
Il y a donc en effet un souci :)
Je regarde dès que je peux.

2016-10-09 21:36 GMT+02:00 makwarlock <notifications@github.com>:

**Comment by makwarlock** [comment]
merci à toi cette fonctionnalité sera la bien venue pour les connexion xpl avec des outils externe a domogik comme un arduino ou autre raspberry.
Pour continuer le dev de mon plugin je vais tricher un peu et translater la target avant de l’interpréter mais c'est peu cavalier comme méthode
je suis ok pour tout test qui permettrait de faire avancer le pb...
encore merci
@+

**Comment by tikismoke** [comment]
@makwarlock Juste pour info il fait quoi ton plugin? il est dispo sur github? c'est pour faire avancer domodroid autant que les plugins ;)

**Comment by makwarlock** [comment]
c'est un pseudo équivalant au plugin-generic développé par fritz-smh mais avec la gestion d'un switch qui ne semble pas encore présent dans son plugin. l'objectif est l’asservissement de la pompe de mon puit canadien (hydraulique) en fonction de la temperature exterieur. en effet la pompe n'a pas besoin de tourner quand la temp ext est comprise en 13° et 20°
dans l'idee j'ai un pi 3 sur le quel tourne domogik/domoweb dans ma baie info
et un pi 1 sur le quel tourne un soft en c (xpllib) sur celui-ci  j'ai de connecté :
              - un dht-22 (sonde installé a l"exterieur de la maison) 
               - un relai qui alimente le puit ou non
l'etat de la sonde est régulierement envoyé a domogik 
un scenario me permet de mettre en marche la pompe (ou non) en fonction des temps externe
enfin un switch dans l'interface de domoweb me permet de bypasse l'ensemble pour forcer le fonctionnement a ma demande...
prochaine étape meme chose mais avec une VMC
@plus

**Comment by tikismoke** [comment]
Question bêtes hein :) pourquoi ne pas modifier le plugin generic de fritz et proposer un Pull Request avec la commande ''suplémentaire"" si je comprends bien

**Comment by makwarlock** [comment]
2 raisons toutes simple
  1 je test d'abord en local (je maitrise pas complétement le dev des plugin de domogik)
  2 je ne suis pas du tout a l'aise avec l'utilisation de github
mais je vais regarder de près cela et c'est effectivement une bonne chose a faire et je serai ravi de partager mon travail..

**Comment by tikismoke** [comment]
Tes raisons sont très louables et compréhensibles. Au début on est tous pareil, puis on devient accrocs ;)

A l'occasion quand tu sera prêt passe sur IRC on t'aideras avec plaisir. Courage pour la suite

**Comment by makwarlock** [comment]
effectivement les dialogues seront simplifié avec l'usage d'irc je te solliciterai alors avec plaisir 
mais il me semblait normal de présenter ce "bug" sur le bugtraker d'autre pouvant le rencontrer...
