### ISSUE TITLE
Global installation script

### ISSUE THREAD

**Issue by fritz-smh** [domogik/domogik#371]
Create an installation script that install :
- dependencies
- domogik-mq last release
- domogik last release
- domoweb last release
- brain base package
- some other packages ? (weather + autoconfiguration ?)

**Comment by Cereal2nd** [comment]
also add a simple way to get the latest datatypes.json file

so
1- fetch it from github (maybe a seperated repo)
2- restart domogik and domoweb

this will alow us faster dt_type changes

**Comment by Cereal2nd** [comment]
20:20 < fritz_gh1la> 20:17 < cereal_> so we can create something like
20:20 < fritz_gh1la> 20:18 < cereal_> wget domogik.org/fetch and this downlaods the install script and starts it
20:20 < fritz_gh1la> 20:19 < cereal_> wget -O - http://www.domogik.org/get.py | python
20:20 < fritz_gh1la> this was the idea

**Comment by tikismoke** [comment]
We can add a widget and device fake camera with an url from giphy.com? Or any other live webcam.

**Comment by fritz-smh** [comment]
In progress... see https://github.com/domogik/domogik-installation
