### ISSUE TITLE
Systemd support

### ISSUE THREAD

**Issue by fritz-smh** [domogik/domogik#374]
Handle systemd to start domogik, domogik-mq, xplhub, domoweb

**Comment by jaywax** [comment]
Hi,
I propose this kind of configuration : https://gist.github.com/jaywax/9a67d02c7a4c5d78e3ed23684de28edd
With it, /etc/default/domogik and /etc/default/domogik-mq are no more used, and for this reason, systemd files must be generated at installation's time (it's not possible to use variable for ExecStart with systemd for example).
- Pros : All domogik service are dependent of each others. We can tweak the order of start.
- Cons : If you stop one service, you stop all the services (may be not the good choice for domoweb...)

**Comment by jaywax** [comment]
dmg_send seems to be a good solution to stop properly domogik's components. Is there some doc about its use ?
Thanks.

**Comment by vdomos** [comment]
Good idea,

admin.py and gunicorn will be alone in same service ?
It would be useful to be able to restart both with a single command.



2017-07-27 14:27 GMT+02:00 jaywax <notifications@github.com>:

**Comment by jaywax** [comment]
No i don't think so (i don't know for gunicorn like isn't present in stable, but surely if it's managed by manager.py, the main process in domogik.service).
To do that, admy.py and guinicorn must not be launched by manager.py.
See --> https://gist.github.com/jaywax/c598159b0116188c7fff5ef6d3c3f600

**Comment by cereal2nd** [comment]
ok the systemd files are copied, not sure what else we need to do ....

**Comment by jaywax** [comment]
Files are to be copied in /etc/systemd/system
Then `systemctl daemon-reload` to advertise systemd daemon that configuration changed. 
After that, just `systemctl start|restart domogik.service`, for enable it at boot time `systemctl enable domogik.service`.

Lot of documentation on the use of systemd can be found here : https://www.digitalocean.com/community/tutorials/how-to-use-systemctl-to-manage-systemd-services-and-units
