### ISSUE TITLE
Butler's translation: Unicode

### ISSUE THREAD

**Issue by axboct** [domogik/domogik#379]
Butler error. If the name contains unicode characters butler did not respond to the name.
Мaybe it's a bug а rivescript
Here is my test

```
 + <bot name>
 - What you wanted?

```
does not work. always answers "I do not understand"

```
+ what is your name
- <bot name>

```
returns the name of the butler

easy to repeat. It should be given the name of Butler, which contains such an accented character

**Comment by fritz-smh** [comment]
I pushed a fix. Can you test ?
I am not sure of the fix because I did it on a remote system with charset console issues... So not easy to fix in these conditions.
If needed, please reopen the issue ;)

**Comment by axboct** [comment]
does not work. my Google-Kung Fu helped me find it https://github.com/aichaos/rivescript-python/issues/40

**Comment by fritz-smh** [comment]
reopened :(

**Comment by fritz-smh** [comment]
Tell me if this is ok now, there was a issue related to the reading of the config file...
