### ISSUE TITLE
Develop, dependencies install revision issue

### ISSUE THREAD

**Issue by Nico0084** [domogik/domogik#383]
Here I proprose to put all dependencies issue by using `sudo ./install.py --dist-packages`

- Ubuntu 16.04
   - python-magic==0.4.12 instead of  required : python-magic >= 0.4.3

**Comment by fritz-smh** [comment]
Sorry, I didn't understand what to do with this issue. Can you give some more explanations ?

Thanks,

**Comment by Nico0084** [comment]
Yep ;)
On fresh install user can have some dependencies in regard of distrib. 
And here or other place he could put this issue to informe others user

**Comment by Nico0084** [comment]
Indeed there is no fix  to do !
It's a distribution repository probleme that don't have good revision of
dependency.
I thinknow we can make a base information to list these kind of issues
Linked as known install problem  in doc.

**Comment by fritz-smh** [comment]
There is an error page in the doc : docs/users/errors/index.txt

Can you complete it ?

thanks,

**Comment by Nico0084** [comment]
Ubuntu python-magic issue, fixed by commit 
https://github.com/domogik/domogik/commit/745db2defe8dc1232419fda46ee1040b54025ba0
and
https://github.com/domogik/domogik/commit/4c17ca60a188145260fe34b5981ae7f60828752a
