### ISSUE TITLE
Add a location parameters 

### ISSUE THREAD

**Issue by Nico0084** [domogik/domogik#386]
Hi,
Idea for enhancement 
Add a location information that user can config in admin.
This parameter could be use, for example, by cron system to  calculate ephemeris date.

**Comment by Cereal2nd** [comment]
adding this to the config file would be easy.

Adding it inside the admin, is a bit more work.
As we would need a new config table to store it (core_config). Another option would be to reuse the plugin_config and store these values as core-[manager|admin].<hostname> plugin.

we can add this to the next release

**Comment by fritz-smh** [comment]
Hi,

The idea is good, but for the next release indeed.
I can't tag issues from here, could you add it to the 0.6 milestone?

Thanks,

**Comment by Cereal2nd** [comment]
I already did for 0.6.1

**Comment by Cereal2nd** [comment]
in what format do we want to store this?

just a timezone? or gps coordinates?

**Comment by Nico0084** [comment]
Not really specific need. But
PyEphem could use (city, country) by call Google location and get
coordinate.

It's depend if we want user can locate own house. We need gps. If not city
and country is enough
Surely Google could also locate a full home address  !
My opinion is that city, country is enough and more friendly.
For security no precis location.



Le 14 déc. 2016 6:34 AM, "Maikel Punie" <notifications@github.com> a écrit :

in what format do we want to store this?

just a timezone? or gps coordinates?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/domogik/domogik/issues/386#issuecomment-266947017>, or mute
the thread

**Comment by Cereal2nd** [comment]
something like this?
http://ubilabs.github.io/geocomplete/examples/form.html

**Comment by fritz-smh** [comment]
This seems to be finished.
I close the ticket. Please reopen if something is missing or create a new one.
