### ISSUE TITLE
[0.6]Alembic

### ISSUE THREAD

**Issue by overload08** [domogik/domogik#394]
Also on 0.5, the version of alembic installed by install.py isn't ok

ERROR:root:The 'alembic' version installed on this system (0.6.5) is not recent enough. Please install at least alembic >= 0.7.4
 ==> The 'alembic' version installed on this system (0.6.5) is not recent enough. Please install at least alembic >= 0.7.4
========= TRACEBACK =============
Traceback (most recent call last):
  File "./install.py", line 497, in install
    exit(0)
  File "/usr/lib/python2.7/site.py", line 375, in __call__
    raise SystemExit(code)
SystemExit: 0

=================================
ERROR:root:(<type 'exceptions.SystemExit'>, SystemExit(0,), <traceback object at 0x7f4cb90cb248>)
 ==> (<type 'exceptions.SystemExit'>, SystemExit(0,), <traceback object at 0x7f4cb90cb248>)

System : Debian 8.6

Resolution : 
wget http://ftp.fr.debian.org/debian/pool/main/a/alembic/alembic_0.8.8-2_all.deb
dpkg -i alembic_0.8.8-2_all.deb

**Comment by overload08** [comment]
root@dev-dmg:~# apt-cache show alembic
Package: alembic
Status: install ok installed
Priority: optional
Section: python
Installed-Size: 1633
Maintainer: PKG OpenStack <openstack-devel@lists.alioth.debian.org>
Architecture: all
Version: 0.8.8-2
Depends: python-alembic | python3-alembic, libjs-sphinxdoc (>= 1.0)
Description: lightweight database migration tool for SQLAlchemy
 Alembic is a new database migration tool, written by the author
 of SQLAlchemy. A migration tool offers the following functionality:
 .
  * Can emit ALTER statements to a database in order to change the
    structure of tables and other constructs
  * Provides a system whereby "migration scripts" may be constructed;
    each script indicates a particular series of steps that can
    "upgrade" a target database to a new version, and optionally a
    series of steps that can "downgrade" similarly, doing the same
    steps in reverse.
  * Allows the scripts to execute in some sequential manner.
 .
 This package provides /usr/bin/alembic script and documentation for Alembic,
 and depends on the python-alembic package which contains all the actual code
 (in Python 2) for Alembic to actually work.
Description-md5: 9064bef180e0a63eed793d56e9039cdd
Homepage: https://bitbucket.org/zzzeek/alembic

Package: alembic
Version: 0.6.5+ds-1
Installed-Size: 776
Maintainer: Debian Python Modules Team <python-modules-team@lists.alioth.debian.org>
Architecture: all
Depends: python-alembic, libjs-sphinxdoc (>= 1.0), python, python:any (>= 2.6~)
Suggests: python3-alembic
Description-en: lightweight database migration tool for SQLAlchemy
 This package provides /usr/bin/alembic script and documentation for Alembic
Description-md5: 3fa0c5c04f214aaf7f9334a00f72b645
Homepage: http://www.bitbucket.org/zzzeek/alembic
Section: python
Priority: optional
Filename: pool/main/a/alembic/alembic_0.6.5+ds-1_all.deb
Size: 186630
MD5sum: 291c9c6a88b4456589b7b853c1ba843a
SHA1: 7542ab07441be3050329ea287c8d18342a19bd2b
SHA256: a73f239d6e262cc433f09beadbffaea8ad52743f35f352d3df3a2a4627b27c38

root@dev-dmg:~# cat /etc/debian_version
8.6

**Comment by fritz-smh** [comment]
Fixed by updating the doc : 
```
About Debian stable (8.6)
*************************

If you are using a Debian stable, you will need to install a more recent release of the **alembic** package. You can do ::

    $ cd /tmp
    $ wget http://ftp.fr.debian.org/debian/pool/main/a/alembic/alembic_0.8.8-2_all.deb
    $ sudo dpkg -i alembic_0.8.8-2_all.deb

```
