### ISSUE TITLE
[0.5.0] Flask-Themes2

### ISSUE THREAD

**Issue by overload08** [domogik/domogik#397]
Lors de l'install : 
Installed /usr/local/lib/python2.7/dist-packages/tornado-4.4.2-py2.7-linux-x86_64.egg
Searching for Flask-Themes2
Reading https://pypi.python.org/simple/Flask-Themes2/
Best match: Flask-Themes2 0.1.4.linux-x86-64
Downloading https://pypi.python.org/packages/d3/00/450ee99e95fd860acdc8dcad8de07b42029bfe9904d5300bd7849cfdbd45/Flask-Themes2-0.1.4.linux-x86_64.tar.gz#md5=71321801f51576557850b4b08b70af89
Processing Flask-Themes2-0.1.4.linux-x86_64.tar.gz
error: Couldn't find a setup script in /tmp/easy_install-NwbHv5/Flask-Themes2-0.1.4.linux-x86_64.tar.gz
========= TRACEBACK =============
Traceback (most recent call last):
  File "./install.py", line 454, in install
    raise OSError("setup.py doesn't finish correctly")
OSError: setup.py doesn't finish correctly
 
=================================
ERROR:root:(<type 'exceptions.OSError'>, OSError("setup.py doesn't finish correctly",), <traceback object at 0x7f88b4c88bd8>)
 ==> (<type 'exceptions.OSError'>, OSError("setup.py doesn't finish correctly",), <traceback object at 0x7f88b4c88bd8>)

Résolution : 
pip install Flask-Themes2
Relancer l'install

**Comment by fritz-smh** [comment]
Quelle distribution ?

Avais-tu lancé le script debian_packages_install.sh ? Il fait ceci : 

pip install -e git://github.com/sysr-q/flask-themes2.git#egg=flask_themes2-dev

**Comment by overload08** [comment]
C'est Basilic__ qui a eu le soucis, il a à priori suivit la doc

**Comment by fritz-smh** [comment]
Je ferme, car le souci vient d'ailleurs et on n'a pas eu masse de gens à l'avoir... peut être un souci temporaire du côté de ce package là...
