### ISSUE TITLE
mysql get sensor history error (ubuntu 16.04)

### ISSUE THREAD

**Issue by Nico0084** [domogik/domogik#400]
With : mysql  5.7.16-0ubuntu0.16.04.1 (default ubuntu install)
Getting sensor history make error.
Symptom are : 

- In domoweb no sensor history in graph.
   /var/log/domoweb/console.log error :

> 2016-12-19 10:14:01,919 domoweb:INFO WS: Received message ["sensor-gethistory",{"caller":146,"id":11,"from":1482052450,"to":1482138850,"interval":"hour","rest_auth":{"username":"admin","password":"123"}}]
> 2016-12-19 10:14:01,921 domoweb:INFO REST Call :
>  https://admin:123@192.168.0.192:40406/rest/sensorhistory/id/11/from/1482052450/to/1482138850/interval/hour/selector/avg
> 2016-12-19 10:14:02,032 tornado.application:ERROR Future exception was never retrieved: Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
>     yielded = self.gen.throw(*exc_info)
>   File "/opt/dmg/domoweb-0.5.1/domoweb/handlers.py", line 205, in on_message
>     data = yield self.WSSensorGetHistory(jsonmessage[1])
>   File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
>     value = future.result()
>   File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
>     raise_exc_info(self._exc_info)
>   File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
>     yielded = self.gen.throw(*exc_info)
>   File "/opt/dmg/domoweb-0.5.1/domoweb/handlers.py", line 373, in WSSensorGetHistory
>     response = yield http.fetch(request)
>   File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
>     value = future.result()
>   File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
>     raise_exc_info(self._exc_info)
>   File "<string>", line 3, in raise_exc_info
> HTTPError: HTTP 500: Internal Server Error

- with rest url : https://admin:123@192.168.0.192:40406/rest/sensorhistory/id/11/from/1482052450/to/1482138850/interval/hour/selector/avg
return "Internal server error"
   /var/log/domogik/core_admin.log error : 

> ERROR:tornado.application:Uncaught exception GET /rest/sensorhistory/id/11/from/1482052450/to/1482138850/interval/hour/selector/avg (192.168.0.173)
> HTTPServerRequest(protocol='https', host='192.168.0.192:40406', method='GET', uri='/rest/sensorhistory/id/11/from/1482052450/to/1482138850/interval/hour/selector/avg', version='HTTP/1.1', remote_ip='192.168.0.173', headers={'Accept-Language': 'fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4', 'Accept-Encoding': 'gzip, deflate, sdch, br', 'Host': '192.168.0.192:40406', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.21 Safari/537.36', 'Connection': 'keep-alive', 'Cookie': 'i18next=fr-FR; user="2|1:0|10:1481880564|4:user|16:YWRtaW4tbW9hbmE=|e340fe6faae88fc1983e0f042ae3490fcac1418fe5d9bd6f7ab1a34c6fffad15"; session=.eJxFkM1qwzAQhF-l6JxDItsXQw4tckQDu8ZFrtBeQlv_SlYLdotThbx7lVx6m4HhG2Yu7NTN7TKwvHublnbDTmPD8gt7eGc5I3nwIHEgWSQkq8x4siTRlWKwoOroTUa2_gVfp6WodugPvpSwkjjGTONRTROoPsWAFgU5CM2AmkYUL74Ubgu8yFDHjlvGPnkUOJUaR7KNA-sSlK9R37r6LanHzPAiAdufQR-90RVHX3AQ0cvnPbtu2Mcyd6fvL9d-_k8Q1RrRDhQkEKaRVL0ihwARjRoSssBJmDOEIpAaPFiTQrW_436Wdr7fsbv-AaWbYIE.Czk2pQ.tGlK2M1dLS6EpjbUYJar6bpc8t0', 'Upgrade-Insecure-Requests': '1'})
> Traceback (most recent call last):
> .....
> .....
> InternalError: (pymysql.err.InternalError) (1055, u"Expression #3 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'domogik.core_sensor_history.date' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")
> 	[SQL: u"SELECT year(core_sensor_history.date) AS year_1, month(core_sensor_history.date) AS month_1, week(core_sensor_history.date, %(week_2)s) AS week_1, day(core_sensor_history.date) AS day_1, hour(core_sensor_history.date) AS hour_1, avg(core_sensor_history.value_num) AS avg_1 \nFROM core_sensor_history \nWHERE core_sensor_history.sensor_id = %(sensor_id_1)s AND date >= '2016-12-18 10:14:10' AND date < '2016-12-19 10:14:10' GROUP BY year(core_sensor_history.date), month(core_sensor_history.date), day(core_sensor_history.date), hour(core_sensor_history.date)"] [parameters: {u'sensor_id_1': 11, u'week_2': 3}]
> ERROR:tornado.access:500 GET /rest/sensorhistory/id/11/from/1482052450/to/1482138850/interval/hour/selector/avg (192.168.0.173) 311.19ms
> 

Issues due to myslq version : 
http://stackoverflow.com/questions/37951742/1055-expression-of-select-list-is-not-in-group-by-clause-and-contains-nonaggr/38002876#38002876

Solution : 
-  Edit  /etc/mysql/conf.d/mysql.cnf file 
`sudo nano /etc/mysql/conf.d/mysql.cnf
`
- Add at the end of file : 
```
[mysqld]
sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
```
- Save and close edit.
- Restart mysql : 
`sudo service mysql restart`

This should fix sensor history issue :)

**Comment by axboct** [comment]
another way to solve - use MariaDB.

**Comment by jschaeke** [comment]
Had the same issue, added the line to mysql.cnf... works now.

**Comment by Cereal2nd** [comment]
we may just have to add this in the docu

in case mysql < version 5.7.5

**Comment by jschaeke** [comment]
Not so trivial to install older version in Ubuntu, I would rather add the extra line in the config than installing older version. Are the newer MariaDB versions not suffering from this problem?

**Comment by axboct** [comment]
in my case. I have installed mariadb from the repository "default".
mariadb-server / xenial-updates, xenial-updates, xenial-security, xenial-security, now 10.0.28-0ubuntu0.16.04.1 all [installed]
there is no problem of sensors history

**Comment by fritz-smh** [comment]
@Cereal2nd so, to sum up : 
we are not compliant witg mysql >= 5.7.5, but compliant with mariadb ?

**Comment by Cereal2nd** [comment]
No we are not complient with mysql < 5.7.5

**Comment by fritz-smh** [comment]
Ah, why ?

**Comment by Cereal2nd** [comment]
Thats what the docs say. I i missread them

**Comment by jschaeke** [comment]
It would be interesting to have domogik compliant with some LTS debian distro as I assume it would typically run on a device running some long term supported linux distro. That's at least my intention to have it running on the 16.04 ubuntu until the next LTS comes around (18.04).

**Comment by fritz-smh** [comment]
I looked to see if we could do some check during installation.

The best way to get the release seems to be : 
mysqld --version 2>/dev/null | sed "s/^.* \([0-9\.]*\)[- ].*$/\1/"

Some examples without the sed : 
mysqld  Ver 5.6.30-1 for debian-linux-gnu on x86_64 ((Debian))
mysqld  Ver 10.1.20-MariaDB-3 for debian-linux-gnu on x86_64 (Debian unstable)
mysqld  Ver 5.5.47-0+deb8u1 for debian-linux-gnu on x86_64 ((Debian))

There is no constant in the way it is displayed... sometimes we get mysql, sometimes mariadb, sometimes neither of myslq or mariadb....

So I think I will : 

1. during installation, do a test on the version : if version < 5.7.5, request the user to install mariadb
2. in the doc, upgrade to request to install mariadb

Are you ok with this ?

(notice that I am running an old 5.6.3 mysql with no issue...)

**Comment by fritz-smh** [comment]
Fixed, closing
