### ISSUE TITLE
domogik-mq_broker WARNING broker has no service dbmgr  [domogik 0.6]

### ISSUE THREAD

**Issue by vdomos** [domogik/domogik#401]
With the merge dbmgr/admin,

I have this error in mq log:

    2016-12-20 15:49:56,529 domogik-mq_broker DEBUG Client REQ received: to='dbmgr' (timeout=10.0s) data=['sensor_history.get', '{"sensor_id": 86, "mode": "last"}']
    2016-12-20 15:49:56,529 domogik-mq_broker WARNING broker has no service dbmgr

When plugin vdevice, request MQ:

    2016-12-20 15:50:06,539 domogik-vdevice ERROR ### 0MQ REQ/REP: 'Traceback (most recent call last):
     File "bin/vdevice.py", line 108, in sensorMQValueIsSet
        sensor_history = mq_client.request('dbmgr', msg.get(), timeout=10).get()
    AttributeError: 'NoneType' object has no attribute 'get'

**Comment by Cereal2nd** [comment]
i'll adapt the mq lib, to reroute all request going to the dbmgr to the admin

**Comment by fritz-smh** [comment]
There were some hardcoded stuff in MQ lib ?

**Comment by tikismoke** [comment]
> i'll adapt the mq lib, to reroute all request going to the dbmgr to the admin

So in client we could continue using old MQ msg for all version?

**Comment by Cereal2nd** [comment]
ok, the plugin must be fixed, you should not do any mq requests inside the plugin.

If you need it we will add an api for it inside plugin.py

**Comment by vdomos** [comment]
I read on IRC:
"there are functions to get the last values from plugin.py"

A example to help for reading the last value ?

2016-12-21 9:56 GMT+01:00 Maikel Punie <notifications@github.com>:

**Comment by fritz-smh** [comment]
You can use the function get_device_list and parse the json result to get
each sensor last value.

The best thing would be on domogik side to add a function
get_sensor_last_value(sensod_id). Would it fit your needs ? We could add it
in 0.5.2 release.

**Comment by vdomos** [comment]
I agree, if possible for a get_sensor_last_value(sensod_id) function.
Could be useful in several cases, I think.

Also possible to return with the last value if the data is in time-out or not ?
A plugin must to know if value is up to date.

This is not urgent, I can use the function "get device_list" for now.
