### ISSUE TITLE
Value string to num conversion BUG

### ISSUE THREAD

**Issue by tikismoke** [domogik/domogik#402]
"value_str": "5,8", "value_num": null
"value_str": "5.8", value_num": 5.8

So in a scenario value - 1 for example we get "null-1". That's overload crash is scenario.

**Comment by tikismoke** [comment]
related to https://github.com/domogik/domodroid/issues/134

**Comment by Cereal2nd** [comment]
not sure this is a bug.

5,8 = string, so not a number
5.8 = float

**Comment by tikismoke** [comment]
It depends of your language. In French number use a comma not a point.

**Comment by Cereal2nd** [comment]
but in python its not, i don't think we should fix this

**Comment by fritz-smh** [comment]
For a french end user, "5,8" is not a string but a float.

In scenario we should convert for the locale. I did this for the butler,
let me found the related code

**Comment by Cereal2nd** [comment]
this is not scenario, this is at database level ....

**Comment by fritz-smh** [comment]
The issue is related to a scenario bug found by overload

The related code in the butler :

            try:
                if len(user_locale.split(".")) > 1:     # fr_FR.UTF-8
                    the_locale = "{0}".format(user_locale)
                else:                                   # fr_FR
                    the_locale = "{0}.UTF-8".format(user_locale)
                #locale.setlocale(locale.LC_ALL, str("fr_FR.UTF-8"))
                locale.setlocale(locale.LC_ALL, the_locale)
                the_value = locale.format(u"%g", float(the_value))
            except:
                log.warning(u"Unable to format the value '{0}' as float/int
with the locale '{1}'".format(the_value, the_locale))

**Comment by Cereal2nd** [comment]
yeah but the vaue and value_num is stored in the database, and the conversion is done there

**Comment by fritz-smh** [comment]
I agree, on database side we should not change anything.
But in scenario, if the input is an integer/float, we should try it and if
it raise an error (2,8 instead of 2.8 for example), we should try to
convert the integer/float from the user locale to the system locale. If it
still fails, then this is a bad value.

**Comment by Cereal2nd** [comment]
then we need to do this check on all places where we use value_num

better way to handle this is at the db level. Just not sure how

**Comment by fritz-smh** [comment]
Where do we use this as a human entry ?

**Comment by Cereal2nd** [comment]
i think we should use

locale.atof instead of just float()

**Comment by fritz-smh** [comment]
if it works, ok for me :)

**Comment by vdomos** [comment]
Question:

if sensor is set with a Rest request like that:

    curl -s "http://host:40406/rest/cmd/id/39?value=5,8"

In admin, the sensor is displayed as string for a DT_Scaling in this example below, it's same issue ?

![screenshot_20161221_161514](https://cloud.githubusercontent.com/assets/1257481/21394427/e526c374-c798-11e6-836e-ccd9059981be.png)

**Comment by tikismoke** [comment]
I think yes, it is value_str but if you look to the rest data of this sensor you will see value_num= null

**Comment by fritz-smh** [comment]
@domos, I didn't see the difference with a number who have a point in your
screenshot ?
Can you show the both cases ?

**Comment by vdomos** [comment]
With a real number:

    curl -s "http://host:40406/rest/cmd/id/39?value=5.7"

![screenshot_20161221_170155](https://cloud.githubusercontent.com/assets/1257481/21396094/3eccd1c4-c79f-11e6-8bb0-f9dc1ab5fa1d.png)

With a string:

    
![screenshot_20161221_170351](https://cloud.githubusercontent.com/assets/1257481/21396181/986a68a4-c79f-11e6-8bb8-0f38fe18b4de.png)

in the database:

    (dan@localhost) [domogik]> select * from core_sensor_history where sensor_id=346 order by date desc limit 2  ;
    +----------+-----------+---------------------+-----------+-----------+--------------------+
    | id       | sensor_id | date                | value_num | value_str | original_value_num |
    +----------+-----------+---------------------+-----------+-----------+--------------------+
    | 10055925 |       346 | 2016-12-21 17:03:19 |      NULL | toto      |               NULL |
    | 10055799 |       346 | 2016-12-21 17:01:16 |       5.7 | 5.7       |                5.7 |
    +----------+-----------+---------------------+-----------+-----------+--------------------+
    2 rows in set (0.00 sec)

The test is done with vdevice plugin. 

Does the plugin have to check whether the value received by MQ is of the correct type or should this be done in the core ?

**Comment by Cereal2nd** [comment]
this means its the same problem.

**Comment by Cereal2nd** [comment]
hmm,

we can solve this, but look at the example below.
It can be dangerous to solve it

>>> locale.resetlocale()
>>> locale.getlocale()
('en_US', 'UTF-8')
>>> locale.atof('5.8')
5.8
>>> locale.atof('5,8')
58.0

**Comment by Cereal2nd** [comment]
ok, we decided the following:

for sensor values we will always use the . as decimal seperator, so a value coming from a plugin should always use a .
We will use the default python way of handling this.


For the values we use in the userinterface, (butler, scenario) we will use the locale to do the correct casting to a float.
What is described here, a sensor sets a value to 5,8 thisis for python a string, so we will store it as a string, and not as a number.

**Comment by tikismoke** [comment]
For example in domodroid for a sensor I should display 20,5°C (locale usertype) but send 20.4 (python float) to rest/ for command to be correctly stored exact?

Le 9 janvier 2017 14:26:16 GMT+01:00, Maikel Punie <notifications@github.com> a écrit :
>ok, we decided the following:
>
>for sensor values we will always use the . as decimal seperator, so a
>value coming from a plugin should always use a .
>We will use the default python way of handling this.
>
>
>For the values we use in the userinterface, (butler, scenario) we will
>use the locale to do the correct casting to a float.
>What is described here, a sensor sets a value to 5,8 thisis for python
>a string, so we will store it as a string, and not as a number.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/domogik/domogik/issues/402#issuecomment-271283509

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by fritz-smh** [comment]
Yes

You should just handle the locale when displaying in the widget.

**Comment by tikismoke** [comment]
OK. For command it's already done. Just to check sensors...

**Comment by Cereal2nd** [comment]
Ok, we can not solve this on all places as blockly has the following code:

`// Strip out thousands separators.
text = text.replace(/,/g, '');
`

so we would have to hack blockly to make it possible, and even then we depend on the locale send by the browser, if the user is not configuring it correctly, we will fail.

So we should just change this bug into a documentation udpate, to make a big warning, to ALWAYS and EVERYWHERE use the . as a decimal seperator
