### ISSUE TITLE
Install option "without the xpl hub"

### ISSUE THREAD

**Issue by fritz-smh** [domogik/domogik#404]
Is it a good idea to allow an install without the xplhub ?

**Comment by Cereal2nd** [comment]
yes i like it, i don't need the xplhub at home anymore all plugins work without xpl

**Comment by jschaeke** [comment]
Also the weather plugin? As it was failing last week because my xplhub wasn't starting...

**Comment by fritz-smh** [comment]
The plugin weather should be migrated to no xpl.
I just need to find some time (or someone) to do it

**Comment by cereal2nd** [comment]
added install option

https://github.com/domogik/domogik/commit/2f01af2094021b25e7d26ec645823ef697261484

Todo
- [ ] store no-xpl-hub in config file
- [ ] xplgw do not connect to xpl if the options is set
- [ ] manager do not extend from xplPlugin
