### ISSUE TITLE
butler from rest not a  json in answer

### ISSUE THREAD

**Issue by tikismoke** [domogik/domogik#405]
Make that sort of query:
`http://192.168.0.63:40406/rest/butler/discuss?callback=foo&data=%7B%22text%22%3A%22il+est+quelle+heure%22%2C%22media%22%3A%22speech%22%2C%22identity%22%3A%22domodroid%22%2C%22source%22%3A%22terminal-android.android-28a6e9e9cb649392%22%7D`

Answer looks like:

`foo({"lang": "fr_FR", "mood": null, "text": "il est 12 heure 19 ", "sex": "female", "location": null, "media": "speech", "reply_to": "terminal-android.android-28a6e949392", "identity": "Aria", "is_reply": true})`

foo is not a json object or array. is it normal?

**Comment by fritz-smh** [comment]
Yes, this is a javascript callback (search for jsonp on google for more informations).
I will check the next week the code to tell you if you can avoid the callback. If not, I will implement a way to avoid it.

**Comment by tikismoke** [comment]
Ok no problem it cans be handle likt that, it was just to be sure:

`String json = jsonp.substring(jsonp.indexOf("(") + 1, jsonp.lastIndexOf(")"));`

**Comment by fritz-smh** [comment]
Let the issue open :)

**Comment by fritz-smh** [comment]
You can check the code to use in the new ButlerAndroid app in ButlerService.java.

Closing

**Comment by tikismoke** [comment]
Could you migrate the ticket to domodroid to not forbid it please ?
