### ISSUE TITLE
Configuration of plugin not saved

### ISSUE THREAD

**Issue by jschaeke** [domogik/domogik#410]
Impacted plugins: weather and mqtt plugin
Symptom: need to start manually, configuration in domogik admin screen always shows default.
On latest develop-stream. 0.5-hotfix is not impacted (confirmed by me and vdomos)

Original ticket:
https://github.com/vdomos/domogik-plugin-mqtt/issues/3

**Comment by Cereal2nd** [comment]
i'll look at it this has probably something todo with the dbmgr and admin merge
