### ISSUE TITLE
0.5-hotfix db insertion error

### ISSUE THREAD

**Issue by tikismoke** [domogik/domogik#411]
from ozwave i got a new device:

> {
> 
>     "info_changed": "2016-12-27 19:57:17",
>     "description": "",
>     "reference": "NorthQ -- NQ-9121 Gas Meter",
>     "xpl_commands": { },
>     "client_id": "plugin-ozwave.domogik",
>     "sensors": {
>         "meter-gas": {
>             "value_min": null,
>             "data_type": "DT_VolumeM3",
>             "incremental": true,
>             "id": 2509,
>             "reference": "meter-gas",
>             "conversion": "",
>             "name": "Gas",
>             "last_received": null,
>             "timeout": 0,
>             "formula": null,
>             "last_value": null,
>             "value_max": null
>         },
>         "battery-level": {
>             "value_min": null,
>             "data_type": "DT_Battery",
>             "incremental": false,
>             "id": 2510,
>             "reference": "battery-level",
>             "conversion": "",
>             "name": "Battery level",
>             "last_received": 1483010712,
>             "timeout": 0,
>             "formula": null,
>             "last_value": "100",
>             "value_max": 100.0
>         }
>     },
>     "id": 401,
>     "xpl_stats": { },
>     "commands": { },
>     "name": "compteur gaz essai",
>     "parameters": {
>         "networkid": {
>             "value": "MyHomeId",
>             "type": "string",
>             "id": 564,
>             "key": "networkid"
>         },
>         "node": {
>             "value": "38",
>             "type": "integer",
>             "id": 565,
>             "key": "node"
>         },
>         "batterycheck": {
>             "value": "y",
>             "type": "boolean",
>             "id": 567,
>             "key": "batterycheck"
>         },
>         "instance": {
>             "value": "1",
>             "type": "integer",
>             "id": 566,
>             "key": "instance"
>         }
>     },
>     "device_type_id": "ozwave.battery-level_meter-gas",
>     "client_version": "0.5.3"
> 
> }

Battery is saved correctly but the gas meter get error in xplgw.log:

> 2016-12-28 21:44:58,232 domogik-xplgw DEBUG Getting item from the store queue, current length = 2, item = '{'sensor_id': u'2509', 'value': 11360.32, 'time': 1482957896}
> '
> 2016-12-28 21:44:58,234 domogik-xplgw DEBUG Send client status : alive
> 2016-12-28 21:44:58,317 domogik-xplgw INFO Storing stat for device 'compteur gaz essai' (401) and sensor 'Gas' (2509) with value '11360.32' after conversion.
> 2016-12-28 21:44:58,322 domogik-xplgw ERROR Error when adding sensor history : Traceback (most recent call last):
>   File "/home/domogik/src/domogik/bin/xplgw.py", line 849, in run
>     current_date)
>   File "/home/domogik/src/domogik/common/database.py", line 1034, in add_sensor_history
>     self.__raise_dbhelper_exception(u"Error when adding data to sensor history. Sensor id = {0}  | Value = {1}  | Date = {2}. Error is {3}".format(sid, value, date, tra
> ceback.format_exc()))
>   File "/home/domogik/src/domogik/common/database.py", line 1934, in __raise_dbhelper_exception
>     raise DbHelperException(error_msg)
> DbHelperException: u'Error when adding data to sensor history. Sensor id = 2509  | Value = 11360.32  | Date = 1482957896. Error is Traceback (most recent call last):\n
>  File "/home/domogik/src/domogik/common/database.py", line 895, in add_sensor_history\n    last = last2[0]\nIndexError: list index out of range\n'
> 
> 2016-12-28 21:44:58,323 domogik-xplgw DEBUG Getting item from the store queue, current length = 1, item = '{'sensor_id': u'2510', 'value': 97, 'time': 1482957897}'
> 2016-12-28 21:44:58,323 domogik-xplgw INFO Storing stat for device 'compteur gaz essai' (401) and sensor 'Battery level' (2510) with value '97' after conversion.
>

**Comment by vdomos** [comment]
Same error for me on 0.5-hotfix too:

    2016-12-29 17:19:58,153 domogik-xplgw ERROR Error when adding sensor history : Traceback (most recent call last):
      File "/opt/dmg/domogik/src/domogik/bin/xplgw.py", line 849, in run
        current_date)
      File "/opt/dmg/domogik/src/domogik/common/database.py", line 1034, in add_sensor_history
        self.__raise_dbhelper_exception(u"Error when adding data to sensor history. Sensor id = {0}  | Value = {1}  | Date = {2}. Error is {3}".format(sid, value, date, traceback.format_exc()))
      File "/opt/dmg/domogik/src/domogik/common/database.py", line 1934, in __raise_dbhelper_exception
        raise DbHelperException(error_msg)
    DbHelperException: u'Error when adding data to sensor history. Sensor id = 3  | Value = 1718849  | Date = 1483028398. Error is Traceback (most recent call last):\n  File "/opt/dmg/domogik/src/domogik/common/database.py", line 895, in add_sensor_history\n    last = last2[0]\nIndexError: list index out of range\n'

**Comment by Cereal2nd** [comment]
Can you get me the sensor condig?

The duplicate, round value those things.

**Comment by vdomos** [comment]
For me, sensor_id 3:

    mysql> select * from core_sensor where id=3;
    +----+-----------+--------------+----------------------+-------------+---------+-----------+------------+------------+---------------+-----------+-----------+---------------+-------------+----------------+---------------+-------------------+---------+
    | id | device_id | name         | reference            | incremental | formula | data_type | conversion | last_value | last_received | value_min | value_max | history_store | history_max | history_expire | history_round | history_duplicate | timeout |
    +----+-----------+--------------+----------------------+-------------+---------+-----------+------------+------------+---------------+-----------+-----------+---------------+-------------+----------------+---------------+-------------------+---------+
    |  3 |         2 | Counter diff | onewire counter diff |           1 | NULL    | DT_Number |            | NULL       |          NULL |      NULL |      NULL |             1 |           0 |              0 |             0 |                 1 |     600 |
    +----+-----------+--------------+----------------------+-------------+---------+-----------+------------+------------+---------------+-----------+-----------+---------------+-------------+----------------+---------------+-------------------+---------+

**Comment by tikismoke** [comment]
Can't find the difference between this sensors and any other :(

**Comment by Cereal2nd** [comment]
hmm, this is because of the incremental is set to 1 i think

**Comment by tikismoke** [comment]
I removed it yesterday night to see. Do not look for log since but they're still no value this morning.

**Comment by Cereal2nd** [comment]
foudn the bug, working on a fix

**Comment by tikismoke** [comment]
Cool, can't try before 2 days to be sure but nice to know. THANK'S

**Comment by Cereal2nd** [comment]
This one is introduced by the following commit:

https://github.com/domogik/domogik/commit/e95b3f73b29c21b46570aabf21d79d186d38fa9c
will look for a fix
