### ISSUE TITLE
Enable person locations

### ISSUE THREAD

**Issue by Cereal2nd** [domogik/domogik#413]
if a person has location enabled create the following
1- device person location (device param is person id)
2- sensor lat
3- sensor long

This enables us to reuse the sensor system for locations

**Comment by tikismoke** [comment]
Why not use a dt_type dt_coord like real sensor with lat,lon

Le 31 décembre 2016 17:46:51 GMT+01:00, Maikel Punie <notifications@github.com> a écrit :
>if a person has location enabled create the following
>1- device person location (device param is person id)
>2- sensor lat
>3- sensor long
>
>This enables us to reuse the sensor system for locations
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/domogik/domogik/issues/413

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by Cereal2nd** [comment]
thats even better :)
