### ISSUE TITLE
Admin : set up the public ip/port

### ISSUE THREAD

**Issue by fritz-smh** [domogik/domogik#417]
To allow a more easier configuration of domodroid/butler/whatever else, we should add in the QR code these informations : public ip, public rest url, public mq ports  (all the same that is already published but with the external config access.

This may be done in 2 steps : 

1. during installation, find the public ip (or dns is possible) and configure it in the config table (type=core, key=public_ip_or_dns
1. still during installation, set the configured ports in the same table (with appropriate keys)

2. on the admin, add a page to be able to review this configuration items (with some auto check done while displaying the page)

3. on admin, update the QR code

**Comment by tikismoke** [comment]
What about if a user have a non static ip?

**Comment by Cereal2nd** [comment]
the public ip can also be a dns name. Then it will work

**Comment by Cereal2nd** [comment]
The config is available in 0.6, and the qr code is adapted
so closing this, as now its a domodroid thing
