### ISSUE TITLE
Harden admin/rest security

### ISSUE THREAD

**Issue by Cereal2nd** [domogik/domogik#419]
Currently we use the insecure basic auth.
But there is a flask extension that allows us to use digest.

- [x] Implement server side sessions (flask-sessions)
- [ ] http digest auth lib for flask https://flask-httpauth.readthedocs.io/en/latest/

**Comment by tikismoke** [comment]
I add to make try wih @overload to understand why dmd do no more work.
Even with disabling auth in conf, /rest/sensor and /rest/device are never available until you log at least once on admin.

Let me know if i should find a solution to handle http auth digest for 0.9 api and if it is normal even ith auth disable?

**Comment by Cereal2nd** [comment]
Nothing changed in the authentication

the only change is that the session is stored on the server and not on the client.
Any error in the admin?

**Comment by tikismoke** [comment]
Does your domodroid works as except in this version ?

**Comment by overload08** [comment]
Don't forget to add secret_key to domogik.cfg !

**Comment by Cereal2nd** [comment]
If you rerun install.py it will do it for you

**Comment by tikismoke** [comment]
Can you have a look with Overload as he have a develop version and the problems.
When i try to open /rest/sensor or /rest/device/ on his installation it always return a blank empty page or the previous one.

**Comment by Cereal2nd** [comment]
checked with overload, and connected my domodroid to it, and it worked perfectly.

All is ok in his installation

**Comment by tikismoke** [comment]
So it was only the admin issue. OK good to know that nothing to change in DMD ;)

**Comment by jschaeke** [comment]
Will this enable it to expose the rest interface (securely) to the internet so that we can use it directly in domodroid? If not, I would like to raise this feature as an enhancement.

**Comment by Cereal2nd** [comment]
That is the idea.

**Comment by Cereal2nd** [comment]
part 2 can not be done ... as we have a hashed user password.

so to open up rest/admin to the internet we suggest to add an ssl certificate in combination with the current auth.
