### ISSUE TITLE
pyzmq crash in ioloop start

### ISSUE THREAD

**Issue by Cereal2nd** [domogik/domogik#421]
File 'admin.py', line 292, in __init__
    IOLoop.instance().start()
  File '/usr/lib/python2.7/dist-packages/zmq/eventloop/ioloop.py', line 168, in start
    raise e
ZMQError: Invalid argument

This happens if your running libzmq 4.2.0 with pyzmq < 16.0

Ticket created for reference

**Comment by jschaeke** [comment]
`2017-05-27 18:16:19,772 domogik-admin ERROR Traceback (most recent call last):
  File '/opt/dmg/domogik/src/domogik/bin/admin.py', line 313, in __init__
    IOLoop.instance().start()
  File '/usr/lib/python2.7/dist-packages/zmq/eventloop/ioloop.py', line 151, in start
    super(ZMQIOLoop, self).start()
  File '/usr/local/lib/python2.7/dist-packages/tornado-4.4.2-py2.7-linux-armv7l.egg/tornado/ioloop.py', line 831, in start
    self._run_callback(callback)
  File '/usr/local/lib/python2.7/dist-packages/tornado-4.4.2-py2.7-linux-armv7l.egg/tornado/ioloop.py', line 604, in _run_callback
    ret = callback()
  File '/usr/local/lib/python2.7/dist-packages/tornado-4.4.2-py2.7-linux-armv7l.egg/tornado/stack_context.py', line 275, in null_wrapper
    return fn(*args, **kwargs)
  File '/opt/dmg/domogik/src/domogik/common/plugin.py', line 1265, in force_leave
    sys.exit()
SystemExit
`
Just upgraded from 0.5.2 to develop, got this, any idea? (Raspbian)
