### ISSUE TITLE
Documentation update to avoid "Checking if Domogik is available"

### ISSUE THREAD

**Issue by ACBXL** [domogik/domogik#422]
Hi,

could I please ask you to add the following step in the domogik installation guide (or otherwise FAQ section)? 
Update in /etc/domogik/domogik.cfg:
`[admin]
interface=eth0`
to 
`[admin]
interface=eth0,lo`
Without this change domoweb does not start, but hangs with a message "Checking if Domogik is available". I ran into this problem yesterday after doing a fresh domogik installation, following the documentation. This additional step could help others save time troubleshooting the problem.

Thanks

**Comment by fritz-smh** [comment]
You did it in 0.5-hotfix or develop ?

**Comment by Cereal2nd** [comment]
ah develop i'll merge
