### ISSUE TITLE
Request for scenario update for time's test

### ISSUE THREAD

**Issue by vdomos** [domogik/domogik#427]
Relate to this issue https://github.com/domogik/domogik/issues/425 , and as discussed with  fritz-smh  ,

* Possibility to use the "current time" as a datatype DT_Time to be display in notification or to be save in a sensor for further testing ?

* Currently the current time is converted to minutes since midnight for test.
Would it be possible to use a conversion to timestamp to allow time's tests > 24h ?

* Add in scenario's "other sensors" a "Current datetime" too for above test (>24h).

thanks,

**Comment by fritz-smh** [comment]
as #425, we would like to process it in 0.6.

@vdomos  : could you set your vdevice plugin with the time/datetime devices as compliant with domogik 0.6.0 ?

**Comment by vdomos** [comment]
"set your vdevice plugin with the time/datetime devices as compliant with domogik 0.6.0" ?
Don't understand
