### ISSUE TITLE
register_cb_update_devices don't handle "Global parameters" modifications

### ISSUE THREAD

**Issue by vdomos** [domogik/domogik#439]
I do not know if it's normal or not.
when I update a Global parameter in device configuration, the update_device function is not called.

The other tests of updating or create new device are seen by the callback function, it works very well.

**Comment by fritz-smh** [comment]
Fixed in 0.5-hotfix branch : e44488c..fd54881

**Comment by Cereal2nd** [comment]
still need to merge to develop, so reopening

**Comment by fritz-smh** [comment]
sorry for this, I forgot the admin/dbmgr merge
