### ISSUE TITLE
register_cb_update_devices and "Global parameters" modifications (2)

### ISSUE THREAD

**Issue by vdomos** [domogik/domogik#442]
To continue the issue #439, I can now receive 'device.update' callback, it's ok. 
but with multiples parameters the 'callback' fonction is called for every parameter.

In this exemple,the function will be called 2 times :

![screenshot_20170120_233604](https://cloud.githubusercontent.com/assets/1257481/22167869/58a19d00-df69-11e6-9c94-23f34936b06e.png)

With multiples parameters, It will be difficult to do action in the calback function because this function will be called several times in parallel for each parameter even if one parameter is modified.

Would it be possible to receive only one notification 'device.update' when updating the Global parameters with the final "device_list" ?

**Comment by Nico0084** [comment]
Fixed in PR #547
