### ISSUE TITLE
[develop] xplgw issue

### ISSUE THREAD

**Issue by overload08** [domogik/domogik#448]
Without dmg_cron, deleted devices stay in DB.
xplgw seem to doesn't make difference between active and deleted devices.
So it make Traceback when it try to update "deleted" device

**Comment by Cereal2nd** [comment]
after looking at it we found the problem.

this is a simple fix in the database interface

**Comment by cereal2nd** [comment]
This should be solved in develop, can you confirm?

**Comment by overload08** [comment]
Ok in develop
