### ISSUE TITLE
Admin : the admin seems to be unable to response to MQ when a rest request is in progress

### ISSUE THREAD

**Issue by fritz-smh** [domogik/domogik#461]
Use case : ask the butler over rest about a sensor.
``` 
INFO in application [/opt/dmg/domogik/src/domogik/admin/application.py:94]:
http request for /rest/butler/discuss received
--------------------------------------------------------------------------------
2017-02-27 21:54:57,988 domogik.admin.application INFO http request for /rest/butler/discuss received
INFO:domogik.admin.application:http request for /rest/butler/discuss received
{'username': 'admin', 'password': 'xxxxx'}
Rest auth active - user authenticated
Rest auth active - user authenticated - user is admin (ok)
2017-02-27 21:55:07,313 domogik-admin DEBUG Send client status : alive
--------------------------------------------------------------------------------
DEBUG in application [/opt/dmg/domogik/src/domogik/admin/application.py:86]:
 => response status code: 200
--------------------------------------------------------------------------------
2017-02-27 21:55:08,694 domogik.admin.application DEBUG  => response status code: 200
DEBUG:domogik.admin.application: => response status code: 200
--------------------------------------------------------------------------------
DEBUG in application [/opt/dmg/domogik/src/domogik/admin/application.py:87]:
 => response content_type: application/json
--------------------------------------------------------------------------------
2017-02-27 21:55:08,694 domogik.admin.application DEBUG  => response content_type: application/json
DEBUG:domogik.admin.application: => response content_type: application/json
2017-02-27 21:55:08,698 domogik-admin DEBUG MQ Request received : <MQMessage(action=sensor_history.get, data='{u'sensor_id': 657, u'mode': u'last'}')>
``` 

As we see here, the MQ request is seen 10 seconds after the rest call.

I think that something is missing : something should be threaded (the old dbmgr part ?)

**Comment by fritz-smh** [comment]
After some more tests, the issue is : 

1. we do a rest url call
2. the action of the rest call does a MQ req/rep to the butler
3. the butler does also a MQ req/rep, but to the admin (to get a sensor last value)

During the action 2, the action 3 is blocked. It is received by the admin only when the action 2 has finished.

**Comment by fritz-smh** [comment]
I did specific tests : when a rest url call is in progress, the admin is unable to process the req/rep requests done to it

I will try to fix this (surely by adding some thread somewhere)

**Comment by fritz-smh** [comment]
In a more general way, a call to a rest url is blocking all other rest urls.

It seems that flask is not threading the calls...

**Comment by fritz-smh** [comment]
It seems there is an easy fix :

Normally, the WSGI server included with Flask is run in single-threaded mode, and can only handle one request at a time. Any parallel requests will have to wait until they can be handled, which can lead to issues if you tried to contact your own server from a request.

With threaded=True requests are each handled in a new thread. How many threads your server can handle concurrently depends entirely on your OS and what limits it sets on the number of threads per process. The implementation uses the SocketServer.ThreadingMixIn class, which sets no limits to the number of threads it can spin up.

Note that the Flask server is designed for development only. It is not a production-ready server. Don't rely on it to run your site on the wider web. Use a proper WSGI server like gunicorn or uWSGI) instead.

**Comment by cereal2nd** [comment]
fixed with https://github.com/domogik/domogik/commit/8e5288f2265a8873788c12dac5969d31405586af
