### ISSUE TITLE
Develop: callback for new/update devices no longer works in this branch

### ISSUE THREAD

**Issue by vdomos** [domogik/domogik#469]
There is no error wiith "register_cb_update_devices" function
but any  update/new device never run the callback.

        # Callback for new/update devices
        self.log.info(u"==> Add callback for new/update devices.")
        self.register_cb_update_devices(self.reload_devices)

It always works in 0.5hotfix

Test with vdevice, mqtt, weather plugins

**Comment by cereal2nd** [comment]
after looking at some debug it seems that the pub message is not transmitted anymore

**Comment by vdomos** [comment]
Works again with last commits.
Tested with different plugins
