### ISSUE TITLE
Propose to add datatype for three-valued logic

### ISSUE THREAD

**Issue by vdomos** [domogik/domogik#482]
For use with thermostat / alarm with three states like on/off/disable.
Or presence Yes/No/Unknown
In order to make a basic widget  to represent the 3 states.

For example of datatype:

    "DT_Trinary": {
        "labels": {
            "0": "False",
            "1": "True",
            "-1": "???"  Tralse ?
        },
        "childs": [
            "DT_Triswitch",
            ...
        ]
    },

    "DT_Triswitch": {
        "labels": {
            "0": "On",
            "1": "Off",
            "-1": "Disable"
        },
        "parent": "DT_Trinary",
        "childs": []
    },

**Comment by jschaeke** [comment]
As referenced in https://github.com/vdomos/domogik-plugin-mqtt/issues/8 I'd need similar functionality for my shutters. I'll use 2 relais per shutter, with per shutter 3 states:

- Nothing:  relais 1 and 2 not active 
- Up: relais 1 active
- Down: relais 2 active 

Will be using a 16 channel relais for it (https://github.com/jschaeke/arduinoHouse)

**Comment by jaywax** [comment]
Hi,
I've got the same needs for another domogik-plugin.
https://github.com/jaywax/domogik-plugin-mprsg6z/issues/1

Thanks !
