### ISSUE TITLE
dmg_package installation evolution

### ISSUE THREAD

**Issue by vdomos** [domogik/domogik#487]
The **dmg_package** script can install a plugin.

It is just an idea of improvement

Some plugins like onewire, mqtt, ping, ... need dependencies to work.
**dmg_package** script can run a include script in plugin to try installation of the dependency and alert if this fails

**Comment by fritz-smh** [comment]
Yes, it can be done as the info.json list the plugin prerequisites.

It must just be changed to allow sudo for dmg_package during domogik install

**Comment by tikismoke** [comment]
Is it also true if dependencies are not available through pip install or apt-get?

**Comment by fritz-smh** [comment]
The package installer will be improved in next release (> 0.6)
I postpone this idea.

This may be done witht the inclusion of packages available directly in the admin
