### ISSUE TITLE
0.5.2 -> develop : Admin crash on launch ioloop.py in stacktrace

### ISSUE THREAD

**Issue by jschaeke** [domogik/domogik#498]
On Raspbian, admin won't start. Only trace in admin_log:
`2017-05-27 18:44:05,452 domogik-admin ERROR Traceback (most recent call last):
  File '/opt/dmg/domogik/src/domogik/bin/admin.py', line 313, in __init__
    IOLoop.instance().start()
  File '/usr/lib/python2.7/dist-packages/zmq/eventloop/ioloop.py', line 151, in start
    super(ZMQIOLoop, self).start()
  File '/usr/local/lib/python2.7/dist-packages/tornado-4.4.2-py2.7-linux-armv7l.egg/tornado/ioloop.py', line 831, in start
  File '/usr/local/lib/python2.7/dist-packages/tornado-4.4.2-py2.7-linux-armv7l.egg/tornado/ioloop.py', line 604, in _run_callback
  File '/usr/local/lib/python2.7/dist-packages/tornado-4.4.2-py2.7-linux-armv7l.egg/tornado/stack_context.py', line 275, in null_wrapper
  File '/opt/dmg/domogik/src/domogik/common/plugin.py', line 1265, in force_leave
    sys.exit()
SystemExit
`
Any suggestions? So far I did upgrade jessie to jessie-backports (all packages) and all pip packages, didnt help. Reverted back to 0.5.2, no issue anymore.

**Comment by fritz-smh** [comment]
Can you try to launch the admin in foregroud :
1. start domogik
2. launch the admin : cd src/domogik/bin/ ; ./admin.py -f
3. it should not start as some admin process are up. The command showed you the process pid. Kill all of them. Wait a few seconds
4. Relaunch the admin : cd src/domogik/bin/ ; ./admin.py -f
5. Attach the full output to the issue

I think something is not catched in the logs.

Thanks

**Comment by jschaeke** [comment]
I switched to develop again and did ./install to generate a new config (to which I added the ssl). After that I followed your instructions but don't get that original error anymore:
https://gist.github.com/jschaeke/d8036f7c2c93d00b8a473b2efcd17291

however I get a 404:Not Found when navigating to https://192.168.1.59:40405/, on :40406 I get nothing.

**Comment by fritz-smh** [comment]
The port 40405 is for admin websockets
Use the 40406 for admin "web"

This is strange you got nothing on port 40406.

Your issue is here :
`2017-05-30 21:43:19,726 domogik-admin INFO Starting webserver as: None --preload --access-logfile /var/log/domogik/core_admin_http.log --error-logfile /var/log/domogik/core_admin_http.log --log-level debug --certfile /var/lib/domogik/ssl_cert.pem --keyfile /var/lib/domogik/ssl_key.pem -b 127.0.0.1:40406 -b 192.168.1.59:40406 -w 2 domogik.admin.application:app`

gunicorn is not found.
Can you do `pip install -r requirements.txt` ? It should install all needed dependencies

For me : TODO : update install doc

**Comment by jschaeke** [comment]
yes, that fixed it.
I can login and so far I see 2 notices I can't get away (although I filled the global config/location in):

- Not all config set, you should first set the basic config Fix it
- No home location set, you should configure it first

but can't get the velbus, weather and mqtt plugin started because their configuration isn't loaded and can't update it (forgets it)... also global config is not remembered....
Update: a reboot did manage to get the 3 plugins to see their configuration and were able to start. the global config however I can't set and although a location is set the two notices are still there...

PS: for reference, it should look like
`
2017-05-30 23:23:49,979 domogik-admin INFO Starting webserver as: /usr/local/bin/gunicorn --preload --access-logfile /var/log/domogik/core_admin_http.log --error-logfile /var/log/domogik/core_admin_http.log --log-level debug --certfile /var/lib/domogik/ssl_cert.pem --keyfile /var/lib/domogik/ssl_key.pem -b 192.168.1.59:40406 -w 2 domogik.admin.application:app
`

**Comment by fritz-smh** [comment]
can you create issues for your remaining bugs ?
