### ISSUE TITLE
Develop branch: global config notice doesn't get away.

### ISSUE THREAD

**Issue by jschaeke** [domogik/domogik#499]
I had problems to fix the global config notice in the admin screen after upgrade from 0.5.2. Seems like printer name and ip are mandatory fields in order to save. It took me several attempts until I guessed printer fields had to be filled in. I don't have a printer and don't see why domogik would need one?
PS : successful has 1 l at the end (see that typo every time we adapt configuration in admin).

**Comment by fritz-smh** [comment]
The printer field should not be mandatory indeed.
The use case of the printer is for the butler to be able to print some data. For example the shopping list. This is not something yet available on butler side ;)

I will fix all this.

**Comment by fritz-smh** [comment]
Fixed.
I reviewed the layout to be more clear with some descriptions. Can you have a look and reopen if not clear/ok ?

**Comment by jschaeke** [comment]
yes looks good and I can leave the printer empty; thanks. just found a typo Externel instead of external.
