### ISSUE TITLE
Plugin "not-configured" at start

### ISSUE THREAD

**Issue by overload08** [domogik/domogik#506]
When domogik restart, hue and notify plugins are in "not-configured" mode.
As i have in DB, all plugins are ok.

https://pastebin.com/gkE5JMtC 
https://pastebin.com/mp8n5XNH 
https://snag.gy/fGg36N.jpg

**Comment by fritz-smh** [comment]
It is ok since we merge nico's PR, correct ?

**Comment by overload08** [comment]
Yes, no more errors!

Envoyé depuis mon mobile Huawei

-------- Message original --------
Objet : Re: [domogik/domogik] Plugin "not-configured" at start (#506)
De : Fritz SMH
À : domogik/domogik
Cc : OverLoad ,Author


It is ok since we merge nico's PR, correct ?
