### ISSUE TITLE
Datatype : DT_Number, use of Min and Max params in sensor/command 

### ISSUE THREAD

**Issue by jaywax** [domogik/domogik#512]
Hi,
To have the possibility to use the params "min" and "max" of a DT_Number directly in sensors or command.

**Comment by cereal2nd** [comment]
so you want to use these as parameters for a command?
What exactly do you want to use this for in a sensor?

**Comment by jaywax** [comment]
Let's take for example a device to choice a channel number between 1 and 6, and as there is no DT_type choice yet (to my knowledge), if the min and max were directly encoded in the DT_Type, it could be easier to use in the plugin.
I wanted to use that for https://github.com/jaywax/domogik-plugin-mprsg6z/wiki/Specifications (Channel choice).
