### ISSUE TITLE
Scenarios : Action isn't done while Test condition seems to be ok.

### ISSUE THREAD

**Issue by jaywax** [domogik/domogik#515]
Hello,
Have this scenario enabled in DMG : https://snag.gy/1VriUy.jpg
Here is the log : https://gist.github.com/jaywax/fa311a6b9b4ef26192e6020c3e9e918f
The addition of values seems to be good, but the command isn't sent to the corresponding plugin.
In addition, the whole domogik doesn't to respond anymore. I have to restart domogik + domoweb.

Thanks.

**Comment by fritz-smh** [comment]
Which Domogik release ? 0.5 ?

**Comment by jaywax** [comment]
Hello,
This is the version : domogik_version=0.5.2

**Comment by fritz-smh** [comment]
Fixed with the PR
