### ISSUE TITLE
Info.json : in a device type parameter, allow to use a kind of device type as type

### ISSUE THREAD

**Issue by fritz-smh** [domogik/domogik#527]
The idea is to be able to link a device to another one. Example : 

For the ipx800 relayboard, we could create a master device for an ipx board with ip, login, password as parameters. We could then have other devices related to the features of the board (relai, analog input, digital input) and for these devices having a 'ipx device' parameter. This would avoid to configure ip+login+password for all the relay devices of an ipx device.

**Comment by cereal2nd** [comment]
should the ip + login+ pass not be a plugin config?

**Comment by jaywax** [comment]
not if we have more than one ipx800.

**Comment by tikismoke** [comment]
Could be useful for other plugins too.

Like ebus if you have more than one interface and others I think too.

Le 31 juillet 2017 15:54:58 GMT+02:00, jaywax <notifications@github.com> a écrit :
>not if we have more than one ipx800.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/domogik/domogik/issues/527#issuecomment-319073890

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.
