### ISSUE TITLE
info.json can use choice in configuration section

### ISSUE THREAD

**Issue by Basilic** [domogik/domogik#528]
I need to use a choices list on my configuration plugin.

Domogik seems can't validate it.

**Comment by cereal2nd** [comment]
this is already supported in develop ....

**Comment by fritz-smh** [comment]
Iirc whe we spoke about this on irc with basilic, this exists in a part of the json (devices config maybe) and not in another one (global config).

To check...

**Comment by cereal2nd** [comment]
as far as i can see its also in the global config ...
