### ISSUE TITLE
DB sensor history optimization

### ISSUE THREAD

**Issue by Nico0084** [domogik/domogik#539]
Hi,

I had search how optimize sensor history request, after many try it seems that improve core_sensor_history table index is the best way.
So adding a index with a composite key (sensor_id and date) improve significatively request between two date.
Perfomance eg:

- Before 

> SELECT min(core_sensor_history.value_num) AS min_1, max(core_sensor_history.value_num) AS max_1, avg(core_sensor_history.value_num) AS avg_1, sum(core_sensor_history.value_num) AS sum_1 FROM core_sensor_history WHERE core_sensor_history.sensor_id = 112 AND date >= '2017-09-01 00:00:00' AND date < '2017-09-20 00:00:00';
> +--------+---------+-------------------+-------------------+
> | min_1  | max_1   | avg_1             | sum_1             |
> +--------+---------+-------------------+-------------------+
> | 140.16 | 4366.56 | 594.0708598095333 | 21895669.67999997 |
> +--------+---------+-------------------+-------------------+
> 1 row in set (3 min 33,40 sec)
> 

EXPLAIN of this request : 

> +----+-------------+---------------------+------------+------+--------------------------------------------------------------+----------------------------------+---------+-------+---------+----------+-------------+
> | id | select_type | table               | partitions | type | possible_keys                                                | key                              | key_len | ref   | rows    | filtered | Extra       |
> +----+-------------+---------------------+------------+------+--------------------------------------------------------------+----------------------------------+---------+-------+---------+----------+-------------+
> |  1 | SIMPLE      | core_sensor_history | NULL       | ref  | ix_core_sensor_history_date,ix_core_sensor_history_sensor_id | ix_core_sensor_history_sensor_id | 4       | const | 1127802 |    12.79 | Using where |
> +----+-------------+---------------------+------------+------+--------------------------------------------------------------+----------------------------------+---------+-------+---------+----------+-------------+
> 

- After 

> SELECT min(core_sensor_history.value_num) AS min_1, max(core_sensor_history.value_num) AS max_1, avg(core_sensor_history.value_num) AS avg_1, sum(core_sensor_history.value_num) AS sum_1 FROM core_sensor_history WHERE core_sensor_history.sensor_id = 112 AND date >= '2017-09-01 00:00:00' AND date < '2017-09-20 00:00:00';
> +--------+---------+-------------------+-------------------+
> | min_1  | max_1   | avg_1             | sum_1             |
> +--------+---------+-------------------+-------------------+
> | 140.16 | 4366.56 | 594.0708598095333 | 21895669.67999997 |
> +--------+---------+-------------------+-------------------+
> 1 row in set (1,35 sec)
> 

EXPLAIN of this request : 

> +----+-------------+---------------------+------------+-------+------------------------------------------------------------------------+-----------+---------+------+-------+----------+----------------------------------+
> | id | select_type | table               | partitions | type  | possible_keys                                                          | key       | key_len | ref  | rows  | filtered | Extra                            |
> +----+-------------+---------------------+------------+-------+------------------------------------------------------------------------+-----------+---------+------+-------+----------+----------------------------------+
> |  1 | SIMPLE      | core_sensor_history | NULL       | range | ix_core_sensor_history_date,ix_core_sensor_history_sensor_id,sensor_id | sensor_id | 9       | NULL | 71822 |   100.00 | Using index condition; Using MRR |
> +----+-------------+---------------------+------------+-------+------------------------------------------------------

------------------+-----------+---------+------+-------+----------+----------------------------------+

- Result : 3 min 33,40 sec to 1,35 sec, very very faster :)

Mysql command is  :
`ALTER TABLE core_sensor_history ADD INDEX (sensor_id, date);`

But I don't know how to do migration db in domogik install, so I let you do ;)

Other improvement should do an `OPTIMIZE TABLE core_sensor_history;` regulary.

**Comment by fritz-smh** [comment]
Very good !
We will include it in 0.6.

About the optimize, there is now the dmg_cron (used for devices deletion in background each hour) : we could use it to do the optimize.
The question is how often ? daily, weekly ?

**Comment by cereal2nd** [comment]
optimize should not be needed, except if you delete a device with a lot of
stats.

So maybe we should do the optimize table in the delete device cron.

**Comment by tikismoke** [comment]
Fritz if you still have a copy of my 3Go database, could you try the optimise ?

Nico? Do the optimise action took long time? As my db go through 2011 I think it could be useful (lots of old value/date/sensor/device).

**Comment by Nico0084** [comment]
For my part,

**core_sensor_history** table with 6773156 rows for 87 sensors 

about 2 mins to build  index with a composite key

**Comment by cereal2nd** [comment]
people that added this index manually should delete it, and then run the reinstall script or the db-upgrade procedure
