### ISSUE TITLE
Add plugin history status

### ISSUE THREAD

**Issue by Nico0084** [domogik/domogik#544]
Idea to help developper and user debuging.

Keep the status of the plugins with a comment for the last events.

- in new tables core-plugin-histotry-status
- something like 10 or 20 last status should be enough
  (using no duplicate data would be the best, but continue store the last event duplicate)
- Store : 
    - plugin status (alive, dead, stopped...)
    - a detail like small comment (limited to 200 chars ?)
    - the timestamp
- from Plugin class call a callback at each STATUS_HBEAT (self._send_status())
- this callback could be use by developper to set the comment (eg : "unable to retreive web service ..." , "lost port com....." , log of critical error, .....)
- manager setstatus() could also use the comment to add some detail. (Stopped reason, start manually , ....)
- in admin add page/plugin to list last status.
- this could be extend for core-component.

**Comment by vdomos** [comment]
Good idea to display plugin status in the admin, if I understood correctly.
A management of these statuses in the scenarios can also be interesting for
external notifications

2018-04-11 9:37 GMT+02:00 Nico0084 <notifications@github.com>:
