### ISSUE TITLE
Issue installing on Debian Jessie

### ISSUE THREAD

**Issue by starnight84** [domogik/domogik#546]
i all
I just install this serveur for the first time and a trouble appear on an debian jessie
i expose all informations

during the installation No error appear  << ... Everythink seems ok, you should be able to start  ... >>

I follow the The first actions in your Errors and solutions page

i check the log files
grep ERROR /var/log/domogik/*
/var/log/domogik/core_xplgw.log:2018-05-25 03:35:43,965 domogik-xplgw ERROR Updating client list failed, no response from manager (try number 1/5)
/var/log/domogik/core_xplgw.log:2018-05-25 04:02:20,125 domogik-xplgw ERROR Updating client list failed, no response from manager (try number 1/5)
/var/log/domogik/core_xplgw.log:2018-05-25 04:22:11,347 domogik-xplgw ERROR Updating client list failed, no response from manager (try number 1/5)

I check the Check the process status
ps -fu domogik | grep dmg_
domogik  29451     1  0 04:21 ?        00:00:12 /usr/bin/python /usr/local/bin/dmg_broker
domogik  29475 29449  0 04:21 ?        00:00:00 -su -c /usr/local/bin/dmg_forwarder >/dev/null 
domogik  29480 29475  0 04:21 ?        00:00:00 /usr/bin/python /usr/local/bin/dmg_forwarder
domogik  29489     1  0 04:21 ?        00:00:04 /usr/bin/python /usr/local/bin/dmg_hub
domogik  29531     1  0 04:21 ?        00:00:00 /usr/bin/python /usr/local/bin/dmg_manager -a -d -x -s -b
domogik  29536 29531  0 04:21 ?        00:00:08 /usr/bin/python /usr/local/bin/dmg_manager -a -d -x -s -b
--> no processes for the administration web interface
--> 2 processes for MQ forwarder (dmg_forwarder)

Check if dbmgr is up
ps -fu domogik | grep dbmgr
domogik  29583     1  0 04:21 ?        00:00:00 /usr/bin/python /opt/dmg/domogik-0.5.2/src/domogik/bin/dbmgr.py
domogik  29601 29583  0 04:21 ?        00:00:04 /usr/bin/python /opt/dmg/domogik-0.5.2/src/domogik/bin/dbmgr.py
--> Seems OK

Check if xplgw is up
ps -fu domogik | grep xplgw
domogik  29627     1  0 04:21 ?        00:00:00 /usr/bin/python /opt/dmg/domogik-0.5.2/src/domogik/bin/xplgw.py
domogik  29644 29627  0 04:22 ?        00:00:05 /usr/bin/python /opt/dmg/domogik-0.5.2/src/domogik/bin/xplgw.py
--> Seems OK

Check if services are available
netstat -tnpl | grep 404
tcp        0      0 192.168.1.210:40410     0.0.0.0:*               LISTEN      29451/python    
tcp        0      0 192.168.1.210:40411     0.0.0.0:*               LISTEN      29480/python    
tcp        0      0 192.168.1.210:40412     0.0.0.0:*               LISTEN      29480/python
--> No port 40406

The  xPL seems work correctly  no file log in /var/log/domogik/xplgw.log
and the xplhub log 
| Client id             | Client source                      | Interval | Last seen                  | Status  | Nb OK  | Nb KO  |
|-----------------------+------------------------------------+----------+----------------------------+---------+--------+--------|
| 192.168.1.210_49132   | domogik-manager.serveur            |        5 | 2018-05-25T05:06:55.137312 | alive   |     12 |      0 |
| 192.168.1.210_39994   | domogik-xplgw.serveur              |        5 | 2018-05-25T05:07:01.034171 | alive   |     13 |      0 |
|-----------------------+------------------------------------+----------+----------------------------+---------+--------+--------|
--> Seems OK

when a send restart domogik "/etc/init.d/domogik restart"    this appear
 * Stopping Plugins... Done.
 * Stopping Manager... Done.
 * Stopping XPL... Done.
 * Stopping 0MQ broker... Done.
 * Stopping 0MQ forwarder... Done.
 * Starting 0MQ broker ...Pas de répertoire, connexion avec HOME=/
 Done.
 * Starting 0MQ forwarder ... Done.
 * Starting xPL (python version) ...Pas de répertoire, connexion avec HOME=/
 Done.
 * Starting Manager (with -a -d -x -s -b) ...  Done.

some one have an idea

thx a lot
Starnight84

**Comment by vdomos** [comment]
Hi,
--> no processes for the administration web interface
--> No port 40406

you can start the "admin" process manually in foreground  with a 

    /opt/dmg/domogik-0.5.2/src/domogik/bin/admin.py -f

to see if any other errors appear.

Kill all admin and gunicorn process before.

**Comment by starnight84** [comment]
Hi VDomos  
thx for your answer
i try to start it manually and this error appear

 `# /opt/dmg/domogik-0.5.2/src/domogik/bin/admin.py -f`

> Traceback (most recent call last):
>   File "/opt/dmg/domogik-0.5.2/src/domogik/bin/admin.py", line 67, in <module>
>     zmq.eventloop.ioloop.install()
>   File "/usr/lib/python2.7/dist-packages/zmq/eventloop/ioloop.py", line 184, in install
>     assert (not ioloop.IOLoop.initialized()) or \
> AttributeError: type object 'IOLoop' has no attribute 'initialized'

you say "Kill all admin and gunicorn process before." 
i have no gunicorn  server installed 
i don't know what admin process you thinks

thx a lot for your help
Starnight84

**Comment by vdomos** [comment]
Sorry Gunicorn is only on 0.6 version.

I don't know this error, but you have probleme with zmq .
Did you use this documentation to install: http://domogik.readthedocs.io/en/master/users/installation/index.html ?

Can you check zmq package version and compare with documentation.
Run again the "Domogik-mq" install.

**Comment by Darknet** [comment]
I thinks it's similar to #556
