### ISSUE TITLE
Info.json question and validation

### ISSUE THREAD

**Issue by tikismoke** [domogik/domogik#551]
I've got a bug on domodroid from @jaywax i'm pretty sure it's come from the plugin but need your confirmation.

He's got a commant like this in the rest/device/
`Json list_command={"switch":{"return_confirmation":true,"id":1058,"parameters":[{"conversion":"","data_type":"DT_Switch","key":"current"}],"name":"Switch On or Off"},"pulse":{"return_confirmation":true,"id":1061,"parameters":[],"name":"Set to a level"}}`

The "pulse" command seems to have no parameters.
Is it possible?

Going to catch this in Domodroid but it seems also an domogik info.json validation issue no?

**Comment by jaywax** [comment]
Hello Tiki, i'm planning to apdat a plugin from Fritz --> https://github.com/jaywax/domogik-plugin-ipx800/blob/master/info.json to domogik master.
I'have surely made some mistakes :)

**Comment by jaywax** [comment]
And no, dmg doesn't cry when i launch the plugin (aussi peu aboutit soit-il, désolé trop compliqué à écire en anglais)...
