### ISSUE TITLE
No admin interface service is working

### ISSUE THREAD

**Issue by Nosreme1** [domogik/domogik#556]
Hello,
I have no processes for the administration web interface. When i restart domogik i have this output
"/etc/init.d/domogik start
 * Starting 0MQ broker ... Done.
 * Starting 0MQ forwarder ... Done.
 * Starting xPL (python version) ... Done.
 * Starting Manager (with -a -d -x -s -b) ...  Done."
instead that output:
"* Starting 0MQ broker ... Done.
* Starting 0MQ forwarder ... Done.
* Starting xPL (python version)... Done.
* Starting Manager (with -d -r -x -s)... Done.
* Starting the admin interface ... Done."
The web interface service is missing.
Thanks

**Comment by Nico0084** [comment]
Hi
Please let us your domogik revision and platform
Check your depencies with "pip freeze" and post it
rgds

**Comment by Darknet** [comment]
Hi'

I've the same issue with debian 9 and using installation from here
https://domogik.readthedocs.io/en/master/users/installation/index.html#installation

I'm using python version 2.7.13 and this is the return of the command 

alabaster==0.7.8
alembic==1.0.10
attrs==16.3.0
Babel==2.3.4
backports-abc==0.5
blinker==1.3
boto==2.44.0
chardet==2.3.0
Click==7.0
colorama==0.3.7
constantly==15.1.0
crcmod==1.7
cryptography==1.7.1
docutils==0.13.1
dominate==2.3.5
Domogik==0.5.0
Domogik-MQ==1.3
enum34==1.1.6
ephem==3.7.6.0
feedparser==5.1.3
file-magic==0.3.0
Flask==1.0.2
Flask-Babel==0.12.2
Flask-Bootstrap==3.3.7.1
Flask-Login==0.4.1
-e git://github.com/sysr-q/flask-themes2.git@b51ddc43860cd4924f962ad735c9229935dd6354#egg=Flask_Themes2
Flask-WTF==0.12
futures==3.0.5
google-compute-engine==2.8.13
idna==2.2
imagesize==0.7.1
incremental==16.10.1
ipaddress==1.0.17
itsdangerous==1.1.0
Jinja2==2.10.1
keyring==10.1
keyrings.alt==1.3
linux-metrics==0.1.4
Mako==1.0.7
MarkupSafe==1.1.0
mysqlclient==1.3.7
netifaces==0.10.9
PAM==0.4.2
Pillow==4.0.0
psutil==5.0.1
psycopg2==2.6.2
pyasn1==0.1.9
pyasn1-modules==0.0.7
pycrypto==2.6.1
Pygments==2.2.0
pygobject==3.22.0
pyinotify==0.9.6
PyMySQL==0.9.3
pyOpenSSL==16.2.0
pyserial==3.2.1
python-dateutil==2.7.3
python-editor==1.0.3
python-magic==0.4.15
pytz==2016.7
pyxdg==0.25
pyzmq==16.0.2

The following command
/etc/init.d/domogik status manager
return
 * manager is running
 * dbmgr is running
 * admin is not running

I use this page for resolve the issue

https://domogik.readthedocs.io/en/master/users/errors/index.html

and the command
ps -fu domogik
return

UID        PID  PPID  C STIME TTY          TIME CMD
domogik   1830     1  0 11:58 ?        00:00:41 /usr/bin/python /usr/local/bin/dmg_broker
domogik   1836  1831  0 11:58 ?        00:00:00 -su -c /usr/local/bin/dmg_forwarder >/dev/null 
domogik   1847  1836  0 11:58 ?        00:00:02 /usr/bin/python /usr/local/bin/dmg_forwarder
domogik   1851     1  0 11:58 ?        00:00:26 /usr/bin/python /usr/local/bin/dmg_hub
domogik   2226     1  0 11:59 ?        00:00:02 /usr/bin/python /usr/local/bin/dmg_manager -a -d -x -s -b
domogik   2228  2226  0 11:59 ?        00:00:41 /usr/bin/python /usr/local/bin/dmg_manager -a -d -x -s -b
domogik   2275     1  0 11:59 ?        00:00:04 /usr/bin/python /opt/dmg/domogik-0.5.2/src/domogik/bin/db
domogik   2318     1  0 11:59 ?        00:00:04 /usr/bin/python /opt/dmg/domogik-0.5.2/src/domogik/bin/xp
domogik   2353  2275  0 11:59 ?        00:00:18 /usr/bin/python /opt/dmg/domogik-0.5.2/src/domogik/bin/db
domogik   2381     1  0 11:59 ?        00:00:04 /usr/bin/python /opt/dmg/domogik-0.5.2/src/domogik/bin/sc
domogik   2411     1  0 11:59 ?        00:00:04 /usr/bin/python /opt/dmg/domogik-0.5.2/src/domogik/bin/bu
domogik   2428  2318  0 11:59 ?        00:00:23 /usr/bin/python /opt/dmg/domogik-0.5.2/src/domogik/bin/xp
domogik   2451  2381  0 11:59 ?        00:00:18 /usr/bin/python /opt/dmg/domogik-0.5.2/src/domogik/bin/sc
domogik   2462  2411  0 11:59 ?        00:00:17 /usr/bin/python /opt/dmg/domogik-0.5.2/src/domogik/bin/bu


Thanks in advance

**Comment by tikismoke** [comment]
Isn't it a gunicorn issue not running?

**Comment by tikismoke** [comment]
Try tu run admin by hand to see if it give you a more explicit error message.

**Comment by Darknet** [comment]
Ok i use this to run manually

/opt/dmg/domogik-0.5.2/src/domogik/bin/admin.py -f

and return

Traceback (most recent call last):

  File "/opt/dmg/domogik-0.5.2/src/domogik/bin/admin.py", line 48, in <module>
    from domogik.admin.application import app as admin_app

  File "/opt/dmg/domogik-0.5.2/src/domogik/admin/application.py", line 32, in <module>
    from flask.ext.themes2 import Themes, render_theme_template

ImportError: No module named ext.themes2

**Comment by tikismoke** [comment]
Ok, try a pip install -.... requirements.txt or something like this.

Nico it looks like a problem I already have no?

**Comment by Darknet** [comment]
Ok requirements.txt appear on this location
/opt/dmg/domogik-mq-1.4/requirements.txt
/opt/dmg/domogik-0.5.2/src/flask-themes2/requirements.txt
/opt/dmg/domogik-0.5.2/requirements.txt

the first two files only have a ".", the other have two lines
Flask>=0.6
simplejson

both requierements satisfied.

other questions if you tries to install libzmq-dev, with apt only is available for Debian Jessie (debian 8) and fails with 9.

**Comment by tikismoke** [comment]
Avoid using apt as possible for domogik :)

You'll get error on an upgrade a day or later.

Do not know what more to say you, maybe fritz or Nico will have more information.

**Comment by Darknet** [comment]
I do all installation process, equal to the installation page.
