### ISSUE TITLE
Add support to upgrade devices when a newer version of the plugin is installed

### ISSUE THREAD

**Issue by cereal2nd** [domogik/domogik#72]
when anewer version of the plugin is found all devices that have client_version in devices table lower then the json version will be marked as 'need to upgrade'.

The interface will then show the changes that will be done and the user needs to confirm
- if the user decides to install a new version he will be forwarded (after install) to the device upgrade wizzard
- the moment manager detects a new json version for a plugin
- it will disable (no action needed as client_version is not equal to json_version) all devices for that plugin and put them in the upgrade queue
- and then a user action is required to upgrade

**Comment by Cereal2nd** [comment]
For all types the data_type Can not be udpated

sensors:
possible: name, conversion, incremental, timeout and all history

commands:
possible: name, return_confirmation, add/remove parameters
not possible: xpl_command

device_type:
possible: id, description, name, add/remove sensors, add/remove commands, add/remove params

xpl_commands:
possible: name, schema, xplstat, add/remove static params, add/remove device params

xpl_stats:
possible: name, schema, add/remove static params, add/remove device params, add/remove dynamic params

For some upgrades we will need to display a form and the user needs to input some values

**Comment by fritz-smh** [comment]
Not sure if this is in cereal TODO for 0.5 ?

Moved in 0.5 milestone for now

**Comment by cereal2nd** [comment]
the system will work as follow:
1- new plugin installs
2- manager detects this and checks what devices need upgrade
3- devices needing upgrade get state upgrade (and will be disabled)
4- via admin interface the user starts the device upgrade process
5- a new device is generated based on the old device (and will start storing sensor values)
6- all sensors history is moved from the old sensors to the new sensors (handled by cron as this can take some time)
7- the old device will be marked for deletion (by the user via the admin interface)
8- the old device will be deleted by the cron system
