### ISSUE TITLE
Python 3: pepare the code

### ISSUE THREAD

**Issue by cereal2nd** [domogik/domogik#77]
- Backward compatibility with Python2 should be kept? Would be good but is it possible?

Things to check:
- Don't use : print "foo" but print("foo")
- Don't use : except Exception, e but except Exception as e
- Don't use : <> but !=
- Consider using ''from future'' statement

For the future :
- Don't use : %s and %d but i.e. print("Hello {0}. I'm happy you visit {1}".format("Fred","mysite.com"))

Ressources :
- http://python.dzone.com/articles/making-code-compatible-python
- We can use the tool 2to3 (See http://diveintopython3.org/porting-code-to-python-3-with-2to3.html)

**Comment by Cereal2nd** [comment]
xplhub is blocking this

**Comment by tikismoke** [comment]
No way to see dmg on python3?

My velux klf200 as been update but need python3 to use asyncio in pyvlx :(

Or I need to create an interface between a new domogik plugin for velux and the pyvlx lib?

**Comment by jaywax** [comment]
> No way to see dmg on python3?
> 
> My velux klf200 as been update but need python3 to use asyncio in pyvlx :(
> 
> Or I need to create an interface between a new domogik plugin for velux and the pyvlx lib?

Same need for same usage :+1:

**Comment by tikismoke** [comment]
> > No way to see dmg on python3?
> > My velux klf200 as been update but need python3 to use asyncio in pyvlx :(
> > Or I need to create an interface between a new domogik plugin for velux and the pyvlx lib?
> 
> Same need for same usage +1
@jaywax i used another container dedicated to velux (with python3.5)and get value via mqtt
https://github.com/Julius2342/pyvlx/issues/11#issuecomment-487401335

**Comment by Nico0084** [comment]
Hi,
Working on it, but don't known how many time it's take with how many difficulties ! ?????
That is sure all plugin must be python 3, another unknown is to make them compatible .....

Please be patient ;) la devise de domogik !
