### ISSUE TITLE
Creat a black and White theme

### ISSUE THREAD

**Issue by Cereal2nd** [domogik/domogik#81]
Used for e-ink screens

**Comment by fritz-smh** [comment]
for admin or domoweb ?

**Comment by Cereal2nd** [comment]
admin (a transfered ticket from redmine)

**Comment by fritz-smh** [comment]
Do we really need a black and white theme for e-ink screens ?
I mean, I think this ticket was created for Domoweb, not Domogik...

Using DMW on a reader is a good idea, using DMG admin... not sure at all it is a good idea

**Comment by Cereal2nd** [comment]
ok lets drop this ticket
we can create a new one if people ask for it
