### ISSUE TITLE
Add an agent

### ISSUE THREAD

**Issue by cereal2nd** [domogik/domogik#82]
Create a new core component named 'domogik agent' ?
This agent would be install on all secondary hosts (it will replace the manager roles in 0.2/0.3 for multi host).
this agent would wait for dedicate MQ messages to :

```
install a package
send binary data (package icon, products icons) over the MQ when requested (by the UI mainly)
```

open points :

```
can MQ handle small binary data (pictures) ?
can MQ handle big binary data (zip package). This would allow secondary hosts to not have an internet access and also to launch installations from local zip on the main host
```

**Comment by fritz-smh** [comment]
This was an old ticket (from me I guess).

Today I am not sure anymore we should handle it like this.

My current point of view : we should go towards a distributed architecture : each host can run on its own. And later on we could see how we could handle the failure of the main host (butler, scenario, dbmgr, mq) and let another host take the master role.

Waiting for this, we should do this : 
- each host have the same domogik sources (and so components) (so, no more additionnal agent component to maintain)
- on each host these components are running : manager, admin
- each host is able to discover the other ones and from 1 admin there will be a way to jump to another admin
- some components are up only one one host : domoweb, butler, scenario, ...
