### ISSUE TITLE
Enable/disable scenario from an other

### ISSUE THREAD

**Issue by Cereal2nd** [domogik/domogik#85]
Set possibily to enable/disable a scenario from an other.
Handle case of deleted scenario

**Comment by Cereal2nd** [comment]
TODO
- [ ] make sure we can not delete a referenced scenario
- [ ] make sure we can not reference our own (will crash xplgw and will create orphans)
- [ ] create the actions

**Comment by fritz-smh** [comment]
What is the use case of this issue ? (don't remember)

**Comment by Cereal2nd** [comment]
it was something like, if you set the garden lights on disable the sprinkler scenario

but i'm hitting some problems

**Comment by fritz-smh** [comment]
why not using virtual devices as a flag for this kind of use case ?

**Comment by tikismoke** [comment]
Because in scenario we can not use if then else for now.
So enabling alarm scenario or disable it from another seems easier.

**Comment by fritz-smh** [comment]
isn't a flag (virtual device) more appropriate and more logic ?

A vdevice DT_Bool named "alarm status" could do the trick.

In a scenario you enable/disable it (or from the user interface thanks to
the widget). Then, in other scenarios you do WHEN "alarm status" = on AND
(....).
And the nice thing is that you could see the alarm status just by looking
at the widget.

**Comment by tikismoke** [comment]
It can be add indeed, but it will complicate scenario creation with lots of sensor.
It can be simplier for end user to manage scenario:
when everybody sleep=>enable "full alarm" scenario, disable "callerid notification" scenario, etc
and those both scenario could be very simple.

I think it will make scenario management easier

**Comment by Cereal2nd** [comment]
are we keeping this or are we refusing this?

**Comment by fritz-smh** [comment]
honestly, no idea...

@tikismoke : could we maybe test without to see if this is really so
complicated ? And later if really there is a need we could add the feature.

**Comment by tikismoke** [comment]
Ok for me. Will see at usage if really need.

Didn't try yet the last commit to see how it works.
Maybe just let it as it is for now.
