### ISSUE TITLE
0.3 db migration

### ISSUE THREAD

**Issue by tikismoke** [domogik/domogik#92]
From 0.3 migration does'nt work actually.
This is my structure dump:
http://pastebin.com/Lsr8TncS

And this is the error:
http://pastebin.com/R46GGRNL

Meanning there is a problem with not same datatype or length in the db.

**Comment by Cereal2nd** [comment]
found the problem, db's upgraded from 0.2 to 0.3 are still using myisam, and this should have been innodb

**Comment by Cereal2nd** [comment]
solved with pull request #95
